package ru.neverland.townybuilds;
import java.util.*;
import java.io.IOException;
import org.bukkit.Material;
import org.bukkit.inventory.ItemStack;
import ru.neverland.townybuilds.data.TownData;
import ru.neverland.townybuilds.storage.*;
public final class MarketStorageSmoke {
    static final class Item extends ItemStack {final String key;final int max;int amount;Item(String key,int amount,int max){super();this.key=key;this.amount=amount;this.max=max;}
        public Material getType(){return Material.IRON_INGOT;}public int getAmount(){return amount;}public void setAmount(int n){amount=n;}public int getMaxStackSize(){return max;}public Item clone(){return new Item(key,amount,max);}public boolean isSimilar(ItemStack o){return o instanceof Item i&&key.equals(i.key);}}
    static final class Access implements MarketTransactions.Access {Map<UUID,ItemStack[]> items=new HashMap<>();boolean fail,busy;int commits;
        public ItemStack[] read(UUID town){return StockMath.copy(items.get(town));}public void write(UUID town,ItemStack[] contents){items.put(town,StockMath.copy(contents));}public boolean busy(UUID town){return busy;}public void commit()throws IOException{if(fail)throw new IOException("disk full");commits++;}}
    static final class Inventory implements MarketTransactions.Inventory {final UUID id=UUID.randomUUID();ItemStack[] items=new ItemStack[36];boolean failSave,failWrite;public UUID owner(){return id;}public ItemStack[] read(){return StockMath.copy(items);}public void write(ItemStack[] a){if(failWrite)throw new IllegalStateException("write aborted");items=StockMath.copy(a);}public void save(){if(failSave)throw new IllegalStateException("player save failed");}}
    public static void main(String[] args)throws Exception {
        UUID seller=UUID.randomUUID(),buyer=UUID.randomUUID(),lot=UUID.randomUUID();var town=new TownData(seller,54);var a=new Access();var sample=new Item("iron",1,64);var custom=new Item("ia:iron",1,64);var original=new ItemStack[54];for(int i=0;i<8;i++)original[i]=new Item("iron",64,64);original[9]=new Item("ia:iron",32,64);a.items.put(seller,original);a.items.put(buyer,new ItemStack[54]);
        a.busy=true;check(MarketTransactions.open(town,a,lot,sample,500).equals("BUSY"),"editor lock");a.busy=false;a.fail=true;failure(()->MarketTransactions.open(town,a,lot,sample,500));check(StockMath.count(a.read(seller),sample)==512&&town.marketStock().isEmpty(),"failed escrow creation rolls back source");a.fail=false;
        MarketTransactions.open(town,a,lot,sample,500);MarketTransactions.open(town,a,lot,sample,500);check(StockMath.count(a.read(seller),sample)==12&&StockMath.count(a.read(seller),custom)==32,"listing removes exact stock once and preserves custom items");failure(()->MarketTransactions.open(town,a,lot,custom,500));
        UUID first=UUID.randomUUID(),second=UUID.randomUUID();MarketTransactions.reserve(town,a,lot,first,buyer,true,400);check(MarketTransactions.reserve(town,a,lot,second,buyer,true,400).equals("STOCK_LOW"),"competing buyer cannot oversell");MarketTransactions.reserve(town,a,lot,first,buyer,true,400);check(town.marketStock().get(lot).available()==100,"reservation replay stable");
        failure(()->MarketTransactions.reserve(town,a,lot,first,buyer,true,399));failure(()->MarketTransactions.reserve(town,a,lot,UUID.randomUUID(),seller,true,1));
        a.fail=true;failure(()->MarketTransactions.deliver(town,a,lot,first));check(StockMath.total(a.read(buyer))==0&&town.marketStock().get(lot).holds().get(first).status().equals("HELD"),"failed delivery restores receipt and warehouse");a.fail=false;
        var full=new ItemStack[54];Arrays.setAll(full,i->new Item("other",64,64));a.items.put(buyer,full);check(MarketTransactions.deliver(town,a,lot,first).equals("FULL"),"full city keeps paid reserve");a.items.put(buyer,new ItemStack[54]);
        MarketTransactions.close(town,a,lot);check(StockMath.count(a.read(seller),sample)==112,"closing returns only unreserved remainder");MarketTransactions.deliver(town,a,lot,first);MarketTransactions.deliver(town,a,lot,first);check(StockMath.count(a.read(buyer),sample)==400,"paid delivery completes after listing closed once");failure(()->MarketTransactions.forget(town,a,lot));MarketTransactions.acknowledge(town,a,lot,first);MarketTransactions.forget(town,a,lot);MarketTransactions.forget(town,a,lot);
        var inventory=new Inventory();UUID local=UUID.randomUUID(),order=UUID.randomUUID();MarketTransactions.open(town,a,local,custom,32);MarketTransactions.reserve(town,a,local,order,inventory.id,false,16);MarketTransactions.deliver(town,a,local,order);MarketTransactions.deliver(town,a,local,order);check(town.marketStock().get(local).holds().get(order).status().equals("PICKUP"),"local purchase remains escrowed until collected");failure(()->MarketTransactions.acknowledge(town,a,local,order));
        var stranger=new Inventory();failure(()->MarketTransactions.claim(town,a,local,order,stranger));Arrays.setAll(inventory.items,i->new Item("other",64,64));check(MarketTransactions.claim(town,a,local,order,inventory).equals("FULL"),"full personal inventory preserves pickup");inventory.items=new ItemStack[36];
        a.fail=true;failure(()->MarketTransactions.claim(town,a,local,order,inventory));check(StockMath.total(inventory.items)==0&&town.marketStock().get(local).holds().get(order).status().equals("PICKUP"),"claim intent save failure cannot give items");a.fail=false;
        inventory.failSave=true;failure(()->MarketTransactions.claim(town,a,local,order,inventory));check(StockMath.count(inventory.items,custom)==16&&town.marketStock().get(local).holds().get(order).status().equals("CLAIM_PENDING"),"interrupted player save leaves claim pending");inventory.failSave=false;
        var restarted=new TownData(seller,54);town.marketStock().values().forEach(restarted::putMarketStock);check(MarketTransactions.claim(restarted,a,local,order,inventory).equals("CLAIM_PENDING")&&StockMath.count(inventory.items,custom)==16,"restart cannot replay uncertain personal claim");MarketTransactions.resolveClaim(restarted,a,local,order,true);MarketTransactions.claim(restarted,a,local,order,inventory);check(StockMath.count(inventory.items,custom)==16,"resolved received claim cannot duplicate");MarketTransactions.acknowledge(restarted,a,local,order);
        UUID refund=UUID.randomUUID();MarketTransactions.reserve(restarted,a,local,refund,inventory.id,false,16);MarketTransactions.close(restarted,a,local);MarketTransactions.refund(restarted,a,local,refund);MarketTransactions.refund(restarted,a,local,refund);check(StockMath.count(a.read(seller),custom)==16,"unpaid hold after closing returns to city once");
        var tiny=new ru.neverland.townybuilds.api.MarketStock(UUID.randomUUID(),new Item("unstackable",1,1),36,36,true,Map.of());check(tiny.cargo(36).length==36&&Arrays.stream(tiny.cargo(36)).allMatch(i->i.getAmount()==1),"unstackable cargo is split correctly");
        System.out.println("MarketStorageSmoke OK: physical listing escrow, competing purchases, replay, metadata, city delivery, closed-offer refunds, personal claims, full inventories and ambiguous claim recovery");
    }
    interface Action{void run()throws Exception;}static void failure(Action a)throws Exception{boolean failed=false;try{a.run();}catch(Exception ex){failed=true;}check(failed,"expected failure");}static void check(boolean value,String text){if(!value)throw new AssertionError(text);}
}
