package ru.neverland.townybuilds;
import java.util.*;import java.nio.file.*;import java.io.IOException;
import ru.neverland.core.*;import ru.neverland.townybuilds.shop.*;
public final class ShopReliabilitySmoke {
    static int checks;static void ok(boolean v,String m){checks++;if(!v)throw new AssertionError(m);}
    interface Action{void run()throws Exception;}static void reject(Action a)throws Exception{try{a.run();}catch(Exception expected){checks++;return;}throw new AssertionError("expected rejection");}
    static final class Bank implements PurchaseSaga.Gateway<ShopOrder>{int debits,credits,reservations;boolean unknownDebit,unknownCredit;String receipt="MISSING";public String ready(ShopOrder o){return null;}public String reserve(ShopOrder o){if(receipt.equals("MISSING")){reservations++;receipt="HELD";}return receipt;}public boolean debit(ShopOrder o){debits++;if(unknownDebit)throw new IllegalStateException("bank acknowledgement lost");return true;}public String deliver(ShopOrder o){receipt="PICKUP";return receipt;}public boolean credit(ShopOrder o){credits++;if(unknownCredit)throw new IllegalStateException("seller acknowledgement lost");return true;}public String refund(ShopOrder o){receipt="RETURNED";return receipt;}public String receipt(ShopOrder o){return receipt;}public void acknowledge(ShopOrder o){receipt="MISSING";}}
    static ShopOrder order(long now){return new ShopOrder(UUID.randomUUID(),UUID.randomUUID(),UUID.randomUUID(),"IRON_INGOT",4,25,now,"PREPARED",now,"Создана",false);}
    public static void main(String[] args)throws Exception{
        Path dir=Files.createTempDirectory("shop-reliability-");Path file=dir.resolve("shop.yml");ShopJournal journal=new ShopJournal(file);journal.load();long now=1_000_000;var o=order(now);journal.put(o);var bank=new Bank();bank.unknownDebit=true;ShopJournal initial=journal;
        reject(()->PurchaseSaga.advance(o.id(),now,1000,initial,bank));ok(bank.debits==1&&journal.order(o.id()).paymentStep().equals("DEBIT_PENDING"),"ambiguous debit is durable");
        journal=new ShopJournal(file);journal.load();for(int i=0;i<10;i++)PurchaseSaga.advance(o.id(),now,1000,journal,bank);ok(bank.debits==1,"restart never repeats ambiguous debit");
        journal.put(PurchaseSaga.resolve(journal.order(o.id()),"debit-paid",now));PurchaseSaga.advance(o.id(),now,1000,journal,bank);bank.unknownCredit=true;ShopJournal current=journal;reject(()->PurchaseSaga.advance(o.id(),now,1000,current,bank));
        journal=new ShopJournal(file);journal.load();PurchaseSaga.advance(o.id(),now,1000,journal,bank);ok(bank.credits==1&&journal.order(o.id()).paymentStep().equals("CREDIT_PENDING"),"ambiguous credit cannot replay");
        journal.put(PurchaseSaga.resolve(journal.order(o.id()),"credit-paid",now));PurchaseSaga.advance(o.id(),now,1000,journal,bank);ok(!journal.order(o.id()).finalized()&&bank.receipt.equals("PICKUP"),"complete money keeps unclaimed goods");bank.receipt="CLAIMED";PurchaseSaga.advance(o.id(),now,1000,journal,bank);PurchaseSaga.advance(o.id(),now,1000,journal,bank);ok(journal.order(o.id()).finalized()&&bank.debits==1&&bank.credits==1&&bank.reservations==1,"completion is idempotent");
        ShopJournal done=journal;reject(()->done.put(new ShopOrder(o.id(),o.seller(),o.buyer(),"IRON_INGOT",0,25,now,"PREPARED",now,"",false)));reject(()->PurchaseSaga.resolve(done.order(o.id()),"debit-unpaid",now));
        var second=order(now);journal.put(second);var failure=new PurchaseSaga.Store<ShopOrder>(){public ShopOrder order(UUID id){return second;}public void put(ShopOrder changed)throws IOException{throw new IOException("disk full before bank");}};var untouched=new Bank();reject(()->PurchaseSaga.advance(second.id(),now,1000,failure,untouched));ok(untouched.debits==0,"pending intent must persist before bank call");
        byte[] valid=Files.readAllBytes(file);Files.writeString(file,"schema: 1\norders: [broken]\n");var damaged=new ShopJournal(file);reject(damaged::load);byte[] bad=Files.readAllBytes(file);reject(()->damaged.put(second));ok(Arrays.equals(bad,Files.readAllBytes(file)),"corrupt journal is not overwritten");Files.write(file,valid);
        Path target=dir.resolve("atomic.yml");AtomicFiles.write(target,()->"old");reject(()->AtomicFiles.write(target,()->{throw new IllegalStateException("serialization failure");}));ok(Files.readString(target).equals("old")&&!AtomicFiles.writable(target),"snapshot failure leaves last durable version");reject(()->AtomicFiles.write(target,()->"forbidden retry"));AtomicFiles.loaded(target);AtomicFiles.write(target,()->"new");var metrics=AtomicFiles.metrics().stream().filter(m->m.file().equals(target.toString())).findFirst().orElseThrow();ok(metrics.writes()==2&&metrics.failures()==1&&metrics.bytes()==6&&metrics.maximumNanos()>0,"write latency and failures measured");
        Path blocked=dir.resolve("blocked");Files.createDirectories(blocked);Files.writeString(blocked.resolve("original"),"keep");reject(()->AtomicFiles.write(blocked,()->"replacement"));ok(Files.readString(blocked.resolve("original")).equals("keep")&&!AtomicFiles.writable(blocked),"rename failure preserves target and blocks changes");
        ok(ShopService.cents(.01)==1&&ShopService.cents(19.99)==1999,"exact price cents");reject(()->ShopService.cents(.001));reject(()->ShopService.cents(Double.NaN));
        System.out.println("ShopReliabilitySmoke OK: "+checks+" checks");
    }
}
