package ru.neverland.townypolicies.command;
import org.bukkit.command.*;
import org.bukkit.entity.Player;
import com.palmergames.bukkit.towny.TownyAPI;
import java.util.*;
import ru.neverland.townypolicies.NeverLandTownyPolicies;
import ru.neverland.townypolicies.gui.PoliciesMenu;
import ru.neverland.townypolicies.service.*;
public final class PoliciesCommand implements CommandExecutor,TabCompleter {
    private final NeverLandTownyPolicies plugin;private final PoliciesService service;private final PoliciesMenu menu;
    public PoliciesCommand(NeverLandTownyPolicies plugin,PoliciesService service,PoliciesMenu menu){this.plugin=plugin;this.service=service;this.menu=menu;}
    private void count(String[] a,int n,String usage){if(a.length!=n)throw new IllegalArgumentException(usage);}
    @Override public boolean onCommand(CommandSender sender,Command command,String label,String[] args){try{execute(sender,args);}catch(Exception e){Ui.tell(sender,"&c"+(e.getMessage()==null?"Операция не завершена; проверьте консоль":e.getMessage()));if(!(e instanceof IllegalArgumentException||e instanceof IllegalStateException))plugin.getLogger().log(java.util.logging.Level.WARNING,"Ошибка сохранения указа",e);}return true;}
    private void execute(CommandSender sender,String[] a)throws Exception{String action=a.length==0?"menu":a[0].toLowerCase(Locale.ROOT);if(action.equals("reload")){count(a,1,"/townypolicies reload");if(!sender.hasPermission("neverlandtownypolicies.admin"))throw new IllegalArgumentException("Недостаточно прав");Ui.tell(sender,plugin.reloadPolicies()?"Политики обновлены.":"Настройки не применены; проверьте консоль.");return;}if(!(sender instanceof Player p))throw new IllegalArgumentException("Эта команда доступна в игре");
        if(action.equals("town")||action.equals("set")){if(!p.hasPermission("neverlandtownypolicies.admin"))throw new IllegalArgumentException("Недостаточно прав");count(a,action.equals("town")?2:4,"/townypolicies "+action+" <город>"+(action.equals("set")?" <политика> <режим>":""));var town=TownyAPI.getInstance().getTown(a[1]);if(town==null)throw new IllegalArgumentException("Город не найден");if(action.equals("town"))menu.open(p,town.getUUID(),null,null);else{service.offer(p,town.getUUID(),a[2],a[3],true);review(p);}return;}
        if(action.equals("confirm")){count(a,1,"/t policies confirm");UUID id=service.confirm(p);Ui.tell(p,"Указ города сохранён.");menu.open(p,id,null,null);return;}
        if(!p.hasPermission("neverlandtownypolicies.use"))throw new IllegalArgumentException("Недостаточно прав");var town=service.town(p);if(town==null)throw new IllegalArgumentException("Вы не состоите в городе");switch(action){case "menu"->{count(a,a.length==0?0:1,"/t policies");menu.open(p,town.getUUID(),null,null);}case "info"->{if(a.length<2||a.length>3)throw new IllegalArgumentException("/t policies info <политика> [режим]");menu.open(p,town.getUUID(),a[1],a.length==3?a[2]:null);}case "history"->{count(a,1,"/t policies history");menu.open(p,town.getUUID(),"history",null);}case "choose"->{count(a,3,"/t policies choose <политика> <режим>");service.offer(p,town.getUUID(),a[1],a[2],false);review(p);}case "help"->Ui.tell(p,"/t policies — меню; info <политика> [режим]; choose <политика> <режим>; confirm; history. Выбор мэром или уполномоченным, с подтверждением и ожиданием смены.");default->throw new IllegalArgumentException("Справка: /t policies help");}}
    private void review(Player p){var o=service.offer(p);var g=o.settings().groups().get(o.group());var option=g.options().get(o.mode());Ui.tell(p,"Город «"+TownyAPI.getInstance().getTown(o.town()).getName()+"»: "+g.name()+" → "+option.name()+". "+String.join(" ",option.advantages())+" Издержки: "+String.join(" ",option.disadvantages())+" Следующая смена через "+o.settings().cooldownMillis()/3600000+" ч. "+(o.admin()?"Администратор обходит текущее ожидание. ":"")+"Подтвердите в течение 60 секунд: /t policies confirm");}
    @Override public List<String> onTabComplete(CommandSender s,Command c,String alias,String[] a){var out=new ArrayList<String>();boolean use=s.hasPermission("neverlandtownypolicies.use"),admin=s.hasPermission("neverlandtownypolicies.admin");if(a.length==1){if(use)out.addAll(List.of("menu","info","choose","confirm","history","help"));if(admin)out.addAll(List.of("reload","town","set","confirm"));}else if(a.length==2&&Set.of("town","set").contains(a[0])&&admin)TownyAPI.getInstance().getTowns().forEach(t->out.add(t.getName()));else if((a.length==2&&Set.of("info","choose").contains(a[0])&&use)||(a.length==3&&a[0].equals("set")&&admin))out.addAll(service.settings().groups().keySet());else if((a.length==3&&Set.of("info","choose").contains(a[0])&&use)||(a.length==4&&a[0].equals("set")&&admin)){var g=service.settings().groups().get(a[a.length-2]);if(g!=null)out.addAll(g.options().keySet());}String prefix=a.length==0?"":a[a.length-1].toLowerCase(Locale.ROOT);return out.stream().filter(x->x.toLowerCase(Locale.ROOT).startsWith(prefix)).distinct().sorted().toList();}
}
