package ru.neverland.townytreasury.model;
import java.util.*;
public record CityLedger(long balance,boolean enabled,Map<Budget,Long> funds,Map<Budget,Integer> shares,long revision,long started,String notified,Map<String,Week> weeks,Pending pending,List<String> history) {
    public record Pending(UUID id,long at,long amount,Budget category,String source,String reason){public Pending{Objects.requireNonNull(id);if(at<0||Money.positive(amount)==0)throw new IllegalArgumentException("Некорректное списание");Objects.requireNonNull(category);if(source==null||!source.matches("[a-z0-9_/-]{1,64}")||reason==null||reason.length()>512)throw new IllegalArgumentException("Некорректное назначение платежа");}}
    public CityLedger{Money.valid(balance);funds=Budget.amounts(funds);shares=Budget.shares(shares);if(revision<0||started<0)throw new IllegalArgumentException("Некорректная ревизия/дата");long total=funds.values().stream().reduce(0L,Money::add);if(total!=Math.max(0,balance))throw new IllegalArgumentException("Бюджеты не совпадают с учтённой казной");if(!enabled&&funds.get(Budget.FREE)!=total)throw new IllegalArgumentException("Отключённые бюджеты должны быть свободны");weeks=Map.copyOf(weeks);weeks.keySet().forEach(Week::validateKey);if(weeks.size()>13)throw new IllegalArgumentException("Слишком длинный архив");history=List.copyOf(history);if(history.size()>30)throw new IllegalArgumentException("Слишком длинная история");if(!notified.isEmpty())Week.validateKey(notified);}
    public static CityLedger initial(long balance,Map<Budget,Integer> shares,long now){return new CityLedger(balance,false,Map.of(Budget.FREE,Math.max(0,balance)),shares,0,now,"",Map.of(),null,List.of());}
    public CityLedger next(long balance,boolean enabled,Map<Budget,Long> funds,Map<Budget,Integer> shares,Map<String,Week> weeks,Pending pending,String change){var history=new ArrayList<>(this.history);if(change!=null){history.add(change);while(history.size()>30)history.remove(0);}return new CityLedger(balance,enabled,funds,shares,Math.addExact(revision,1),started,notified,trim(weeks),pending,history);}
    public CityLedger notified(String week){return new CityLedger(balance,enabled,funds,shares,revision,started,week,weeks,pending,history);}
    public CityLedger production(Map<String,Map<String,Long>> totals){var result=new HashMap<>(weeks);totals.forEach((week,values)->{Week.validateKey(week);result.put(week,result.getOrDefault(week,Week.empty()).produced(values));});return new CityLedger(balance,enabled,funds,shares,revision,started,notified,trim(result),pending,history);}
    private static Map<String,Week> trim(Map<String,Week> source){var map=new TreeMap<>(source);while(map.size()>13)map.pollFirstEntry();return Map.copyOf(map);}
}
