package ru.neverland.townytreasury.model;
import java.util.*;
public final class LedgerEngine {
    private LedgerEngine(){}
    public static Map<Budget,Long> distribute(long amount,Map<Budget,Integer> shares){Money.positive(amount);var out=new EnumMap<Budget,Long>(Budget.class);long used=0;for(var b:Budget.values()){long part=java.math.BigInteger.valueOf(amount).multiply(java.math.BigInteger.valueOf(shares.get(b))).divide(java.math.BigInteger.valueOf(100)).longValueExact();out.put(b,part);used=Money.add(used,part);}out.put(Budget.FREE,Money.add(out.get(Budget.FREE),amount-used));return out;}
    private static Map<Budget,Long> fund(CityLedger city,long nextBalance,long delta,Budget category,boolean refund){var out=new EnumMap<Budget,Long>(Budget.class);out.putAll(city.funds());long change=Math.max(0,nextBalance)-Math.max(0,city.balance());if(change>=0){var more=city.enabled()&&!refund?distribute(change,city.shares()):Budget.amounts(Map.of(city.enabled()?category:Budget.FREE,change));for(var b:Budget.values())out.put(b,Money.add(out.get(b),more.get(b)));}
        else {long left=-change;var order=new ArrayList<Budget>();order.add(category);if(category!=Budget.FREE)order.add(Budget.FREE);for(var b:Budget.values())if(!order.contains(b))order.add(b);for(var b:order){long take=Math.min(left,out.get(b));out.put(b,out.get(b)-take);left-=take;}}
        return out;
    }
    public static CityLedger observe(CityLedger city,long amount,boolean deposit,Budget category,String source,boolean refund,long at,UUID operation){Money.positive(amount);long delta=deposit?amount:-amount;long balance=Money.add(city.balance(),delta);var weeks=new HashMap<>(city.weeks());String week=Week.key(at);weeks.put(week,weeks.getOrDefault(week,Week.empty()).flow(amount,deposit,category,source,deposit&&refund));var pending=city.pending();if(!deposit&&pending!=null&&pending.id().equals(operation)){if(pending.amount()!=amount||pending.category()!=category)throw new IllegalStateException("Сумма наблюдения не совпадает со счётом");pending=null;}
        return city.next(balance,city.enabled(),fund(city,balance,delta,category,deposit&&refund),city.shares(),weeks,pending,null);
    }
    public static CityLedger reconcile(CityLedger city,long actual,long now){if(city.pending()!=null||actual==city.balance())return city;long delta=Money.add(actual,-city.balance());var weeks=new HashMap<>(city.weeks());String week=Week.key(now);weeks.put(week,weeks.getOrDefault(week,Week.empty()).adjustment(delta));return city.next(actual,city.enabled(),fund(city,actual,delta,Budget.FREE,true),city.shares(),weeks,null,null);}
    public static boolean canSpend(CityLedger city,Budget category,long amount){return amount>=0&&city.pending()==null&&city.balance()>=amount&&(!city.enabled()||city.funds().get(category)>=amount);}
    public static CityLedger prepare(CityLedger city,CityLedger.Pending pending){if(!canSpend(city,pending.category(),pending.amount()))throw new IllegalArgumentException("В статье бюджета недостаточно средств или требуется сверка");return city.next(city.balance(),city.enabled(),city.funds(),city.shares(),city.weeks(),pending,null);}
    public static CityLedger cancel(CityLedger city,UUID id){if(city.pending()==null||!city.pending().id().equals(id))throw new IllegalArgumentException("Счёт не совпадает");return city.next(city.balance(),city.enabled(),city.funds(),city.shares(),city.weeks(),null,null);}
    public static CityLedger mode(CityLedger city,boolean enabled,String actor){editable(city);if(city.enabled()==enabled)throw new IllegalArgumentException("Этот режим уже выбран");var funds=enabled?distribute(Math.max(0,city.balance()),city.shares()):Budget.amounts(Map.of(Budget.FREE,Math.max(0,city.balance())));return city.next(city.balance(),enabled,funds,city.shares(),city.weeks(),null,actor+": "+(enabled?"включил распределение бюджета":"освободил бюджеты"));}
    public static CityLedger transfer(CityLedger city,Budget from,Budget to,long amount,String actor){editable(city);if(!city.enabled())throw new IllegalArgumentException("Сначала включите бюджеты");if(from==to||amount<=0||city.funds().get(from)<amount)throw new IllegalArgumentException("Проверьте статьи и доступную сумму");var funds=new EnumMap<Budget,Long>(Budget.class);funds.putAll(city.funds());funds.put(from,funds.get(from)-amount);funds.put(to,Money.add(funds.get(to),amount));return city.next(city.balance(),true,funds,city.shares(),city.weeks(),null,actor+": "+from.title()+" → "+to.title()+" "+Money.format(amount));}
    public static CityLedger shares(CityLedger city,Map<Budget,Integer> shares,String actor){editable(city);return city.next(city.balance(),city.enabled(),city.funds(),Budget.shares(shares),city.weeks(),null,actor+": изменил доли новых поступлений");}
    private static void editable(CityLedger city){if(city.pending()!=null)throw new IllegalArgumentException("Есть незавершённое списание: нужна сверка администратора");}
}
