package ru.neverland.townytaxes.command;

import org.bukkit.command.*;import org.jetbrains.annotations.NotNull;import org.jetbrains.annotations.Nullable;
import ru.neverland.townytaxes.NeverLandTownyTaxes;import ru.neverland.townytaxes.integration.TownyHook;import ru.neverland.townytaxes.model.*;import ru.neverland.townytaxes.service.*;import ru.neverland.townytaxes.util.ColorUtil;
import java.util.*;

public final class AdminCommand implements CommandExecutor,TabCompleter {
    private final NeverLandTownyTaxes plugin;private final TownyHook towny;private final FiscalService fiscal;private final MessageService messages;public AdminCommand(NeverLandTownyTaxes p,TownyHook t,FiscalService f,MessageService m){plugin=p;towny=t;fiscal=f;messages=m;}
    @Override public boolean onCommand(@NotNull CommandSender s,@NotNull Command c,@NotNull String l,@NotNull String[] a){if(!s.hasPermission("townytaxes.admin")){messages.send(s,"no-permission");return true;}if(a.length==0){messages.list("admin-help").forEach(s::sendMessage);return true;}switch(a[0].toLowerCase(Locale.ROOT)){case"reload"->{plugin.reloadPlugin();messages.send(s,"reloaded");}case"collect"->{fiscal.collectNow();s.sendMessage(ColorUtil.color("&#63E6BEСбор налогов запущен."));}case"bank"->messages.send(s,"server-bank",Map.of("amount",fiscal.format(fiscal.serverReserve())));case"ledger"->ledger(s,a);case"policy"->policy(s,a);case"sanction"->sanction(s,a);case"agreement"->agreement(s,a);default->messages.list("admin-help").forEach(s::sendMessage);}return true;}
    private void policy(CommandSender s,String[]a){if(a.length>=3&&a[1].equalsIgnoreCase("remove")){if(fiscal.removePolicy(a[2]))messages.send(s,"policy-removed",Map.of("id",a[2]));else messages.send(s,"policy-not-found",Map.of("id",a[2]));return;}if(a.length<8||!a[1].equalsIgnoreCase("create")){messages.list("admin-help").forEach(s::sendMessage);return;}Domain.Scope scope=Domain.Scope.parse(a[2]),destScope=Domain.Scope.parse(a[6]);Domain.TaxType type=Domain.TaxType.parse(a[4]);if(scope==null||destScope==null){messages.send(s,"invalid-scope");return;}if(type==null){messages.send(s,"invalid-tax-type");return;}TownyHook.Party target=towny.resolve(scope,a[3]),dest=towny.resolve(destScope,a[7]);if(target==null||dest==null){messages.send(s,"target-not-found",Map.of("target",target==null?a[3]:a[7]));return;}try{double value=Double.parseDouble(a[5].replace(',','.'));if(!fiscal.validTaxValue(type,value))throw new NumberFormatException();long minutes=a.length>8?Long.parseLong(a[8]):plugin.getConfig().getLong("taxes.default-interval-minutes",1440);TaxPolicy p=fiscal.createPolicy(target,type,value,dest,fiscal.intervalMillis(minutes),s.getName());messages.send(s,"policy-created",Map.of("id",p.shortId()));}catch(NumberFormatException e){messages.send(s,"invalid-number");}}
    private void sanction(CommandSender s,String[]a){if(a.length>=3&&a[1].equalsIgnoreCase("remove")){if(fiscal.removeSanction(a[2]))messages.send(s,"sanction-removed",Map.of("id",a[2]));else messages.send(s,"sanction-not-found",Map.of("id",a[2]));return;}if(a.length<8||!a[1].equalsIgnoreCase("add")){messages.list("admin-help").forEach(s::sendMessage);return;}Domain.Scope scope=Domain.Scope.parse(a[2]);Domain.SanctionEffect effect=Domain.SanctionEffect.parse(a[4]);TownyHook.Party target=towny.resolve(scope,a[3]),issuer=towny.resolve(Domain.Scope.GLOBAL,"server");if(scope==null||target==null){messages.send(s,"target-not-found",Map.of("target",a[3]));return;}if(effect==null){messages.send(s,"invalid-effect");return;}try{double value=Double.parseDouble(a[5].replace(',','.'));long hours=Long.parseLong(a[6]);String reason=String.join(" ",Arrays.copyOfRange(a,7,a.length));Sanction v=fiscal.createSanction(target,issuer,effect,value,hours<=0?0:System.currentTimeMillis()+hours*3_600_000L,reason,s.getName());messages.send(s,"sanction-created",Map.of("target",target.name(),"id",v.shortId()));}catch(NumberFormatException e){messages.send(s,"invalid-number");}}
    private void agreement(CommandSender s,String[]a){if(a.length<9||!a[1].equalsIgnoreCase("add")){messages.list("admin-help").forEach(s::sendMessage);return;}Domain.Scope sa=Domain.Scope.parse(a[2]),sb=Domain.Scope.parse(a[4]);Domain.AgreementType type=Domain.AgreementType.parse(a[6]);TownyHook.Party first=towny.resolve(sa,a[3]),second=towny.resolve(sb,a[5]);if(first==null||second==null){messages.send(s,"target-not-found",Map.of("target",first==null?a[3]:a[5]));return;}if(type==null){messages.send(s,"invalid-agreement");return;}try{double value=Double.parseDouble(a[7].replace(',','.'));long hours=Long.parseLong(a[8]);Agreement v=fiscal.createAgreement(first,second,type,value,hours<=0?0:System.currentTimeMillis()+hours*3_600_000L,s.getName(),true);messages.send(s,"agreement-accepted",Map.of("id",v.shortId()));}catch(NumberFormatException e){messages.send(s,"invalid-number");}}
    private void ledger(CommandSender s,String[]a){int page=1;try{if(a.length>1)page=Math.max(1,Integer.parseInt(a[1]));}catch(Exception ignored){}List<LedgerEntry> all=fiscal.repository().ledger();int from=Math.max(0,all.size()-page*10),to=Math.min(all.size(),from+10);s.sendMessage(ColorUtil.color("&#FFD45A&lЖурнал казначейства — страница "+page));for(int i=to-1;i>=from;i--){LedgerEntry e=all.get(i);s.sendMessage(ColorUtil.color("&8- &f"+e.action()+" &7"+e.subjectName()+" &e"+fiscal.format(e.amount())+" &8"+e.details()));}}
    @Override public @Nullable List<String> onTabComplete(@NotNull CommandSender s,@NotNull Command c,@NotNull String l,@NotNull String[]a){if(a.length==1)return filter(List.of("policy","sanction","agreement","bank","ledger","collect","reload"),a[0]);if(a.length==2&&List.of("policy","sanction","agreement").contains(a[0].toLowerCase(Locale.ROOT)))return filter(List.of("create","add","remove"),a[1]);return List.of();}private List<String>filter(List<String>v,String p){String q=p.toLowerCase(Locale.ROOT);return v.stream().filter(x->x.startsWith(q)).toList();}
}
