package ru.neverland.townytaxes.command;

import com.palmergames.bukkit.towny.object.Nation;import org.bukkit.command.*;import org.bukkit.entity.Player;import org.jetbrains.annotations.NotNull;
import ru.neverland.townytaxes.integration.TownyHook;import ru.neverland.townytaxes.model.*;import ru.neverland.townytaxes.service.*;import ru.neverland.townytaxes.util.ColorUtil;
import java.util.*;

public final class NationEconomyCommand implements CommandExecutor {
    public enum View{TAXES,SANCTIONS,AGREEMENTS}private final View view;private final TownyHook towny;private final FiscalService fiscal;private final MessageService messages;
    public NationEconomyCommand(View v,TownyHook t,FiscalService f,MessageService m){view=v;towny=t;fiscal=f;messages=m;}
    @Override public boolean onCommand(@NotNull CommandSender sender,@NotNull Command command,@NotNull String label,@NotNull String[]a){if(!(sender instanceof Player p)){messages.send(sender,"players-only");return true;}Nation n=towny.nation(p);if(n==null){messages.send(p,"no-nation");return true;}if(a.length==0){list(p,n);help(p);return true;}if(!p.hasPermission("townytaxes.nation")||!towny.isNationManager(p,n)){messages.send(p,"only-nation-manager");return true;}switch(view){case TAXES->taxes(p,n,a);case SANCTIONS->sanctions(p,n,a);case AGREEMENTS->agreements(p,n,a);}return true;}
    private void taxes(Player p,Nation n,String[]a){if(a[0].equalsIgnoreCase("create")&&a.length>=3){Domain.TaxType type=Domain.TaxType.parse(a[1]);if(type==null){messages.send(p,"invalid-tax-type");return;}try{double value=Double.parseDouble(a[2].replace(',','.'));if(!fiscal.validTaxValue(type,value))throw new NumberFormatException();long minutes=a.length>3?Long.parseLong(a[3]):1440;TownyHook.Party party=new TownyHook.Party(Domain.Scope.NATION,n.getUUID(),n.getName(),n.getAccount());TaxPolicy v=fiscal.createPolicy(party,type,value,party,fiscal.intervalMillis(minutes),p.getName());messages.send(p,"policy-created",Map.of("id",v.shortId()));}catch(NumberFormatException e){messages.send(p,"invalid-number");}}else if(a[0].equalsIgnoreCase("remove")&&a.length>1){TaxPolicy v=fiscal.repository().policy(a[1]);if(v==null||v.scope()!=Domain.Scope.NATION||!v.targetId().equals(n.getUUID()))messages.send(p,"policy-not-found",Map.of("id",a[1]));else{fiscal.removePolicy(a[1]);messages.send(p,"policy-removed",Map.of("id",v.shortId()));}}else help(p);}
    private void sanctions(Player p,Nation n,String[]a){if(a[0].equalsIgnoreCase("impose")&&a.length>=6){Domain.Scope scope=Domain.Scope.parse(a[1]);if(scope!=Domain.Scope.TOWN&&scope!=Domain.Scope.NATION){messages.send(p,"invalid-scope");return;}TownyHook.Party target=towny.resolve(scope,a[2]);Domain.SanctionEffect effect=Domain.SanctionEffect.parse(a[3]);if(target==null){messages.send(p,"target-not-found",Map.of("target",a[2]));return;}if(effect==null){messages.send(p,"invalid-effect");return;}try{double value=Double.parseDouble(a[4].replace(',','.'));long hours=Long.parseLong(a[5]);String reason=a.length>6?String.join(" ",Arrays.copyOfRange(a,6,a.length)):"Без причины";TownyHook.Party issuer=new TownyHook.Party(Domain.Scope.NATION,n.getUUID(),n.getName(),n.getAccount());Sanction v=fiscal.createSanction(target,issuer,effect,value,hours<=0?0:System.currentTimeMillis()+hours*3_600_000L,reason,p.getName());messages.send(p,"sanction-created",Map.of("target",target.name(),"id",v.shortId()));}catch(NumberFormatException e){messages.send(p,"invalid-number");}}else if(a[0].equalsIgnoreCase("remove")&&a.length>1){Sanction v=fiscal.repository().sanction(a[1]);if(v==null||!v.issuerId().equals(n.getUUID()))messages.send(p,"sanction-not-found",Map.of("id",a[1]));else{fiscal.removeSanction(a[1]);messages.send(p,"sanction-removed",Map.of("id",v.shortId()));}}else help(p);}
    private void agreements(Player p,Nation n,String[]a){if(a[0].equalsIgnoreCase("propose")&&a.length>=4){Nation target=towny.nation(a[1]);Domain.AgreementType type=Domain.AgreementType.parse(a[2]);if(target==null){messages.send(p,"target-not-found",Map.of("target",a[1]));return;}if(type==null){messages.send(p,"invalid-agreement");return;}try{double value=Double.parseDouble(a[3].replace(',','.'));long hours=a.length>4?Long.parseLong(a[4]):168;TownyHook.Party first=new TownyHook.Party(Domain.Scope.NATION,n.getUUID(),n.getName(),n.getAccount()),second=new TownyHook.Party(Domain.Scope.NATION,target.getUUID(),target.getName(),target.getAccount());Agreement v=fiscal.createAgreement(first,second,type,value,hours<=0?0:System.currentTimeMillis()+hours*3_600_000L,p.getName(),false);messages.send(p,"agreement-created",Map.of("id",v.shortId()));}catch(NumberFormatException e){messages.send(p,"invalid-number");}}else if(a.length>1&&Set.of("accept","reject","cancel").contains(a[0].toLowerCase(Locale.ROOT))){Agreement v=fiscal.repository().agreement(a[1]);if(v==null||!v.party(Domain.Scope.NATION,n.getUUID())){messages.send(p,"agreement-not-found",Map.of("id",a[1]));return;}Domain.AgreementStatus next=switch(a[0].toLowerCase(Locale.ROOT)){case"accept"->Domain.AgreementStatus.ACTIVE;case"reject"->Domain.AgreementStatus.REJECTED;default->Domain.AgreementStatus.CANCELLED;};if(next==Domain.AgreementStatus.ACTIVE&&(!v.secondId().equals(n.getUUID())||v.status()!=Domain.AgreementStatus.PENDING)){messages.send(p,"not-agreement-party");return;}fiscal.setAgreement(a[1],next);messages.send(p,next==Domain.AgreementStatus.ACTIVE?"agreement-accepted":next==Domain.AgreementStatus.REJECTED?"agreement-rejected":"agreement-removed",Map.of("id",v.shortId()));}else help(p);}
    private void list(Player p,Nation n){p.sendMessage(ColorUtil.color("&#FFD45A&lГосударственная экономика: "+n.getName()));switch(view){case TAXES->fiscal.repository().policies().stream().filter(v->v.scope()==Domain.Scope.NATION&&v.targetId().equals(n.getUUID())).forEach(v->p.sendMessage(ColorUtil.color("&8- &f"+v.shortId()+" &7"+v.type()+" &e"+v.value())));case SANCTIONS->fiscal.repository().sanctions().stream().filter(v->v.targetId().equals(n.getUUID())||v.issuerId().equals(n.getUUID())).forEach(v->p.sendMessage(ColorUtil.color("&8- &f"+v.shortId()+" &7"+v.issuerName()+" → "+v.targetName()+" &e"+v.effect())));case AGREEMENTS->fiscal.repository().agreements().stream().filter(v->v.party(Domain.Scope.NATION,n.getUUID())).forEach(v->p.sendMessage(ColorUtil.color("&8- &f"+v.shortId()+" &7"+v.firstName()+" ↔ "+v.secondName()+" &e"+v.status())));}}
    private void help(Player p){messages.list("help-nation-"+view.name().toLowerCase(Locale.ROOT)).forEach(p::sendMessage);}
}
