package ru.neverland.townytaxes.command;

import com.palmergames.bukkit.towny.object.Town;
import org.bukkit.command.*;import org.bukkit.entity.Player;import org.jetbrains.annotations.NotNull;
import ru.neverland.townytaxes.integration.TownyHook;import ru.neverland.townytaxes.model.*;import ru.neverland.townytaxes.service.*;import ru.neverland.townytaxes.util.ColorUtil;
import java.util.Map;

public final class TownSanctionsCommand implements CommandExecutor {
    private final TownyHook towny;private final FiscalService fiscal;private final MessageService messages;public TownSanctionsCommand(TownyHook t,FiscalService f,MessageService m){towny=t;fiscal=f;messages=m;}
    @Override public boolean onCommand(@NotNull CommandSender sender,@NotNull Command command,@NotNull String label,@NotNull String[] a){if(!(sender instanceof Player p)){messages.send(sender,"players-only");return true;}Town own=towny.town(p);if(own==null){messages.send(p,"no-town");return true;}if(a.length==0){list(p,own);messages.list("help-sanctions").forEach(p::sendMessage);return true;}if(!p.hasPermission("townytaxes.sanctions")||!towny.isTownManager(p,own)){messages.send(p,"only-town-manager");return true;}if(a[0].equalsIgnoreCase("impose"))impose(p,own,a);else if(a[0].equalsIgnoreCase("remove"))remove(p,own,a);else messages.list("help-sanctions").forEach(p::sendMessage);return true;}
    private void list(Player p,Town own){p.sendMessage(ColorUtil.color("&#FFA94D&lДействующие санкции:"));long now=System.currentTimeMillis();boolean any=false;for(Sanction s:fiscal.repository().sanctions())if(s.active(now)&&(s.targetId().equals(own.getUUID())||s.issuerId().equals(own.getUUID()))){any=true;p.sendMessage(ColorUtil.color("&8- &f"+s.shortId()+" &7"+s.issuerName()+" → "+s.targetName()+" &e"+s.effect().name().toLowerCase()+" &8("+s.reason()+")"));}if(!any)p.sendMessage(ColorUtil.color("&7Санкций нет."));}
    private void impose(Player p,Town issuer,String[] a){if(a.length<5){messages.list("help-sanctions").forEach(p::sendMessage);return;}Town target=towny.town(a[1]);if(target==null){messages.send(p,"target-not-found",Map.of("target",a[1]));return;}Domain.SanctionEffect effect=Domain.SanctionEffect.parse(a[2]);if(effect==null){messages.send(p,"invalid-effect");return;}try{double value=Double.parseDouble(a[3].replace(',','.'));long hours=Long.parseLong(a[4]);String reason=a.length>5?String.join(" ",java.util.Arrays.copyOfRange(a,5,a.length)):"Без причины";TownyHook.Party targetParty=new TownyHook.Party(Domain.Scope.TOWN,target.getUUID(),target.getName(),target.getAccount()),issuerParty=new TownyHook.Party(Domain.Scope.TOWN,issuer.getUUID(),issuer.getName(),issuer.getAccount());Sanction s=fiscal.createSanction(targetParty,issuerParty,effect,value,hours<=0?0:System.currentTimeMillis()+hours*3_600_000L,reason,p.getName());messages.send(p,"sanction-created",Map.of("target",target.getName(),"id",s.shortId()));}catch(NumberFormatException e){messages.send(p,"invalid-number");}}
    private void remove(Player p,Town issuer,String[] a){if(a.length<2)return;Sanction s=fiscal.repository().sanction(a[1]);if(s==null||!s.issuerId().equals(issuer.getUUID())){messages.send(p,"sanction-not-found",Map.of("id",a[1]));return;}fiscal.removeSanction(a[1]);messages.send(p,"sanction-removed",Map.of("id",s.shortId()));}
}
