package ru.neverland.townytaxes.command;

import com.palmergames.bukkit.towny.object.Town;import org.bukkit.command.*;import org.bukkit.entity.Player;import org.jetbrains.annotations.NotNull;
import ru.neverland.townytaxes.integration.TownyHook;import ru.neverland.townytaxes.model.*;import ru.neverland.townytaxes.service.*;import ru.neverland.townytaxes.util.ColorUtil;
import java.util.Map;

public final class TownAgreementsCommand implements CommandExecutor {
    private final TownyHook towny;private final FiscalService fiscal;private final MessageService messages;public TownAgreementsCommand(TownyHook t,FiscalService f,MessageService m){towny=t;fiscal=f;messages=m;}
    @Override public boolean onCommand(@NotNull CommandSender sender,@NotNull Command command,@NotNull String label,@NotNull String[] a){if(!(sender instanceof Player p)){messages.send(sender,"players-only");return true;}Town own=towny.town(p);if(own==null){messages.send(p,"no-town");return true;}if(a.length==0){list(p,own);messages.list("help-agreements").forEach(p::sendMessage);return true;}if(!p.hasPermission("townytaxes.agreements")||!towny.isTownManager(p,own)){messages.send(p,"only-town-manager");return true;}switch(a[0].toLowerCase(java.util.Locale.ROOT)){case"propose"->propose(p,own,a);case"accept"->status(p,own,a,Domain.AgreementStatus.ACTIVE,"agreement-accepted");case"reject"->status(p,own,a,Domain.AgreementStatus.REJECTED,"agreement-rejected");case"cancel"->status(p,own,a,Domain.AgreementStatus.CANCELLED,"agreement-removed");default->messages.list("help-agreements").forEach(p::sendMessage);}return true;}
    private void list(Player p,Town own){p.sendMessage(ColorUtil.color("&#63E6BE&lЭкономические соглашения:"));boolean any=false;for(Agreement v:fiscal.repository().agreements())if(v.party(Domain.Scope.TOWN,own.getUUID())){any=true;p.sendMessage(ColorUtil.color("&8- &f"+v.shortId()+" &7"+v.firstName()+" ↔ "+v.secondName()+" &e"+v.type().name().toLowerCase()+" &8["+v.status().name()+"]"));}if(!any)p.sendMessage(ColorUtil.color("&7Соглашений нет."));}
    private void propose(Player p,Town own,String[] a){if(a.length<4){messages.list("help-agreements").forEach(p::sendMessage);return;}Town target=towny.town(a[1]);if(target==null){messages.send(p,"target-not-found",Map.of("target",a[1]));return;}Domain.AgreementType type=Domain.AgreementType.parse(a[2]);if(type==null){messages.send(p,"invalid-agreement");return;}try{double value=Double.parseDouble(a[3].replace(',','.'));long hours=a.length>4?Long.parseLong(a[4]):168;TownyHook.Party first=new TownyHook.Party(Domain.Scope.TOWN,own.getUUID(),own.getName(),own.getAccount()),second=new TownyHook.Party(Domain.Scope.TOWN,target.getUUID(),target.getName(),target.getAccount());Agreement agreement=fiscal.createAgreement(first,second,type,value,hours<=0?0:System.currentTimeMillis()+hours*3_600_000L,p.getName(),false);messages.send(p,"agreement-created",Map.of("id",agreement.shortId()));}catch(NumberFormatException e){messages.send(p,"invalid-number");}}
    private void status(Player p,Town own,String[] a,Domain.AgreementStatus next,String message){if(a.length<2)return;Agreement v=fiscal.repository().agreement(a[1]);if(v==null||!v.party(Domain.Scope.TOWN,own.getUUID())){messages.send(p,"agreement-not-found",Map.of("id",a[1]));return;}if(next==Domain.AgreementStatus.ACTIVE&&(!v.secondId().equals(own.getUUID())||v.status()!=Domain.AgreementStatus.PENDING)){messages.send(p,"not-agreement-party");return;}fiscal.setAgreement(a[1],next);messages.send(p,message,Map.of("id",v.shortId()));}
}
