package ru.neverland.archaeology.service;

import org.bukkit.configuration.ConfigurationSection;
import org.bukkit.configuration.file.YamlConfiguration;
import org.bukkit.plugin.java.JavaPlugin;
import ru.neverland.archaeology.model.DigSite;
import ru.neverland.archaeology.model.PlayerJournal;
import ru.neverland.archaeology.model.TownMuseumData;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.UUID;

public final class ArchaeologyRepository {
    private final JavaPlugin plugin; private final File file; private final Map<UUID, TownMuseumData> towns = new LinkedHashMap<>(); private final Map<UUID, PlayerJournal> players = new LinkedHashMap<>(); private final Map<UUID, DigSite> sites = new LinkedHashMap<>(); private final Set<String> acceptedSerials = new LinkedHashSet<>(); private final Map<String, Integer> acceptedBatches = new LinkedHashMap<>(); private boolean dirty;
    public ArchaeologyRepository(JavaPlugin plugin) { this.plugin = plugin; this.file = new File(plugin.getDataFolder(), "data.yml"); }
    public void load() { towns.clear(); players.clear(); sites.clear(); acceptedSerials.clear(); acceptedBatches.clear(); YamlConfiguration yaml = YamlConfiguration.loadConfiguration(file); loadTowns(yaml.getConfigurationSection("towns")); loadPlayers(yaml.getConfigurationSection("players")); loadSites(yaml.getMapList("sites")); acceptedSerials.addAll(yaml.getStringList("accepted-serials")); loadIntMap(yaml.getConfigurationSection("accepted-batches"), acceptedBatches); dirty = false; }
    private void loadTowns(ConfigurationSection root) { if (root == null) return; for (String rawId : root.getKeys(false)) try { UUID id = UUID.fromString(rawId); ConfigurationSection section = root.getConfigurationSection(rawId); if (section == null) continue; TownMuseumData data = new TownMuseumData(id, section.getString("name", rawId)); data.points(section.getInt("points")); loadIntMap(section.getConfigurationSection("available"), data.available()); loadIntMap(section.getConfigurationSection("donated"), data.donated()); data.completedCollections().addAll(section.getStringList("completed-collections")); ConfigurationSection contributors = section.getConfigurationSection("contributors"); if (contributors != null) for (String player : contributors.getKeys(false)) data.contributors().put(UUID.fromString(player), contributors.getInt(player)); towns.put(id, data); } catch (RuntimeException exception) { plugin.getLogger().warning("Пропущены повреждённые данные музея " + rawId + ": " + exception.getMessage()); } }
    private void loadPlayers(ConfigurationSection root) { if (root == null) return; for (String rawId : root.getKeys(false)) try { UUID id = UUID.fromString(rawId); ConfigurationSection section = root.getConfigurationSection(rawId); if (section == null) continue; PlayerJournal journal = new PlayerJournal(id, section.getString("name", rawId)); journal.totalFound(section.getInt("total-found")); loadIntMap(section.getConfigurationSection("discoveries"), journal.discoveries()); journal.serials().addAll(section.getStringList("serials")); players.put(id, journal); } catch (RuntimeException exception) { plugin.getLogger().warning("Пропущен повреждённый журнал " + rawId); } }
    private void loadSites(List<Map<?, ?>> list) { for (Map<?, ?> map : list) try { UUID id = UUID.fromString(String.valueOf(map.get("id"))); DigSite site = new DigSite(id, String.valueOf(map.get("type")), UUID.fromString(String.valueOf(map.get("world-id"))), String.valueOf(map.get("world-name")), number(map.get("x")), number(map.get("y")), number(map.get("z")), longNumber(map.get("created-at"))); Object rawBlocks = map.get("blocks"); if (rawBlocks instanceof List<?> blocks) for (Object block : blocks) site.blocks().add(String.valueOf(block)); Object completed = map.get("completed"); site.completed(completed != null && Boolean.parseBoolean(String.valueOf(completed))); sites.put(id, site); } catch (RuntimeException exception) { plugin.getLogger().warning("Пропущен повреждённый участок раскопок: " + exception.getMessage()); } }
    public synchronized void save() { if (!dirty && file.exists()) return; YamlConfiguration yaml = new YamlConfiguration(); for (TownMuseumData data : towns.values()) { String path = "towns." + data.townId(); yaml.set(path + ".name", data.townName()); yaml.set(path + ".points", data.points()); yaml.set(path + ".available", data.available()); yaml.set(path + ".donated", data.donated()); yaml.set(path + ".completed-collections", new ArrayList<>(data.completedCollections())); Map<String, Integer> contributors = new LinkedHashMap<>(); data.contributors().forEach((id, amount) -> contributors.put(id.toString(), amount)); yaml.set(path + ".contributors", contributors); } for (PlayerJournal journal : players.values()) { String path = "players." + journal.playerId(); yaml.set(path + ".name", journal.playerName()); yaml.set(path + ".total-found", journal.totalFound()); yaml.set(path + ".discoveries", journal.discoveries()); yaml.set(path + ".serials", new ArrayList<>(journal.serials())); } List<Map<String, Object>> siteList = new ArrayList<>(); for (DigSite site : sites.values()) { Map<String, Object> map = new LinkedHashMap<>(); map.put("id", site.id().toString()); map.put("type", site.type()); map.put("world-id", site.worldId().toString()); map.put("world-name", site.worldName()); map.put("x", site.x()); map.put("y", site.y()); map.put("z", site.z()); map.put("created-at", site.createdAt()); map.put("completed", site.completed()); map.put("blocks", new ArrayList<>(site.blocks())); siteList.add(map); } yaml.set("sites", siteList); yaml.set("accepted-serials", new ArrayList<>(acceptedSerials)); yaml.set("accepted-batches", acceptedBatches); try { yaml.save(file); dirty = false; } catch (IOException exception) { plugin.getLogger().severe("Не удалось сохранить data.yml: " + exception.getMessage()); } }
    public TownMuseumData museum(UUID townId, String name) { TownMuseumData data = towns.computeIfAbsent(townId, id -> { dirty = true; return new TownMuseumData(id, name); }); data.townName(name); return data; } public TownMuseumData museum(UUID townId) { return towns.get(townId); }
    public PlayerJournal journal(UUID playerId, String name) { PlayerJournal journal = players.computeIfAbsent(playerId, id -> { dirty = true; return new PlayerJournal(id, name); }); journal.playerName(name); return journal; } public PlayerJournal journal(UUID playerId) { return players.get(playerId); }
    public Map<UUID, DigSite> sites() { return sites; } public void addSite(DigSite site) { sites.put(site.id(), site); dirty = true; } public void removeSite(UUID id) { sites.remove(id); dirty = true; }
    public boolean accepted(String serial) { return acceptedCount(serial) > 0; } public void accept(String serial) { acceptedSerials.add(serial); dirty = true; }
    public int acceptedCount(String serial) { return acceptedSerials.contains(serial) ? Integer.MAX_VALUE : acceptedBatches.getOrDefault(serial, 0); }
    public void accept(String serial, int amount) { if (amount <= 0) return; acceptedBatches.merge(serial, amount, Integer::sum); dirty = true; }
    public void dirty() { dirty = true; } public boolean dirtyState() { return dirty; }
    private void loadIntMap(ConfigurationSection section, Map<String, Integer> target) { if (section != null) for (String key : section.getKeys(false)) target.put(key, section.getInt(key)); }
    private int number(Object value) { return value instanceof Number number ? number.intValue() : Integer.parseInt(String.valueOf(value)); } private long longNumber(Object value) { return value instanceof Number number ? number.longValue() : Long.parseLong(String.valueOf(value)); }
}
