package ru.neverland.townypolicies.gui;
import org.bukkit.*;
import org.bukkit.entity.Player;
import org.bukkit.event.*;
import org.bukkit.event.inventory.*;
import org.bukkit.inventory.*;
import java.util.*;
import ru.neverland.townypolicies.service.*;
import static ru.neverland.townypolicies.service.Ui.*;
public final class PoliciesMenu implements Listener {
    private final org.bukkit.plugin.Plugin plugin;private final PoliciesService service;
    private static final class View implements InventoryHolder{final UUID town;final Map<Integer,Runnable> actions=new HashMap<>();Inventory inventory;View(UUID town){this.town=town;}public Inventory getInventory(){return inventory;}}
    public PoliciesMenu(org.bukkit.plugin.Plugin plugin,PoliciesService service){this.plugin=plugin;this.service=service;}
    private boolean access(Player p,UUID town){var own=service.town(p);return p.hasPermission("neverlandtownypolicies.admin")||p.hasPermission("neverlandtownypolicies.use")&&own!=null&&own.getUUID().equals(town);}
    public void open(Player p,UUID town,String group,String mode){if(!access(p,town)){tell(p,"Нет доступа к этому городу.");return;}var view=service.policies(town).orElse(null);if(view==null){tell(p,"Ожидаются данные города.");return;}var settings=service.settings();var v=new View(town);v.inventory=Bukkit.createInventory(v,54,color("&6Городские политики"));var state=view.state();
        if(group==null){int slot=10;for(var g:settings.groups().values()){var selected=g.options().get(state.mode(g));button(v,slot++,icon(g.icon()),"&e"+g.name(),List.of("Режим: "+(selected==null?"Отсутствует в настройках":selected.name()),view.status().get(g.id()),"Смена через: "+waitTime(state.next(g.id())),"Нажмите: сравнить три режима."),()->open(p,town,g.id(),null));}button(v,31,Material.WRITABLE_BOOK,"&eИстория указов",List.of("Последние 30 изменений."),()->open(p,town,"history",null));}
        else if(group.equals("history")){int slot=0;var changes=new ArrayList<>(state.history());Collections.reverse(changes);for(var h:changes){var g=settings.groups().get(h.group());var before=g.options().get(h.before());var after=g.options().get(h.after());button(v,slot++,Material.PAPER,"&e"+g.name(),List.of((before==null?"Прежний режим":before.name())+" → "+(after==null?"Удалённый режим":after.name()),"Автор: "+h.actorName(),java.time.format.DateTimeFormatter.ofPattern("dd.MM.yyyy HH:mm").withZone(java.time.ZoneId.systemDefault()).format(java.time.Instant.ofEpochMilli(h.at()))),null);}}
        else{var g=settings.groups().get(group);if(g==null){tell(p,"Политика не найдена.");return;}if(mode==null){int slot=19;for(var option:g.options().values()){button(v,slot,icon(option.icon()),"&e"+option.name(),lore(town,g,option,state.mode(g).equals(option.id())),()->open(p,town,group,option.id()));slot+=3;}}
            else{var option=g.options().get(mode);if(option==null){tell(p,"Режим не найден.");return;}button(v,13,icon(option.icon()),"&e"+option.name(),lore(town,g,option,state.mode(g).equals(mode)),null);if(!state.mode(g).equals(mode))button(v,31,Material.LIME_DYE,"&aПодтвердить указ",List.of("Изменится только политика: "+g.name(),"Смена бесплатна; издержки режима действуют постоянно.","Следующая смена этой политики через "+settings.cooldownMillis()/3600000+" ч.","Текущее ожидание: "+waitTime(state.next(group))),()->{try{service.choose(p,town,group,mode,state.revision(),settings,false);tell(p,"Указ принят: "+g.name()+" — "+option.name());open(p,town,group,null);}catch(Exception e){tell(p,"&c"+e.getMessage());}});button(v,40,Material.COMPARATOR,"&eСравнить режимы",List.of(),()->open(p,town,group,null));}}
        if(group!=null)button(v,45,Material.ARROW,"&aВсе политики",List.of(),()->open(p,town,null,null));if(Bukkit.getPluginManager().isPluginEnabled("NeverLandTownyGovernance"))button(v,48,Material.BOOK,"&eЗаконы и совет",List.of("Открыть существующее управление городом."),()->p.performCommand("town governance"));button(v,49,Material.SPYGLASS,"&aОбновить",List.of(),()->open(p,town,group,mode));if(Bukkit.getPluginManager().isPluginEnabled("NeverLandTownyResources"))button(v,53,Material.CHEST,"&eГородские ресурсы",List.of(),()->p.performCommand("town resources"));p.openInventory(v.inventory);
    }
    private List<String> lore(UUID town,ru.neverland.townypolicies.model.PolicyGroup g,ru.neverland.townypolicies.model.PolicyOption p,boolean selected){var lines=new ArrayList<String>();for(String text:p.advantages())lines.add("&a+ "+text);for(String text:p.disadvantages())lines.add("&c− "+text);if(!p.effects().isEmpty()){lines.add("Фактические эффекты:");p.effects().forEach((key,value)->lines.add(EffectLabels.value(key,value)));}String reason=service.unavailable(town,g,p);if(!reason.isEmpty())lines.add("&eПриостановлено: "+reason);if(selected)lines.add("&aВыбранный режим");return lines;}
    private String waitTime(long until){long seconds=Math.max(0,(until-System.currentTimeMillis()+999)/1000);return seconds==0?"доступна сейчас":seconds/3600+" ч. "+seconds%3600/60+" мин. "+seconds%60+" сек.";}
    private void button(View v,int slot,Material material,String name,List<String> lines,Runnable action){var item=new ItemStack(material);var meta=item.getItemMeta();meta.setDisplayName(color(name));meta.setLore(lines.stream().map(x->color("&7"+x)).toList());item.setItemMeta(meta);v.inventory.setItem(slot,item);if(action!=null)v.actions.put(slot,action);}
    @EventHandler public void click(InventoryClickEvent e){if(!(e.getView().getTopInventory().getHolder() instanceof View v))return;e.setCancelled(true);if(!(e.getWhoClicked() instanceof Player p))return;if(!access(p,v.town)){p.closeInventory();return;}var action=v.actions.get(e.getRawSlot());if(action!=null)Bukkit.getScheduler().runTask(plugin,()->{if(p.isOnline()&&p.getOpenInventory().getTopInventory().getHolder()==v&&access(p,v.town))action.run();});}
    @EventHandler public void drag(InventoryDragEvent e){if(e.getView().getTopInventory().getHolder() instanceof View)e.setCancelled(true);}
}
