package ru.neverland.townyjobs;
import org.bukkit.configuration.file.YamlConfiguration;
import java.nio.file.*;import java.nio.channels.FileChannel;import java.nio.ByteBuffer;import java.nio.charset.StandardCharsets;import java.io.IOException;import java.util.*;
public final class JobsRepository {
    private final Path file;private boolean writable;private volatile Map<UUID,Career> workers=Map.of();
    public JobsRepository(Path file){this.file=file;}public boolean writable(){return writable;}public Map<UUID,Career> all(){return workers;}public Career get(UUID id){return workers.getOrDefault(id,Career.empty());}
    public void load()throws Exception{writable=false;if(!Files.exists(file)){workers=Map.of();writable=true;return;}var y=new YamlConfiguration();y.load(file.toFile());if(JobsSettings.integer(y.get("schema"))!=1||!y.isConfigurationSection("workers"))throw new IOException("Неверная база профессий");Map<UUID,Career> next=new HashMap<>();var root=y.getConfigurationSection("workers");for(String id:root.getKeys(false)){var s=root.getConfigurationSection(id);if(s==null||!s.isString("profession")||!s.isString("town")||!s.isString("building")||!s.isConfigurationSection("experience-seconds"))throw new IOException("Повреждён работник");String role=s.getString("profession"),town=s.getString("town");Map<Profession,Long> xp=new EnumMap<>(Profession.class);var exp=s.getConfigurationSection("experience-seconds");for(String key:exp.getKeys(false))xp.put(Profession.parse(key),JobsSettings.integer(exp.get(key)));next.put(UUID.fromString(id),new Career(role.isEmpty()?null:Profession.parse(role),xp,town.isEmpty()?null:UUID.fromString(town),s.getString("building"),JobsSettings.integer(s.get("assigned-at")),JobsSettings.integer(s.get("changed-at")),JobsSettings.integer(s.get("revision"))));}workers=Map.copyOf(next);writable=true;}
    public void put(UUID id,Career c)throws IOException{var next=new HashMap<>(workers);next.put(id,c);replace(next);}
    public void replace(Map<UUID,Career> next)throws IOException{if(!writable)throw new IOException("База профессий недоступна");next=Map.copyOf(next);if(next.equals(workers))return;var y=new YamlConfiguration();y.set("schema",1);y.createSection("workers");for(var e:next.entrySet()){String k="workers."+e.getKey()+".";var c=e.getValue();y.set(k+"profession",c.profession()==null?"":c.profession().id());y.set(k+"town",c.town()==null?"":c.town().toString());y.set(k+"building",c.building());y.set(k+"assigned-at",c.assignedAt());y.set(k+"changed-at",c.changedAt());y.set(k+"revision",c.revision());y.createSection(k+"experience-seconds");c.seconds().forEach((role,seconds)->y.set(k+"experience-seconds."+role.id(),seconds));}
        Path parent=file.toAbsolutePath().getParent();Path tmp=null;try{Files.createDirectories(parent);tmp=Files.createTempFile(parent,"jobs-",".tmp");try(var ch=FileChannel.open(tmp,StandardOpenOption.WRITE,StandardOpenOption.TRUNCATE_EXISTING)){var bytes=ByteBuffer.wrap(y.saveToString().getBytes(StandardCharsets.UTF_8));while(bytes.hasRemaining())ch.write(bytes);ch.force(true);}try{Files.move(tmp,file,StandardCopyOption.ATOMIC_MOVE,StandardCopyOption.REPLACE_EXISTING);}catch(AtomicMoveNotSupportedException ex){Files.move(tmp,file,StandardCopyOption.REPLACE_EXISTING);}workers=next;}catch(IOException|RuntimeException ex){writable=false;throw ex;}finally{if(tmp!=null)Files.deleteIfExists(tmp);}
    }
}
