package ru.neverland.townyjobs;
import java.util.*;import java.util.function.BiConsumer;import org.bukkit.*;import org.bukkit.entity.Player;import org.bukkit.inventory.*;import org.bukkit.inventory.meta.ItemMeta;import org.bukkit.event.*;import org.bukkit.event.inventory.*;import org.bukkit.plugin.java.JavaPlugin;
public final class JobsMenus implements Listener {
    private final JavaPlugin plugin;private final JobsService service;
    private static final class View implements InventoryHolder {UUID viewer,town;Inventory inventory;Map<Integer,BiConsumer<Player,Boolean>> actions=new HashMap<>();@Override public Inventory getInventory(){return inventory;}}
    public JobsMenus(JavaPlugin plugin,JobsService service){this.plugin=plugin;this.service=service;}
    public static String color(String text){return ChatColor.translateAlternateColorCodes('&',text);}
    public static void message(org.bukkit.command.CommandSender p,String text){p.sendMessage(color("&8[&dNeverLand &7• &fПрофессии&8] &r"+text));}
    private View view(Player p,String title){if(!p.hasPermission("neverlandtownyjobs.use"))throw new IllegalArgumentException("Нет прав на профессии");var town=service.town(p);if(town==null)throw new IllegalArgumentException("Вы не состоите в городе");View v=new View();v.viewer=p.getUniqueId();v.town=town.getUUID();v.inventory=Bukkit.createInventory(v,54,title);return v;}
    private void button(View v,int slot,Material icon,String name,List<String> lore,BiConsumer<Player,Boolean> action){ItemStack item=new ItemStack(icon);ItemMeta meta=item.getItemMeta();meta.setDisplayName(color(name));meta.setLore(lore.stream().map(JobsMenus::color).toList());meta.addItemFlags(ItemFlag.HIDE_ATTRIBUTES);item.setItemMeta(meta);v.inventory.setItem(slot,item);if(action!=null)v.actions.put(slot,action);}
    private void back(View v){button(v,49,Material.ARROW,"&fК профессиям",List.of(),(p,s)->open(p));}
    private void show(Player p,View v){p.openInventory(v.inventory);}
    private void attempt(Player p,Checked action){try{action.run();}catch(Exception ex){message(p,"&c"+ex.getMessage());}}
    private interface Checked {void run()throws Exception;}
    public void open(Player p){service.refresh(false);View v=view(p,"Городские профессии");Career c=service.career(p.getUniqueId());var settings=service.settings();List<String> info=new ArrayList<>();info.add("&7Профессия: &f"+(c.profession()==null?"Не выбрана":settings.profiles().get(c.profession()).name()));if(c.profession()!=null){info.add("&7Уровень: &a"+settings.level(c)+"/5");info.add("&7Опыт смен: &f"+c.seconds().getOrDefault(c.profession(),0L)/60+" мин.");int level=settings.level(c);if(level<5)info.add("&7Следующий уровень: &f"+settings.levels().get(level)+" мин.");info.add("&7Личный вклад: &a+"+percent(settings.profiles().get(c.profession()).bonus().get(level-1))+"%");}
        info.add("&7Место: &f"+(c.town()==null?"Не выбрано":settings.building(c.building())));info.add("&7Состояние: &e"+service.status(p.getUniqueId()));long seconds=service.cooldown(p.getUniqueId());if(seconds>0)info.add("&7До смены профессии: &f"+((seconds+59)/60)+" мин.");button(v,4,Material.PLAYER_HEAD,"&dМоя профессия",info,null);
        int[] slots={19,20,21,22,23,24,25};int n=0;for(Profession role:Profession.values()){var profile=settings.profiles().get(role);List<String> lore=new ArrayList<>();profile.description().forEach(t->lore.add("&7"+t));lore.add("&7Здания:");profile.buildings().stream().sorted().forEach(id->lore.add("&f• "+settings.building(id)));lore.add("&7Бонус: &a"+percent(profile.bonus().get(0))+"–"+percent(profile.bonus().get(4))+"%");lore.add(profile.enabled()?"&eНажмите для выбора с подтверждением":"&cОтключено");button(v,slots[n++],profile.icon(),"&f"+profile.name(),lore,(who,s)->choose(who,role));}
        button(v,38,Material.CRAFTING_TABLE,"&eВыбрать рабочее место",List.of("&7Количество мест зависит от уровня здания"),(who,s)->workplaces(who,0));
        button(v,40,service.onDuty(p.getUniqueId())?Material.RED_DYE:Material.LIME_DYE,service.onDuty(p.getUniqueId())?"&cЗакончить смену":"&aНачать смену",List.of("&7Подойдите к рабочему зданию","&7Работайте по выбранной профессии","&7Нет опыта за время вне игры"),(who,s)->attempt(who,()->{service.duty(who);open(who);}));
        button(v,42,Material.WRITABLE_BOOK,"&bРаботники города",List.of("&7Мэр и помощник могут освобождать места"),(who,s)->staff(who,0));if(c.town()!=null)button(v,46,Material.BARRIER,"&cОсвободить своё место",List.of("&7Профессия и весь опыт сохранятся"),(who,s)->attempt(who,()->{service.leave(who);open(who);}));show(p,v);
    }
    public void choose(Player p,Profession role){View v=view(p,"Выбор профессии");var settings=service.settings();var profile=settings.profiles().get(role);Career c=service.career(p.getUniqueId());List<String> lore=new ArrayList<>();profile.description().forEach(t->lore.add("&7"+t));lore.add("&eТекущее рабочее место будет освобождено");lore.add("&7Накопленный опыт каждой профессии сохраняется");lore.add("&7Следующая смена профессии: через "+settings.cooldown()+" ч.");button(v,13,profile.icon(),"&f"+profile.name(),lore,null);button(v,30,Material.LIME_CONCRETE,"&aПодтвердить выбор",List.of(),(who,s)->attempt(who,()->{service.choose(who,role,c.revision(),settings);message(who,"&aПрофессия выбрана. Теперь выберите рабочее место.");open(who);}));back(v);show(p,v);}
    public void workplaces(Player p,int page){attempt(p,()->{View v=view(p,"Рабочие места");Career c=service.career(p.getUniqueId());if(c.profession()==null)throw new IllegalArgumentException("Сначала выберите профессию");var settings=service.settings();var sites=service.workplaces(v.town);var ids=settings.profiles().get(c.profession()).buildings().stream().sorted().toList();int slot=0;
        for(String id:ids.stream().skip(page*45L).limit(45).toList()){var site=sites.get(id);int capacity=WorkPolicy.seats(site,settings);long used=service.repository().all().values().stream().filter(career->v.town.equals(career.town())&&id.equals(career.building())).count();List<String> lore=new ArrayList<>();lore.add("&7Занято мест: &f"+used+"/"+capacity);lore.add("&7На смене: &a"+service.workers(v.town,id));lore.add("&7Бонус здания: &a+"+percent(service.bonus(v.town,id))+"%");
            if(site==null||site.level()<1)lore.add("&cЗдание ещё не построено");else{lore.add("&7Уровень здания: &f"+site.level());World w=Bukkit.getWorld(site.world());lore.add("&7Мир: &f"+(w==null?"Недоступен":w.getName()));lore.add("&7Координаты: &f"+site.minX()+", "+site.y()+", "+site.minZ());if(!site.owned())lore.add("&cУчасток не принадлежит городу");if(!site.active())lore.add("&cСодержание или энергия недоступны");}
            lore.add("&eНажмите, чтобы занять место");button(v,slot++,site!=null&&site.level()>0?settings.profiles().get(c.profession()).icon():Material.GRAY_DYE,"&f"+settings.building(id),lore,(who,s)->attempt(who,()->{service.work(who,id);message(who,"&aРабочее место выбрано. Подойдите к зданию и начните смену.");open(who);}));
        }pages(v,page,ids.size(),this::workplaces);back(v);show(p,v);});}
    public void staff(Player p,int page){service.refresh(false);View v=view(p,"Работники города");var rows=service.repository().all().entrySet().stream().filter(e->v.town.equals(e.getValue().town())).sorted(Map.Entry.comparingByKey()).toList();int slot=0;boolean manager=service.manager(p,service.town(p));
        for(var row:rows.stream().skip(page*45L).limit(45).toList()){Career c=row.getValue();var resident=com.palmergames.bukkit.towny.TownyAPI.getInstance().getResident(row.getKey());String name=resident==null?row.getKey().toString().substring(0,8):resident.getName();var profile=service.settings().profiles().get(c.profession());List<String> lore=new ArrayList<>(List.of("&7Профессия: &f"+profile.name(),"&7Уровень: &f"+service.settings().level(c),"&7Место: &f"+service.settings().building(c.building()),"&7"+service.status(row.getKey())));if(manager)lore.add("&eНажмите для освобождения места");button(v,slot++,profile.icon(),"&f"+name,lore,manager?(who,s)->release(who,row.getKey(),c.revision(),name):null);}
        back(v);pages(v,page,rows.size(),this::staff);show(p,v);
    }
    private void release(Player p,UUID actor,long revision,String name){View v=view(p,"Освобождение рабочего места");button(v,13,Material.PAPER,"&f"+name,List.of("&7Профессия и накопленный опыт сохранятся"),null);button(v,30,Material.RED_CONCRETE,"&cОсвободить место",List.of(),(who,s)->attempt(who,()->{service.release(who,actor,revision);staff(who,0);}));back(v);show(p,v);}
    private void pages(View v,int page,int count,java.util.function.BiConsumer<Player,Integer> action){if(page>0)button(v,45,Material.ARROW,"&fНазад",List.of(),(p,s)->action.accept(p,page-1));if((page+1)*45<count)button(v,53,Material.ARROW,"&fДалее",List.of(),(p,s)->action.accept(p,page+1));}
    public static String percent(double value){return String.format(Locale.ROOT,"%.1f",100*value);}
    @EventHandler public void click(InventoryClickEvent e){var inv=e.getView().getTopInventory();if(!(inv.getHolder() instanceof View v))return;e.setCancelled(true);if(!(e.getWhoClicked() instanceof Player p)||e.getRawSlot()<0||e.getRawSlot()>=inv.getSize())return;var action=v.actions.get(e.getRawSlot());if(action==null)return;boolean shift=e.isShiftClick();Bukkit.getScheduler().runTask(plugin,()->{if(!p.isOnline()||p.getOpenInventory().getTopInventory()!=inv||!p.getUniqueId().equals(v.viewer))return;var town=service.town(p);if(town==null||!town.getUUID().equals(v.town)||!p.hasPermission("neverlandtownyjobs.use")){p.closeInventory();return;}attempt(p,()->action.accept(p,shift));});}
    @EventHandler public void drag(InventoryDragEvent e){if(e.getView().getTopInventory().getHolder() instanceof View)e.setCancelled(true);}
}
