package ru.neverland.townyjobs;
import java.util.*;import org.bukkit.command.*;import org.bukkit.entity.Player;import com.palmergames.bukkit.towny.TownyAPI;
public final class JobsCommand implements CommandExecutor,TabCompleter {
    private final NeverLandTownyJobs plugin;private final JobsService service;private final JobsMenus menus;
    public JobsCommand(NeverLandTownyJobs p,JobsService s,JobsMenus m){plugin=p;service=s;menus=m;}
    @Override public boolean onCommand(CommandSender sender,Command command,String label,String[] args){try{
        if(args.length>0&&args[0].equalsIgnoreCase("admin")){if(!sender.hasPermission("neverlandtownyjobs.admin"))throw new IllegalArgumentException("Нет прав администратора");if(args.length==2&&args[1].equalsIgnoreCase("reload")){plugin.reloadJobs();JobsMenus.message(sender,"&aНастройки применены; смены нужно начать заново.");}else if(args.length==4&&args[1].equalsIgnoreCase("release")&&args[3].equalsIgnoreCase("confirm")){UUID actor;try{actor=UUID.fromString(args[2]);}catch(IllegalArgumentException ex){var resident=TownyAPI.getInstance().getResident(args[2]);if(resident==null)throw new IllegalArgumentException("Житель не найден");actor=resident.getUUID();}service.adminRelease(actor);plugin.getLogger().info(sender.getName()+" освободил рабочее место "+actor);JobsMenus.message(sender,"&aМесто освобождено. Опыт сохранён.");}else JobsMenus.message(sender,"/townyjobs admin reload; /townyjobs admin release <житель|UUID> confirm");return true;}
        if(!(sender instanceof Player p))throw new IllegalArgumentException("Команда доступна игроку");if(!p.hasPermission("neverlandtownyjobs.use"))throw new IllegalArgumentException("Нет прав на профессии");if(service.town(p)==null)throw new IllegalArgumentException("Нужно состоять в городе");
        String action=args.length==0?"menu":args[0].toLowerCase(Locale.ROOT);switch(action){case "menu","info"->menus.open(p);case "choose"->{if(args.length!=2)throw new IllegalArgumentException("/t jobs choose <профессия>");menus.choose(p,Profession.parse(args[1]));}case "work"->{if(args.length==1)menus.workplaces(p,0);else if(args.length==2){service.work(p,args[1].toLowerCase(Locale.ROOT));menus.open(p);}else throw new IllegalArgumentException("/t jobs work <здание>");}case "duty"->{service.duty(p);menus.open(p);}case "leave"->{service.leave(p);menus.open(p);}case "staff"->menus.staff(p,0);default->JobsMenus.message(p,"&f/t jobs &7— профессии\n&f/t jobs choose <профессия>\n&f/t jobs work [здание]\n&f/t jobs duty &7— начать/закончить смену\n&f/t jobs leave &7— освободить своё место\n&f/t jobs staff &7— работники города");}
    }catch(Exception ex){JobsMenus.message(sender,"&c"+ex.getMessage());}return true;}
    @Override public List<String> onTabComplete(CommandSender sender,Command c,String alias,String[] args){List<String> list=List.of();if(args.length==1)list=List.of("choose","work","duty","leave","staff","info","help");if(args.length==2&&args[0].equalsIgnoreCase("choose"))list=Arrays.stream(Profession.values()).map(Profession::id).toList();if(args.length==2&&args[0].equalsIgnoreCase("work")&&sender instanceof Player p){var career=service.career(p.getUniqueId());if(career.profession()!=null)list=service.settings().profiles().get(career.profession()).buildings().stream().sorted().toList();}String prefix=args.length==0?"":args[args.length-1].toLowerCase(Locale.ROOT);return list.stream().filter(s->s.startsWith(prefix)).toList();}
}
