package ru.neverland.townyjobs;
import java.util.*;import org.bukkit.*;import org.bukkit.block.data.Ageable;import org.bukkit.entity.*;import org.bukkit.event.*;import org.bukkit.event.block.*;import org.bukkit.event.entity.*;import org.bukkit.event.player.*;import org.bukkit.event.inventory.*;
public final class JobsListener implements Listener {
    private final JobsService service;private final Map<UUID,Location> patrol=new HashMap<>();
    public JobsListener(JobsService service){this.service=service;}
    @EventHandler(priority=EventPriority.MONITOR,ignoreCancelled=true)public void interact(PlayerInteractEvent e){if(e.getHand()!=org.bukkit.inventory.EquipmentSlot.HAND||e.getAction()!=org.bukkit.event.block.Action.RIGHT_CLICK_BLOCK||e.getClickedBlock()==null||e.useInteractedBlock()==Event.Result.DENY)return;Material m=e.getClickedBlock().getType();Profession job=switch(m){case ANVIL,CHIPPED_ANVIL,DAMAGED_ANVIL,SMITHING_TABLE,BLAST_FURNACE,FURNACE->Profession.BLACKSMITH;case COMPOSTER,BEEHIVE,BEE_NEST,HAY_BLOCK->Profession.FARMER;case LEVER,DAYLIGHT_DETECTOR,REPEATER,COMPARATOR->Profession.ENGINEER;case CHEST,TRAPPED_CHEST,BARREL,CHISELED_BOOKSHELF->Profession.MERCHANT;case LECTERN,BOOKSHELF,ENCHANTING_TABLE,CARTOGRAPHY_TABLE->Profession.RESEARCHER;case BREWING_STAND,CAULDRON,WATER_CAULDRON->Profession.ALCHEMIST;default->null;};if(job!=null)service.signal(e.getPlayer().getUniqueId(),job);}
    @EventHandler(priority=EventPriority.MONITOR,ignoreCancelled=true)public void crop(BlockBreakEvent e){if(e.getBlock().getBlockData() instanceof Ageable a&&a.getAge()==a.getMaximumAge())service.signal(e.getPlayer().getUniqueId(),Profession.FARMER);}
    @EventHandler(priority=EventPriority.MONITOR,ignoreCancelled=true)public void breed(EntityBreedEvent e){if(e.getBreeder() instanceof Player p)service.signal(p.getUniqueId(),Profession.FARMER);}
    @EventHandler(priority=EventPriority.MONITOR,ignoreCancelled=true)public void shear(PlayerShearEntityEvent e){service.signal(e.getPlayer().getUniqueId(),Profession.FARMER);}
    @EventHandler(priority=EventPriority.MONITOR,ignoreCancelled=true)public void place(BlockPlaceEvent e){if(e.canBuild())service.signal(e.getPlayer().getUniqueId(),Profession.ENGINEER);}
    @EventHandler(priority=EventPriority.MONITOR,ignoreCancelled=true)public void smelt(FurnaceExtractEvent e){if(e.getItemAmount()>0)service.signal(e.getPlayer().getUniqueId(),Profession.BLACKSMITH);}
    @EventHandler(priority=EventPriority.MONITOR,ignoreCancelled=true)public void craft(CraftItemEvent e){if(!(e.getWhoClicked() instanceof Player p)||e.getAction()==InventoryAction.NOTHING)return;String key=e.getRecipe().getResult().getType().name();if(key.startsWith("IRON_")||key.startsWith("GOLDEN_")||key.startsWith("COPPER_")||key.startsWith("NETHERITE_"))service.signal(p.getUniqueId(),Profession.BLACKSMITH);if(Set.of("BOOK","WRITABLE_BOOK","MAP","PAPER").contains(key))service.signal(p.getUniqueId(),Profession.RESEARCHER);if(Set.of("BREAD","CAKE","COOKIE","PUMPKIN_PIE").contains(key))service.signal(p.getUniqueId(),Profession.FARMER);}
    @EventHandler(priority=EventPriority.MONITOR,ignoreCancelled=true)public void brew(BrewEvent e){service.signalAt(e.getBlock(),Profession.ALCHEMIST);}
    @EventHandler(priority=EventPriority.MONITOR,ignoreCancelled=true)public void kill(EntityDeathEvent e){Player p=e.getEntity().getKiller();if(p!=null&&e.getEntity() instanceof Enemy)service.signal(p.getUniqueId(),Profession.GUARD);}
    @EventHandler(priority=EventPriority.MONITOR,ignoreCancelled=true)public void move(PlayerMoveEvent e){if(e instanceof PlayerTeleportEvent||e.getTo()==null||service.career(e.getPlayer().getUniqueId()).profession()!=Profession.GUARD||!service.onDuty(e.getPlayer().getUniqueId()))return;Location old=patrol.get(e.getPlayer().getUniqueId());if(old==null||!old.getWorld().equals(e.getTo().getWorld())){patrol.put(e.getPlayer().getUniqueId(),e.getTo().clone());return;}if(old.distanceSquared(e.getTo())>=9){patrol.put(e.getPlayer().getUniqueId(),e.getTo().clone());service.signal(e.getPlayer().getUniqueId(),Profession.GUARD);}}
    @EventHandler(priority=EventPriority.HIGH,ignoreCancelled=true)public void protect(EntityDamageByEntityEvent e){if(!(e.getEntity() instanceof Player p))return;Entity source=e.getDamager();if(source instanceof Projectile projectile){if(!(projectile.getShooter() instanceof Entity shooter))return;source=shooter;}if(!(source instanceof Enemy))return;var town=service.town(p);var here=com.palmergames.bukkit.towny.TownyAPI.getInstance().getTown(p.getLocation());if(town==null||here==null||!town.getUUID().equals(here.getUUID()))return;e.setDamage(e.getDamage()*(1-service.townBonus(town.getUUID(),"guard_defence")));}
    @EventHandler public void quit(PlayerQuitEvent e){service.endShift(e.getPlayer().getUniqueId());patrol.remove(e.getPlayer().getUniqueId());}
    @EventHandler(priority=EventPriority.MONITOR,ignoreCancelled=true)public void teleport(PlayerTeleportEvent e){service.endShift(e.getPlayer().getUniqueId());patrol.remove(e.getPlayer().getUniqueId());}
    @EventHandler(priority=EventPriority.MONITOR,ignoreCancelled=true)public void mode(PlayerGameModeChangeEvent e){service.endShift(e.getPlayer().getUniqueId());}
    @EventHandler public void death(PlayerDeathEvent e){service.endShift(e.getPlayer().getUniqueId());}
    @EventHandler public void left(com.palmergames.bukkit.towny.event.TownRemoveResidentEvent e){service.removeResident(e.getResident().getUUID());}
    @EventHandler public void deleted(com.palmergames.bukkit.towny.event.DeleteTownEvent e){for(var row:service.repository().all().entrySet())if(e.getTownUUID().equals(row.getValue().town()))service.removeResident(row.getKey());}
}
