package ru.neverland.townyjobs;
import com.palmergames.bukkit.towny.TownyCommandAddonAPI;import org.bukkit.configuration.file.YamlConfiguration;import org.bukkit.plugin.ServicePriority;import org.bukkit.plugin.java.JavaPlugin;import ru.neverland.townyjobs.api.TownyJobsApi;
public final class NeverLandTownyJobs extends JavaPlugin {
    private JobsService service;private CityBridge bridge;private boolean townCommand;
    @Override public void onEnable(){try{saveDefaultConfig();bridge=new CityBridge();var repo=new JobsRepository(getDataFolder().toPath().resolve("jobs-data.yml"));repo.load();service=new JobsService(this,repo,settings(),bridge);var menus=new JobsMenus(this,service);var command=new JobsCommand(this,service,menus);var direct=getCommand("townyjobs");if(direct==null)throw new IllegalStateException("Нет команды townyjobs");direct.setExecutor(command);direct.setTabCompleter(command);townCommand=TownyCommandAddonAPI.addSubCommand(TownyCommandAddonAPI.CommandType.TOWN,"jobs",command);if(!townCommand)getLogger().warning("/t jobs занят; доступна /townyjobs");getServer().getPluginManager().registerEvents(menus,this);getServer().getPluginManager().registerEvents(new JobsListener(service),this);getServer().getServicesManager().register(TownyJobsApi.class,service,this,ServicePriority.Normal);service.start();if(service.fault())throw new IllegalStateException("Профессии не смогли рассчитать рабочие места");getLogger().info("Городские профессии включены: 7 профессий, рабочие места и опыт смен.");}catch(Exception|LinkageError ex){getLogger().log(java.util.logging.Level.SEVERE,"Профессии не загружены",ex);getServer().getPluginManager().disablePlugin(this);}}
    private JobsSettings settings()throws Exception{var y=new YamlConfiguration();y.load(getDataFolder().toPath().resolve("config.yml").toFile());return JobsSettings.load(y,bridge.known());}
    public void reloadJobs()throws Exception{var next=settings();service.reload(next);if(service.fault())throw new IllegalStateException("Настройки прочитаны, но рабочие места недоступны");}
    public JobsService jobs(){return service;}
    @Override public void onDisable(){if(service!=null)service.stop();getServer().getServicesManager().unregisterAll(this);if(townCommand)TownyCommandAddonAPI.removeSubCommand(TownyCommandAddonAPI.CommandType.TOWN,"jobs");}
}
