package ru.neverland.townypolicies.config;
import java.util.*;
import java.math.BigDecimal;
import org.bukkit.configuration.ConfigurationSection;
import ru.neverland.townypolicies.model.*;
import ru.neverland.integration.PolicyEffects;
public record PoliciesSettings(long cooldownMillis,int interval,Map<String,PolicyGroup> groups){
    public PoliciesSettings{groups=Collections.unmodifiableMap(new LinkedHashMap<>(groups));if(cooldownMillis<0||cooldownMillis>365L*86400000||interval<1||interval>60||!groups.keySet().equals(PolicyEffects.GROUPS))throw new IllegalArgumentException("Неверные настройки политик");}
    public static long integer(Object raw){try{return new BigDecimal(String.valueOf(raw)).longValueExact();}catch(Exception e){throw new IllegalArgumentException("Нужно целое число: "+raw);}}
    private static List<String> strings(ConfigurationSection s,String key){Object value=s.get(key);if(!(value instanceof List<?> list))throw new IllegalArgumentException("Нужен список "+key);var out=new ArrayList<String>();for(Object item:list){if(!(item instanceof String text)||text.isBlank()||out.contains(text))throw new IllegalArgumentException("Неверный или повторный элемент "+key);out.add(text);}return out;}
    public static PoliciesSettings load(ConfigurationSection config,ConfigurationSection data){Map<String,PolicyGroup> groups=new LinkedHashMap<>();var root=data.getConfigurationSection("policies");if(root==null)throw new IllegalArgumentException("Нет policies");for(String id:root.getKeys(false)){var g=root.getConfigurationSection(id);if(g==null||!(g.get("enabled") instanceof Boolean enabled))throw new IllegalArgumentException("Неверная политика");var options=g.getConfigurationSection("options");if(options==null)throw new IllegalArgumentException("Нет режимов");Map<String,PolicyOption> modes=new LinkedHashMap<>();for(String mode:options.getKeys(false)){var p=options.getConfigurationSection(mode);if(p==null)throw new IllegalArgumentException("Неверный режим");var effects=new LinkedHashMap<String,Double>();var e=p.getConfigurationSection("effects");if(e==null)throw new IllegalArgumentException("Нет effects");for(String key:e.getKeys(false))effects.put(key,Double.parseDouble(String.valueOf(e.get(key))));modes.put(mode,new PolicyOption(mode,p.getString("name"),p.getString("icon"),strings(p,"advantages"),strings(p,"disadvantages"),effects,new LinkedHashSet<>(strings(p,"requires")),new LinkedHashSet<>(strings(p,"production-projects")),new LinkedHashSet<>(strings(p,"upkeep-projects"))));}groups.put(id,new PolicyGroup(id,g.getString("name"),g.getString("icon"),g.getString("default"),enabled,modes));}
        if(!groups.get("imports").standard().equals("open")||!groups.get("imports").options().keySet().equals(Set.of("open","nation","closed")))throw new IllegalArgumentException("Режимы импорта: open, nation, closed");
        // Effects cannot be enabled without the module responsible for their real cost/benefit.
        for(var g:groups.values())for(var p:g.options().values()){Set<String> needed=new HashSet<>();for(String e:p.effects().keySet())switch(e){case "tax"->{if(!g.id().equals("taxes"))throw new IllegalArgumentException("Налог только в taxes");needed.add("NeverLandTownyTaxes");}case "tariff"->{if(!g.id().equals("tariffs"))throw new IllegalArgumentException("Пошлина только в tariffs");needed.add("NeverLandTownyTrade");}case "trade_time"->needed.add("NeverLandTownyTrade");case "army"->needed.add("NeverLandTownyBuilds");case "production"->needed.add("NeverLandTownyResources");case "upkeep"->needed.add("NeverLandTownyUpkeep");case "happiness"->needed.add("NeverLandTownyPopulation");}if(g.id().equals("imports")&&!p.id().equals("open"))needed.add("NeverLandTownyTrade");if(!p.requires().containsAll(needed))throw new IllegalArgumentException("Не указаны зависимости эффектов: "+g.id()+"/"+p.id());if(p.effects().containsKey("production")&&p.production().isEmpty()||p.effects().containsKey("upkeep")&&p.upkeep().isEmpty())throw new IllegalArgumentException("Не заданы здания для эффекта");}
        return new PoliciesSettings(Math.multiplyExact(integer(config.get("selection.change-cooldown-hours",24)),3600000L),Math.toIntExact(integer(config.get("simulation.interval-seconds",5))),groups);}
}
