package ru.neverland.townytreasury;
import ru.neverland.townytreasury.model.*;
import ru.neverland.townytreasury.data.TreasuryRepository;
import ru.neverland.townytreasury.service.*;
import ru.neverland.townytreasury.config.TreasurySettings;
import org.bukkit.configuration.file.YamlConfiguration;
import java.util.*;
import java.nio.file.*;
import java.time.*;
public final class TreasurySmoke {
    private static void check(boolean condition,String name){if(!condition)throw new AssertionError(name);}
    private interface Checked {void run()throws Exception;}
    private static void fails(Checked action,String name)throws Exception{try{action.run();}catch(Exception expected){return;}throw new AssertionError(name);}
    private static final Map<Budget,Integer> SHARES=Map.of(Budget.CONSTRUCTION,40,Budget.ARMY,20,Budget.INFRASTRUCTURE,25,Budget.SOCIAL,15);
    public static void main(String[] args)throws Exception{
        long now=Instant.parse("2026-09-13T23:59:59Z").toEpochMilli();String week=Week.key(now);check(week.equals("2026-09-07"),"Sunday UTC belongs to current week");check(Week.key(now+1000).equals("2026-09-14")&&Week.previous(now+1000).equals(week),"Monday rollover");
        check(Money.cents(.29)==29&&Money.parse("1,005")==101,"decimal cents");fails(()->Money.cents(Double.NaN),"NaN rejected");fails(()->Money.parse("1e50"),"overflow rejected");
        var base=CityLedger.initial(1000000,SHARES,now);check(base.funds().get(Budget.FREE)==1000000&&!base.enabled(),"existing town has free real balance");
        var city=LedgerEngine.mode(base,true,"Мэр");check(city.balance()==base.balance()&&city.funds().get(Budget.ARMY)==200000&&city.funds().get(Budget.CONSTRUCTION)==400000,"activation only allocates real money");check(!LedgerEngine.canSpend(city,Budget.ARMY,200001)&&LedgerEngine.canSpend(city,Budget.ARMY,200000),"rich treasury cannot bypass empty category");
        var shifted=LedgerEngine.transfer(city,Budget.SOCIAL,Budget.ARMY,50000,"Мэр");check(shifted.balance()==city.balance()&&shifted.funds().get(Budget.ARMY)==250000&&shifted.weeks().isEmpty(),"internal transfer is not income or spending");
        var initial=city;fails(()->LedgerEngine.transfer(initial,Budget.FREE,Budget.ARMY,1,"Мэр"),"no unallocated funds");fails(()->LedgerEngine.shares(initial,Map.of(Budget.ARMY,101),"Мэр"),"bad proportions");
        UUID id=UUID.randomUUID();var pending=new CityLedger.Pending(id,now,10000,Budget.ARMY,"upkeep","Содержание штаба");city=LedgerEngine.prepare(city,pending);check(!LedgerEngine.canSpend(city,Budget.CONSTRUCTION,1),"unresolved external payment blocks retries");check(LedgerEngine.reconcile(city,990000,now).equals(city),"unknown debit must not be guessed from balance");
        Path dir=Files.createTempDirectory("treasury-smoke");Path file=dir.resolve("treasury.yml");UUID town=UUID.randomUUID();var repo=new TreasuryRepository(file);repo.load();repo.put(town,city);var restart=new TreasuryRepository(file);restart.load();check(restart.cities().get(town).equals(city)&&restart.cities().get(town).pending().id().equals(id),"pending journal survives exact restart");
        city=LedgerEngine.observe(city,10000,false,Budget.ARMY,"upkeep",false,now,id);check(city.pending()==null&&city.balance()==990000&&city.funds().get(Budget.ARMY)==190000,"successful observed debit debits category once");check(city.weeks().get(week).totalExpense()==10000,"only paid expense recorded");var paid=city;fails(()->LedgerEngine.cancel(paid,id),"completed receipt cannot be resolved again");
        city=LedgerEngine.observe(city,10000,true,Budget.ARMY,"upkeep",true,now,null);check(city.balance()==1000000&&city.funds().get(Budget.ARMY)==200000&&city.weeks().get(week).totalIncome()==0&&city.weeks().get(week).refunds()==10000,"refund restores original budget, is not fresh income");
        city=LedgerEngine.observe(city,10000,true,Budget.FREE,"tax",false,now,null);check(city.funds().get(Budget.CONSTRUCTION)==404000&&city.weeks().get(week).income().get("tax")==10000,"actual tax proceeds use planned shares");
        var failed=LedgerEngine.prepare(city,new CityLedger.Pending(UUID.randomUUID(),now,1,Budget.ARMY,"upkeep","Не оплачено"));failed=LedgerEngine.cancel(failed,failed.pending().id());check(failed.balance()==city.balance()&&failed.weeks().equals(city.weeks()),"failed debit does not spend or count");
        city=LedgerEngine.reconcile(city,-3000,now);check(city.funds().values().stream().mapToLong(Long::longValue).sum()==0&&city.balance()==-3000,"external overdraft never creates negative allocated funds");city=LedgerEngine.observe(city,10000,true,Budget.FREE,"other",false,now,null);check(city.balance()==7000&&city.funds().values().stream().mapToLong(Long::longValue).sum()==7000,"deposit repays overdraft before allocation");
        var random=new Random(7616);for(int i=0;i<10000;i++){int operation=random.nextInt(4);long amount=random.nextInt(2000);Budget category=Budget.values()[random.nextInt(5)];if(operation==0)city=LedgerEngine.observe(city,amount,true,category,"other",false,now,null);else if(operation==1)city=LedgerEngine.observe(city,amount,false,category,"other",false,now,null);else if(operation==2)city=LedgerEngine.reconcile(city,city.balance()+random.nextInt(2001)-1000,now);else if(city.enabled()&&city.funds().get(category)>0){Budget to=Budget.values()[(category.ordinal()+1)%5];city=LedgerEngine.transfer(city,category,to,Math.min(city.funds().get(category),1+amount),"Мэр");}check(city.funds().values().stream().mapToLong(Long::longValue).sum()==Math.max(0,city.balance()),"conservation in mixed payments "+i);check(city.funds().values().stream().allMatch(n->n>=0),"no negative budget");}
        for(int i=0;i<30;i++)city=LedgerEngine.observe(city,1,true,Budget.FREE,"tax",false,now+i*7*86400000L,null);check(city.weeks().size()==13&&city.history().size()<=30,"bounded archive and history");
        city=LedgerEngine.mode(city,false,"Мэр");check(city.funds().get(Budget.FREE)==Math.max(0,city.balance()),"disable releases allocations without withdrawing");repo.put(town,city);repo.put(UUID.randomUUID(),base);restart=new TreasuryRepository(file);restart.load();check(restart.cities().get(town).equals(city)&&restart.cities().size()==2,"UUID separation and complete report persistence");
        Path block=dir.resolve("blocked.yml");var blocked=new TreasuryRepository(block);blocked.load();blocked.put(town,base);Files.delete(block);Files.createDirectory(block);Files.writeString(block.resolve("keep"),"safe");var finalCity=city;fails(()->blocked.put(town,finalCity),"atomic replacement failure");check(blocked.cities().get(town).equals(base)&&Files.readString(block.resolve("keep")).equals("safe"),"failed write keeps previous memory and disk");
        Path bad=dir.resolve("bad.yml");Files.writeString(bad,"schema: 1\ncities: [broken");var broken=new TreasuryRepository(bad);fails(broken::load,"invalid data rejected");fails(()->broken.put(town,base),"damaged database cannot be overwritten");
        var settings=new YamlConfiguration();settings.load(Path.of("src/main/resources/config.yml").toFile());var config=TreasurySettings.load(settings);check(config.projects().size()==101&&config.category("project/army")==Budget.ARMY&&config.category("project/infirmary")==Budget.SOCIAL&&config.category("project/water_tower")==Budget.INFRASTRUCTURE,"101 upkeep project mappings");settings.set("income-shares.army",-1);fails(()->TreasurySettings.load(settings),"bad settings rejected");
        check(TreasuryService.versionAtLeast("0.1.10","0.1.9")&&!TreasuryService.versionAtLeast("0.1.9","0.1.10")&&!TreasuryService.versionAtLeast("dev","0.1.10"),"minimum version numeric comparison");
        var export=LedgerEngine.observe(base,12345,true,Budget.FREE,"tax",false,now,null);Path csv=ReportExporter.write(dir.resolve("reports"),town,"=DANGEROUS;\"",week,export);String text=Files.readString(csv);check(text.contains("Налоги")&&text.contains("123.45")&&text.contains("'=DANGEROUS"),"CSV amounts and formula escaping");fails(()->ReportExporter.write(dir,town,"City","../../escape",export),"path traversal rejected");
        DebitSmoke.run();
        System.out.println("TreasurySmoke OK: allocation conservation, 10000 mixed operations, refund accounting, pending debit restart, atomic failure, UUID isolation, 101 upkeep categories, UTC weeks and CSV");
    }
}
