package ru.neverland.mintexpeditions.service;
import org.bukkit.Material; import org.bukkit.configuration.ConfigurationSection; import org.bukkit.configuration.file.YamlConfiguration; import org.bukkit.entity.EntityType; import org.bukkit.inventory.ItemStack; import org.bukkit.plugin.java.JavaPlugin;
import ru.neverland.mintexpeditions.integration.ItemsAdderHook; import ru.neverland.mintexpeditions.model.*;
import java.io.File; import java.util.*;
public final class ExpeditionRegistry {
    private final JavaPlugin plugin; private final ItemsAdderHook itemsAdder; private final Map<String,ExpeditionDefinition> entries=new LinkedHashMap<>();
    public ExpeditionRegistry(JavaPlugin plugin,ItemsAdderHook itemsAdder){this.plugin=plugin;this.itemsAdder=itemsAdder;reload();}
    public void reload(){entries.clear(); YamlConfiguration y=YamlConfiguration.loadConfiguration(new File(plugin.getDataFolder(),"expeditions.yml")); ConfigurationSection root=y.getConfigurationSection("expeditions"); if(root==null)return; for(String id:root.getKeys(false))try{String p="expeditions."+id+"."; Material icon=material(y.getString(p+"icon")); Material objective=material(y.getString(p+"objective-material")); EntityType mob=EntityType.valueOf(y.getString(p+"mob","ZOMBIE").toUpperCase(Locale.ROOT)); ExpeditionDefinition d=new ExpeditionDefinition(id,y.getString(p+"name",id),ExpeditionType.valueOf(y.getString(p+"type","RUINS")),ObjectiveType.valueOf(y.getString(p+"objective","EXCAVATE")),icon,y.getInt(p+"slot",20),y.getInt(p+"min-camp-level",1),y.getLong(p+"duration-minutes",20)*60,y.getInt(p+"distance.min",256),y.getInt(p+"distance.max",480),y.getInt(p+"goal",4),objective,mob,y.getInt(p+"mob-count",0),items(PotionSupplies.migrate(id,y.getStringList(p+"costs"))),items(y.getStringList(p+"rewards")),y.getDouble(p+"money-per-participant"),y.getStringList(p+"description")); entries.put(id,d);}catch(RuntimeException e){plugin.getLogger().severe("Шаблон "+id+" пропущен: "+e.getMessage());} plugin.getLogger().info("Загружено экспедиций: "+entries.size()+".");}
    private List<ItemAmount> items(List<String> list){List<ItemAmount> out=new ArrayList<>(); for(String raw:list){int split=raw.lastIndexOf(':');String tail=split>0?raw.substring(split+1):"";boolean numbered=tail.matches("[0-9]+");String key=numbered?raw.substring(0,split):raw;int amount=numbered?Integer.parseInt(tail):1; ItemStack stack=PotionSupplies.create(key); if(stack==null)stack=itemsAdder.item(key); if(stack==null){Material m=material(key); stack=new ItemStack(m);} out.add(new ItemAmount(key,stack,amount));} return out;}
    private Material material(String s){Material m=Material.matchMaterial(s==null?"STONE":s); if(m==null)throw new IllegalArgumentException("неизвестный материал "+s); return m;}
    public Collection<ExpeditionDefinition> all(){return Collections.unmodifiableCollection(entries.values());} public ExpeditionDefinition get(String id){return entries.get(id.toLowerCase(Locale.ROOT));}
}
