package ru.neverland.mintexpeditions.service;

import org.bukkit.Material; import org.bukkit.configuration.ConfigurationSection; import org.bukkit.configuration.file.YamlConfiguration; import org.bukkit.inventory.ItemStack; import org.bukkit.plugin.java.JavaPlugin;
import ru.neverland.mintexpeditions.model.*;
import java.io.*; import java.util.*;

public final class ExpeditionRepository {
    private final JavaPlugin plugin; private final File file; private final Map<UUID,ActiveExpedition> active=new LinkedHashMap<>(); private final List<ExpeditionHistory> history=new ArrayList<>();
    private final Map<UUID,List<ItemStack>> items=new LinkedHashMap<>(); private final Map<UUID,Double> money=new LinkedHashMap<>(); private boolean dirty;
    public ExpeditionRepository(JavaPlugin plugin){this.plugin=plugin;file=new File(plugin.getDataFolder(),"data.yml");}
    public void load(){active.clear();history.clear();items.clear();money.clear();if(!file.exists())return;YamlConfiguration y=YamlConfiguration.loadConfiguration(file);ConfigurationSection root=y.getConfigurationSection("active");if(root!=null)for(String raw:root.getKeys(false))try{String p="active."+raw+".";UUID id=UUID.fromString(raw);ActiveExpedition e=new ActiveExpedition(id,UUID.fromString(y.getString(p+"leader")),y.getString(p+"definition"),UUID.fromString(y.getString(p+"world-id")),y.getString(p+"world-name"),BlockPos.parse(y.getString(p+"camp")),BlockPos.parse(y.getString(p+"site")),y.getLong(p+"started"),y.getLong(p+"expires"));for(String v:y.getStringList(p+"participants"))e.participants().add(UUID.fromString(v));for(String v:y.getStringList(p+"objectives"))e.objectives().add(BlockPos.parse(v));for(String v:y.getStringList(p+"completed"))e.completed().add(BlockPos.parse(v));e.kills(y.getInt(p+"kills"));for(Map<?,?> m:y.getMapList(p+"snapshots")){BlockPos pos=BlockPos.parse(String.valueOf(m.get("pos")));Material mat=Material.matchMaterial(String.valueOf(m.get("material")));if(mat==null)continue;List<ItemStack> inv=new ArrayList<>();Object rawInv=m.get("inventory");if(rawInv instanceof List<?> list)for(Object o:list)if(o instanceof ItemStack s)inv.add(s);e.snapshots().put(pos,new SiteSnapshot(mat,String.valueOf(m.get("data")),inv));}active.put(id,e);}catch(RuntimeException ex){plugin.getLogger().severe("Не удалось загрузить экспедицию "+raw+": "+ex.getMessage());}
        for(Map<?,?> m:y.getMapList("history"))try{history.add(new ExpeditionHistory(UUID.fromString(String.valueOf(m.get("id"))),UUID.fromString(String.valueOf(m.get("leader"))),String.valueOf(m.get("definition")),num(m,"participants"),num(m,"objectives"),num(m,"kills"),ExpeditionStatus.valueOf(String.valueOf(m.get("status"))),Long.parseLong(String.valueOf(m.get("ended")))));}catch(RuntimeException ignored){}
        ConfigurationSection reward=y.getConfigurationSection("rewards");if(reward!=null)for(String raw:reward.getKeys(false))try{UUID id=UUID.fromString(raw);List<ItemStack> list=new ArrayList<>();for(Object o:y.getList("rewards."+raw+".items",List.of()))if(o instanceof ItemStack s)list.add(s);if(!list.isEmpty())items.put(id,list);double value=y.getDouble("rewards."+raw+".money");if(value>0)money.put(id,value);}catch(RuntimeException ignored){} dirty=false;}
    private int num(Map<?,?>m,String k){return Integer.parseInt(String.valueOf(m.get(k)));}
    public void save(){YamlConfiguration y=new YamlConfiguration();for(ActiveExpedition e:active.values()){String p="active."+e.id()+".";y.set(p+"leader",e.leaderId().toString());y.set(p+"definition",e.definitionId());y.set(p+"world-id",e.worldId().toString());y.set(p+"world-name",e.worldName());y.set(p+"camp",e.campAnchor().key());y.set(p+"site",e.siteAnchor().key());y.set(p+"started",e.startedAt());y.set(p+"expires",e.expiresAt());y.set(p+"participants",e.participants().stream().map(UUID::toString).toList());y.set(p+"objectives",e.objectives().stream().map(BlockPos::key).toList());y.set(p+"completed",e.completed().stream().map(BlockPos::key).toList());y.set(p+"kills",e.kills());List<Map<String,Object>> snaps=new ArrayList<>();for(var s:e.snapshots().entrySet()){Map<String,Object> m=new LinkedHashMap<>();m.put("pos",s.getKey().key());m.put("material",s.getValue().material().name());m.put("data",s.getValue().blockData());if(!s.getValue().inventory().isEmpty())m.put("inventory",s.getValue().inventory());snaps.add(m);}y.set(p+"snapshots",snaps);}
        List<Map<String,Object>> hist=new ArrayList<>();for(ExpeditionHistory h:history){Map<String,Object>m=new LinkedHashMap<>();m.put("id",h.id().toString());m.put("leader",h.leaderId().toString());m.put("definition",h.definitionId());m.put("participants",h.participants());m.put("objectives",h.objectives());m.put("kills",h.kills());m.put("status",h.status().name());m.put("ended",h.endedAt());hist.add(m);}y.set("history",hist);Set<UUID> ids=new LinkedHashSet<>(items.keySet());ids.addAll(money.keySet());for(UUID id:ids){y.set("rewards."+id+".items",items.getOrDefault(id,List.of()));y.set("rewards."+id+".money",money.getOrDefault(id,0D));}try{y.save(file);dirty=false;}catch(IOException ex){plugin.getLogger().severe("Не удалось сохранить data.yml: "+ex.getMessage());}}
    public Collection<ActiveExpedition> active(){return Collections.unmodifiableCollection(active.values());} public ActiveExpedition get(UUID id){return active.get(id);} public ActiveExpedition byLeader(UUID id){return active.values().stream().filter(e->e.leaderId().equals(id)||e.participants().contains(id)).findFirst().orElse(null);} public ActiveExpedition byCamp(UUID id){return active.values().stream().filter(e->e.leaderId().equals(id)).findFirst().orElse(null);}
    public void put(ActiveExpedition e){active.put(e.id(),e);dirty=true;}public void remove(ActiveExpedition e){active.remove(e.id());dirty=true;}public void changed(){dirty=true;}public void saveIfDirty(){if(dirty)save();}
    public void history(ExpeditionHistory h,int limit){history.add(0,h);while(history.size()>limit)history.remove(history.size()-1);dirty=true;}public List<ExpeditionHistory> history(){return Collections.unmodifiableList(history);}
    public void reward(UUID id,List<ItemStack> stacks,double value){items.computeIfAbsent(id,k->new ArrayList<>()).addAll(stacks.stream().map(ItemStack::clone).toList());money.merge(id,value,Double::sum);dirty=true;} public List<ItemStack> takeItems(UUID id){List<ItemStack> out=items.remove(id);dirty=true;return out==null?List.of():out;}public double money(UUID id){return money.getOrDefault(id,0D);}public void clearMoney(UUID id){money.remove(id);dirty=true;}public boolean hasReward(UUID id){return items.containsKey(id)||money.getOrDefault(id,0D)>0;}
}
