package ru.neverland.mintexpeditions.service;
import org.bukkit.Material; import ru.neverland.mintexpeditions.model.*; import java.util.*;
public final class SiteGenerator {
    public SitePlan generate(ExpeditionDefinition d,BlockPos a){Map<BlockPos,Material>b=new LinkedHashMap<>();Set<BlockPos>o=new LinkedHashSet<>();switch(d.type()){case RUINS->ruins(a,b,o,d);case SHIPWRECK->wreck(a,b,o,d);case ANOMALY->anomaly(a,b,o,d);}return new SitePlan(b,o);}
    private void ruins(BlockPos a,Map<BlockPos,Material>b,Set<BlockPos>o,ExpeditionDefinition d){for(int x=-6;x<=6;x++)for(int z=-6;z<=6;z++)if(Math.abs(x)<6&&Math.abs(z)<6)b.put(a.add(x,0,z),(x+z)%4==0?Material.MOSSY_STONE_BRICKS:Material.STONE_BRICKS);for(int x=-6;x<=6;x++)for(int z:new int[]{-6,6})wall(a,b,x,z);for(int z=-5;z<=5;z++)for(int x:new int[]{-6,6})wall(a,b,x,z);b.put(a.add(0,1,0),Material.CHISELED_STONE_BRICKS);for(BlockPos p:points(a,d.goal(),5)){b.put(p,d.objectiveMaterial());o.add(p);}}
    private void wall(BlockPos a,Map<BlockPos,Material>b,int x,int z){if((Math.abs(x*31+z*17)%4)!=0){b.put(a.add(x,1,z),Material.MOSSY_STONE_BRICKS);if((Math.abs(x+z)%3)==0)b.put(a.add(x,2,z),Material.CRACKED_STONE_BRICKS);}}
    private void wreck(BlockPos a,Map<BlockPos,Material>b,Set<BlockPos>o,ExpeditionDefinition d){for(int x=-7;x<=7;x++)for(int z=-3;z<=3;z++)if(Math.abs(z)<=3-Math.abs(x)/4)b.put(a.add(x,0,z),Material.DARK_OAK_PLANKS);for(int x=-6;x<=6;x++){b.put(a.add(x,1,-3),Material.DARK_OAK_PLANKS);b.put(a.add(x,1,3),Material.DARK_OAK_PLANKS);}for(int y=1;y<=6;y++)b.put(a.add(0,y,0),Material.STRIPPED_DARK_OAK_LOG);for(int z=-3;z<=3;z++)b.put(a.add(0,5,z),Material.WHITE_WOOL);for(BlockPos p:points(a,d.goal(),5)){BlockPos q=p.add(0,1,0);b.put(q,d.objectiveMaterial());o.add(q);}}
    private void anomaly(BlockPos a,Map<BlockPos,Material>b,Set<BlockPos>o,ExpeditionDefinition d){for(int x=-6;x<=6;x++)for(int z=-6;z<=6;z++){double r=Math.sqrt(x*x+z*z);if(r>4.5&&r<6.5)b.put(a.add(x,0,z),Material.OBSIDIAN);else if(r<3)b.put(a.add(x,0,z),Material.CALCITE);}for(int y=1;y<=5;y++)b.put(a.add(0,y,0),y==5?Material.AMETHYST_CLUSTER:Material.CRYING_OBSIDIAN);for(BlockPos p:points(a,d.goal(),5)){BlockPos q=p.add(0,1,0);b.put(q,d.objectiveMaterial());o.add(q);}}
    private List<BlockPos> points(BlockPos a,int count,int radius){List<BlockPos> out=new ArrayList<>();for(int i=0;i<count;i++){double v=2*Math.PI*i/Math.max(1,count);out.add(a.add((int)Math.round(Math.cos(v)*radius),0,(int)Math.round(Math.sin(v)*radius)));}return out;}
}
