package ru.neverland.mintexpeditions.integration;
import org.bukkit.*;import org.bukkit.entity.Player;import org.bukkit.inventory.ItemStack;import org.bukkit.plugin.java.JavaPlugin;import java.util.*;
import ru.neverland.core.ApiServices;import ru.neverland.mintexpeditions.model.ItemAmount;
public final class CampFacade {
    public record CampView(UUID owner,World world,Location anchor,int level,long burnUntil,Set<UUID> trusted,ItemStack[] stash){}
    private final JavaPlugin plugin;private final ru.neverland.mintexpeditions.service.RussianItemNames itemNames;
    public CampFacade(JavaPlugin plugin,ru.neverland.mintexpeditions.service.RussianItemNames itemNames){this.plugin=plugin;this.itemNames=itemNames;}
    private ApiServices.Connection api(){return ApiServices.connect(plugin.getConfig().getString("camps.plugin","NeverLandTownyCamps"),"ru.neverland.mintcamps.api.TownyCampsApi",1,"camp","stashBusy","consume");}
    public CampView owned(Player player){return owned(player.getUniqueId());}
    public CampView owned(UUID player){var connection=api();if(!connection.ready())return null;try{var c=(Map<?,?>)connection.invoke("camp",new Class<?>[]{UUID.class},player);if(c.isEmpty())return null;UUID owner=(UUID)c.get("owner");World world=Bukkit.getWorld((UUID)c.get("world"));if(world==null)world=Bukkit.getWorld((String)c.get("worldName"));return new CampView(owner,world,new Location(world,((Number)c.get("x")).doubleValue()+.5,((Number)c.get("y")).doubleValue()+1,((Number)c.get("z")).doubleValue()+.5),((Number)c.get("level")).intValue(),((Number)c.get("burnUntil")).longValue(),Set.copyOf((Set<UUID>)c.get("trusted")),(ItemStack[])c.get("stash"));}catch(ReflectiveOperationException|RuntimeException ex){return null;}}
    public boolean stashOpen(UUID owner){var connection=api();if(!connection.ready())return true;try{return Boolean.TRUE.equals(connection.invoke("stashBusy",new Class<?>[]{UUID.class},owner));}catch(ReflectiveOperationException|RuntimeException ex){return true;}}
    public List<Player> party(CampView c){List<Player> out=new ArrayList<>(); Player leader=Bukkit.getPlayer(c.owner()); if(leader!=null)out.add(leader); int cap=plugin.getConfig().getInt("camps.maximum-party-by-level."+c.level(),c.level()*2); double radius=plugin.getConfig().getDouble("camps.party-radius",20); for(UUID id:c.trusted()){Player p=Bukkit.getPlayer(id);if(p!=null&&p.getWorld().equals(c.world())&&p.getLocation().distanceSquared(c.anchor())<=radius*radius&&out.size()<cap)out.add(p);} return out;}
    public String missing(CampView c,List<ItemAmount> costs){List<String> missing=new ArrayList<>(); for(ItemAmount cost:costs){int have=0;for(ItemStack s:c.stash())if(s!=null&&s.isSimilar(cost.item()))have+=s.getAmount();if(have<cost.amount())missing.add(itemNames.name(cost.item())+" × "+(cost.amount()-have));}return String.join(", ",missing);}
    public boolean consume(CampView camp,List<ItemAmount> costs){var connection=api();if(!connection.ready())return false;try{ItemStack[] items=costs.stream().map(c->{var item=c.item().clone();item.setAmount(c.amount());return item;}).toArray(ItemStack[]::new);return Boolean.TRUE.equals(connection.invoke("consume",new Class<?>[]{UUID.class,ItemStack[].class},camp.owner(),items));}catch(ReflectiveOperationException|RuntimeException ex){return false;}}
}
