package ru.neverland.runtime;
import java.lang.reflect.*;import java.nio.file.*;import java.util.*;
import org.bukkit.*;import org.bukkit.entity.Player;import org.bukkit.plugin.*;import org.bukkit.plugin.java.JavaPlugin;
import org.bukkit.inventory.*;import org.bukkit.event.inventory.*;import org.bukkit.permissions.PermissibleBase;
import net.kyori.adventure.text.Component;
import com.palmergames.bukkit.towny.*;import com.palmergames.bukkit.towny.object.*;
import ru.neverland.townyjustice.*;import ru.neverland.townyjustice.api.*;
import ru.neverland.townytreasury.api.TownyTreasuryApi;
import ru.neverland.townycouncil.*;
/** Opt-in disposable server fixture. Actual economy, API, jail persistence and restart; no network clients. */
public final class JusticeRuntimeProbe extends JavaPlugin {
    static UUID id(String s){return UUID.nameUUIDFromBytes(("justice-030-"+s).getBytes(java.nio.charset.StandardCharsets.UTF_8));}
    static final UUID T=id("town"),M=id("mayor"),S=id("subject"),H=id("hunter"),D=id("minister"),P=id("pending");
    Path proof;boolean restart;int checks;World world;Location cell;Town town;JusticeService justice;JusticeRepository ledger;TownyJusticeApi api;
    int expected(String key)throws Exception{var p=new Properties();try(var in=getResource("expected-counts.properties")){p.load(in);}return Integer.parseInt(p.getProperty(key));}
    JavaPlugin plugin(String name){return (JavaPlugin)Objects.requireNonNull(Bukkit.getPluginManager().getPlugin(name));}
    static <T>T field(Object owner,Class<T> type)throws Exception{for(var f:owner.getClass().getDeclaredFields())if(type.isAssignableFrom(f.getType())){f.setAccessible(true);return type.cast(f.get(owner));}throw new IllegalArgumentException(type.getName());}
    void check(boolean b,String label)throws Exception{if(!b)throw new AssertionError(label);checks++;Files.writeString(proof.resolve((restart?"restart":"first")+"-checks.txt"),label+"\n",StandardOpenOption.CREATE,StandardOpenOption.APPEND);getLogger().info("CHECK "+label);}
    interface Action{void run()throws Exception;}void denied(Action a,String label)throws Exception{boolean denied=false;try{a.run();}catch(Exception e){denied=true;}check(denied,label);}
    void pulse()throws Exception{var method=JusticeService.class.getDeclaredMethod("pulse");method.setAccessible(true);method.invoke(justice);}
    void advance(){for(var p:List.copyOf(ledger.state().payments().values()))try{for(int i=0;i<3;i++)JusticePayments.advance(p.id(),System.currentTimeMillis(),1000,ledger,new JusticeBank());}catch(Exception e){throw new RuntimeException(e);}}
    @Override public void onEnable(){if(!Boolean.getBoolean("neverland.runtimeProbe")||!Files.isRegularFile(Path.of("ALLOW_DISPOSABLE_RELIABILITY_PROBE"))||!"127.0.0.1".equals(getServer().getIp())){Bukkit.getPluginManager().disablePlugin(this);return;}Bukkit.getScheduler().runTaskLater(this,this::run,100);}
    void run(){try{proof=getDataFolder().toPath();Files.createDirectories(proof);restart=Files.exists(proof.resolve("first-passed.txt"));world=Bukkit.getWorlds().getFirst();cell=new Location(world,132*16+4.5,96,132*16+4.5);
        check(Arrays.stream(Bukkit.getPluginManager().getPlugins()).filter(p->p.getName().startsWith("NeverLandTowny")&&p.isEnabled()).count()==expected("addons"),"all exact-version addons enabled");contracts();
        api=Bukkit.getServicesManager().load(TownyJusticeApi.class);justice=field(plugin("NeverLandTownyJustice"),JusticeService.class);ledger=justice.repository();check(api!=null&&api.healthy(),"healthy native Justice API and durable repository");
        if(restart){town=TownyAPI.getInstance().getTown(T);restartChecks();}else{setup();scenarios();}
        TownyUniverse.getInstance().getDataSource().saveAll();world.save();Files.writeString(proof.resolve((restart?"restart":"first")+"-passed.txt"),"PASS "+checks+" assertions\n");Bukkit.getScheduler().runTaskLater(this,Bukkit::shutdown,1);
    }catch(Throwable e){getLogger().log(java.util.logging.Level.SEVERE,"JUSTICE_PROBE_FAIL",e);try{var sw=new java.io.StringWriter();e.printStackTrace(new java.io.PrintWriter(sw));Files.createDirectories(getDataFolder().toPath());Files.writeString(getDataFolder().toPath().resolve("failed.txt"),sw.toString());}catch(Exception ignored){}Bukkit.getScheduler().runTaskLater(this,Bukkit::shutdown,1);}}
    void setup()throws Exception{check(TownyAPI.getInstance().getTown(T)==null,"fresh disposable fixture");var u=TownyUniverse.getInstance();u.newTownInternal("JusticeAudit",T);town=TownyAPI.getInstance().getTown(T);
        for(var e:Map.of(M,"JusticeMayor",S,"JusticeSubject",H,"JusticeHunter",D,"JusticeMinister").entrySet()){var resident=u.getDataSource().newResident(e.getValue(),e.getKey());resident.setTown(town);resident.save();}
        town.setMayor(TownyAPI.getInstance().getResident(M));var claim=new TownBlock(132,132,u.getWorld(world.getName()));u.addTownBlock(claim);claim.setTown(town);town.setHomeBlock(claim);claim.save();world.getChunkAt(132,132).load();cell.getBlock().setType(Material.AIR);cell.getBlock().getRelative(0,1,0).setType(Material.AIR);cell.getBlock().getRelative(0,-1,0).setType(Material.STONE);town.setSpawn(cell.clone().add(4,0,4));town.save();
        check(town.getAccount().deposit(100000,"disposable Justice seed"),"real town bank seed");check(TownyAPI.getInstance().getResident(S).getAccount().deposit(10000,"disposable Justice seed"),"real resident bank seed");
    }
    void scenarios()throws Exception{var mayor=new Actor(M);var subject=new Actor(S);var hunter=new Actor(H);check(justice.manager(mayor.player,T)&&!justice.manager(subject.player,T),"mayor authority excludes ordinary resident");
        denied(()->justice.issue(subject.player,JusticeCase.Kind.FINE,M,100,0,"Unauthorised fine"),"ordinary resident cannot issue fines");
        UUID fine=justice.issue(mayor.player,JusticeCase.Kind.FINE,S,12000,0,"Fixture municipal fine");var f=justice.get(fine);check(api.fines(S).size()==1&&!justice.readable(hunter.player,f),"fines visible only to debtor or town court");double city=town.getAccount().getHoldingBalance(),money=TownyAPI.getInstance().getResident(S).getAccount().getHoldingBalance();denied(()->justice.pay(hunter.player,fine),"another player cannot pay/debit someone else's fine");justice.pay(subject.player,fine);check(justice.get(fine).phase()==JusticeCase.Phase.PAID,"fine reaches paid after both native bank legs");check(Math.abs(town.getAccount().getHoldingBalance()-city-120)<.001&&Math.abs(TownyAPI.getInstance().getResident(S).getAccount().getHoldingBalance()-money+120)<.001,"exact native resident debit and city fine income");denied(()->justice.pay(subject.player,fine),"completed fine cannot be paid again");
        var council=((NeverLandTownyCouncil)plugin("NeverLandTownyCouncil")).council();var minister=new Actor(D);council.appoint(mayor.player,town,MinisterRole.DEFENSE,D);council.refresh(minister.player);check(minister.player.hasPermission("neverlandtownycouncil.action.justice")&&justice.manager(minister.player,T),"Council defense minister receives scoped court authority");check(!justice.manager(minister.player,id("other-town")),"court permission never grants another town authority");council.dismiss(mayor.player,town,MinisterRole.DEFENSE);council.refresh(minister.player);check(!justice.manager(minister.player,T),"dismissal revokes court authority immediately");
        var menu=new JusticeMenu(plugin("NeverLandTownyJustice"),justice);menu.open(subject.player,"menu",0,null);check(subject.top.getItem(20)!=null&&subject.top.getItem(22)!=null&&subject.top.getItem(24)==null,"player menu separates personal fines from public wanted list");menu.open(mayor.player,"menu",0,null);check(mayor.top.getItem(24)!=null,"court menu available to mayor");denied(()->menu.detail(hunter.player,fine,null),"private fine cannot be opened through menu");
        var jail=justice.createPrison(mayor.player,"AuditCell",false);var prison=ledger.state().prisons().get(jail);var nativeJail=new JusticeJails().usable(prison);check(nativeJail!=null&&TownyAPI.getInstance().getTownBlock(cell).isJail(),"Justice creates real municipal Towny jail and safe cell");new JusticeJails().ensure(prison);check(town.getJails().stream().filter(x->x.getUUID().equals(jail)).count()==1,"recovery does not duplicate Towny jail registration");
        denied(()->justice.createPrison(subject.player,"OtherCell",false),"ordinary resident cannot create city prison");
        double before=town.getAccount().getHoldingBalance();UUID warrant=justice.issue(mayor.player,JusticeCase.Kind.WARRANT,S,20000,2,"Fixture paid warrant");check(justice.get(warrant).phase()==JusticeCase.Phase.WANTED&&Math.abs(town.getAccount().getHoldingBalance()-before+200)<.001,"native army budget funds bounty before public warrant");check(api.wanted(S).size()==1,"funded wanted query exposes active warrant");denied(()->justice.capture(hunter.player,warrant),"offline target cannot be captured or award bounty");justice.cancel(mayor.player,warrant);advance();pulse();check(justice.get(warrant).phase()==JusticeCase.Phase.CANCELLED&&Math.abs(town.getAccount().getHoldingBalance()-before)<.001,"cancelled warrant refunds city escrow exactly once");advance();pulse();check(Math.abs(town.getAccount().getHoldingBalance()-before)<.001,"refund is not repeated");
        // Simulate a lost public Treasury reply after its real bank debit. Account receipt confirms success.
        var services=Bukkit.getServicesManager();var treasury=services.load(TownyTreasuryApi.class);var lost=(TownyTreasuryApi)Proxy.newProxyInstance(TownyTreasuryApi.class.getClassLoader(),new Class<?>[]{TownyTreasuryApi.class},(p,m,a)->{Object value=m.invoke(treasury,a);if(m.getName().equals("spend")&&Boolean.TRUE.equals(value))throw new IllegalStateException("lost reply after real debit");return value;});services.register(TownyTreasuryApi.class,lost,plugin("NeverLandTownyTreasuryPlus"),ServicePriority.Highest);
        UUID custody;try{custody=justice.issue(mayor.player,JusticeCase.Kind.WARRANT,S,5000,1,"Fixture custody check");}finally{services.unregister(TownyTreasuryApi.class,lost);}check(justice.get(custody).phase()==JusticeCase.Phase.WANTED&&Math.abs(town.getAccount().getHoldingBalance()-before+50)<.001,"observed Towny receipt resolves lost Treasury reply without duplicate debit");
        var arrest=justice.get(custody).arrest(H,jail,System.currentTimeMillis());ledger.put(arrest,null);var resident=TownyAPI.getInstance().getResident(S);resident.setJail(nativeJail);resident.setJailCell(0);resident.setJailHours(1);resident.save();pulse();check(justice.get(custody).phase()==JusticeCase.Phase.ARRESTING&&justice.get(custody).payout()==null,"native jailed flag plus offline player never confirms physical delivery or payout");Files.writeString(proof.resolve("custody.txt"),custody.toString());
        // Inject a confirmed-capture journal fixture; actual bank carries out and deduplicates its escrow payout.
        UUID paid=justice.issue(mayor.player,JusticeCase.Kind.WARRANT,D,7000,1,"Fixture confirmed capture");var captured=justice.get(paid).arrest(H,jail,System.currentTimeMillis());UUID payid=id("reward");var reward=new JusticePayment(payid,paid,T,H,JusticePayment.Kind.BOUNTY_PAY,7000,JusticePayment.Step.READY,System.currentTimeMillis(),0);ledger.put(captured.captured(payid,System.currentTimeMillis()),reward);double hunterBefore=TownyAPI.getInstance().getResident(H).getAccount().getHoldingBalance();advance();pulse();advance();pulse();check(ledger.get(payid).step()==JusticePayment.Step.COMPLETE&&Math.abs(TownyAPI.getInstance().getResident(H).getAccount().getHoldingBalance()-hunterBefore-70)<.001,"persisted confirmed-capture fixture pays real hunter account once");
        // Unknown bank result is left pending across a real process restart, never automatically retried.
        long now=System.currentTimeMillis();var pending=new JusticeCase(P,T,M,M,JusticeCase.Kind.WARRANT,3000,1,"Fixture unknown debit",now,now+86400000,JusticeCase.Phase.FUNDING,id("pending-payment"),null,null,null,0,0);var tx=new JusticePayment(pending.payment(),P,T,M,JusticePayment.Kind.BOUNTY_FUND,3000,JusticePayment.Step.DEBIT_PENDING,now,now);ledger.put(pending,tx);check(new JusticeBank().debit(tx),"fixture applies a real debit while journal retains unknown reply");Files.writeString(proof.resolve("city-balance.txt"),Double.toString(town.getAccount().getHoldingBalance()));pulse();check(ledger.get(tx.id()).step()==JusticePayment.Step.DEBIT_PENDING,"unknown debit is held for administrative reconciliation");
        var error=new java.util.concurrent.atomic.AtomicReference<Throwable>();var worker=new Thread(()->{try{api.wanted(null);}catch(Throwable e){error.set(e);}});worker.start();worker.join(2000);check(error.get() instanceof IllegalStateException,"Justice API rejects worker-thread queries");denied(()->api.caseFile(fine).orElseThrow().put("amount",0),"API returns immutable case snapshots");check(Bukkit.getPluginCommand("townyjustice")!=null,"Justice command registered");
    }
    void restartChecks()throws Exception{UUID custody=UUID.fromString(Files.readString(proof.resolve("custody.txt")));check(api.fines(S).isEmpty(),"paid fine remains paid after real restart");check(ledger.state().prisons().size()==1&&new JusticeJails().usable(ledger.state().prisons().values().iterator().next())!=null,"native Towny jail and Justice binding survive restart");check(justice.get(custody).phase()==JusticeCase.Phase.ARRESTING&&justice.get(custody).payout()==null,"offline custody stays unconfirmed across restart");check(ledger.get(id("reward")).step()==JusticePayment.Step.COMPLETE,"completed bounty payment survives restart");double expected=Double.parseDouble(Files.readString(proof.resolve("city-balance.txt")));check(Math.abs(town.getAccount().getHoldingBalance()-expected)<.001,"restart does not repeat any city debit or refund");check(ledger.get(id("pending-payment")).step()==JusticePayment.Step.DEBIT_PENDING&&justice.get(P).phase()==JusticeCase.Phase.FUNDING,"uncertain bank leg stays pending across restart");justice.resolve(id("pending-payment"),"debit-applied");check(justice.get(P).phase()==JusticeCase.Phase.WANTED&&Math.abs(town.getAccount().getHoldingBalance()-expected)<.001,"explicit bank reconciliation activates warrant without second debit");denied(()->justice.resolve(id("pending-payment"),"debit-applied"),"same administrative resolution cannot be applied twice");
        var mayor=new Actor(M);justice.release(mayor.player,custody);pulse();advance();pulse();check(justice.get(custody).phase()==JusticeCase.Phase.CANCELLED&&!TownyAPI.getInstance().getResident(S).isJailed(),"unconfirmed offline arrest can be pardoned through native Towny and escrow refunded");
    }
    void contracts()throws Exception{try(var reader=new java.io.BufferedReader(new java.io.InputStreamReader(getResource("contracts.tsv"),java.nio.charset.StandardCharsets.UTF_8))){var rows=reader.lines().toList();check(rows.size()==expected("contracts"),"all public contracts from source inventory");for(String line:rows){String[] row=line.split("\t");var p=plugin(row[0]);Class<?> type=Class.forName(row[1],true,p.getClass().getClassLoader());Object provider=Bukkit.getServicesManager().load(type);check(provider!=null&&p.isEnabled()&&p.getDescription().getVersion().equals(row[3])&&Integer.valueOf(1).equals(type.getMethod("apiVersion").invoke(provider))&&new HashSet<>(Arrays.asList(row[2].split(","))).equals(type.getMethod("capabilities").invoke(provider)),"provider ABI/capabilities: "+row[1]);}}}
    private final class Actor {
        final Player player; PermissibleBase permissions; Inventory top=Bukkit.createInventory(null,9,Component.text("Fixture")); final Inventory bottom=Bukkit.createInventory(null,36);
        InventoryView view; final List<String> messages=new ArrayList<>();
        Actor(UUID id) {
            player=(Player)Proxy.newProxyInstance(Player.class.getClassLoader(),new Class<?>[]{Player.class},(proxy,m,a)->switch(m.getName()) {
                case "getUniqueId"->id;case "getName"->TownyAPI.getInstance().getResident(id).getName();case "getServer"->Bukkit.getServer();case "getWorld"->world;case "getLocation"->cell;
                case "isOnline"->true;case "isDead","isInsideVehicle"->false;case "getGameMode"->GameMode.SURVIVAL;case "isOp"->false;
                case "hasPermission","isPermissionSet","addAttachment","removeAttachment","recalculatePermissions","getEffectivePermissions"->m.invoke(permissions,a);
                case "sendMessage"->{messages.add(String.valueOf(a[a.length-1]));yield null;}
                case "getOpenInventory"->view;case "openInventory"->{top=(Inventory)a[0];yield view;}case "closeInventory"->{top=Bukkit.createInventory(null,9);yield null;}
                case "hashCode"->id.hashCode();case "equals"->proxy==a[0];case "toString"->"Council actor "+id;default->null;
            });
            permissions=new PermissibleBase(player);
            view=(InventoryView)Proxy.newProxyInstance(InventoryView.class.getClassLoader(),new Class<?>[]{InventoryView.class},(proxy,m,a)->switch(m.getName()) {
                case "getTopInventory"->top;case "getBottomInventory"->bottom;case "getPlayer"->player;case "getType"->InventoryType.CHEST;
                case "getCursor"->new ItemStack(Material.AIR);case "countSlots"->top.getSize()+36;case "getTitle","getOriginalTitle"->"Fixture";case "title"->Component.text("Fixture");
                case "getSlotType"->InventoryType.SlotType.CONTAINER;case "convertSlot"->a[0];case "getInventory"->(Integer)a[0]<top.getSize()?top:bottom;default->null;
            });
        }
    }
}
