name: NeverLandTownyUpkeep
version: '0.1.2'
main: ru.neverland.townyupkeep.NeverLandTownyUpkeep
api-version: '26.2'
authors: [Alexander Sokolov]
description: Обслуживание зданий деньгами и стратегическими ресурсами.
depend: [Towny, NeverLandTownyBuilds, NeverLandTownyResources]
commands:
  townyupkeep:
    aliases: [nltupkeep, cityupkeep]
    description: Обслуживание городских зданий
    usage: /townyupkeep [info|pay|help|reload]
permissions:
  neverlandtownyupkeep.use:
    default: true
  neverlandtownyupkeep.manage:
    default: false
  neverlandtownyupkeep.admin:
    default: op
