package ru.neverland.townyspecialization.command;
import com.palmergames.bukkit.towny.TownyAPI;
import org.bukkit.command.*;
import org.bukkit.entity.Player;
import ru.neverland.townyspecialization.NeverLandTownySpecialization;
import ru.neverland.townyspecialization.gui.SpecializationMenu;
import ru.neverland.townyspecialization.service.*;
import java.util.*;
public final class SpecializationCommand implements CommandExecutor,TabCompleter {
    private final NeverLandTownySpecialization plugin;private final SpecializationService service;private final SpecializationMenu menu;
    public SpecializationCommand(NeverLandTownySpecialization plugin,SpecializationService service,SpecializationMenu menu){this.plugin=plugin;this.service=service;this.menu=menu;}
    private void count(String[] a,int n,String usage){if(a.length!=n)throw new IllegalArgumentException(usage);}
    @Override public boolean onCommand(CommandSender sender,Command command,String label,String[] args){try{execute(sender,args);}catch(Exception ex){Ui.tell(sender,"&c"+(ex.getMessage()==null?"Операция не завершена; проверьте консоль":ex.getMessage()));if(!(ex instanceof IllegalArgumentException||ex instanceof IllegalStateException))plugin.getLogger().log(java.util.logging.Level.WARNING,"Ошибка выбора специализации",ex);}return true;}
    private void execute(CommandSender sender,String[] args)throws Exception{String action=args.length==0?"menu":args[0].toLowerCase(Locale.ROOT);
        if(action.equals("reload")){count(args,1,"/townyspecialization reload");if(!sender.hasPermission("neverlandtownyspecialization.admin"))throw new IllegalArgumentException("Недостаточно прав");Ui.tell(sender,plugin.reloadSpecialization()?"Настройки специализаций обновлены.":"Настройки не применены; проверьте консоль.");return;}
        if(!(sender instanceof Player p))throw new IllegalArgumentException("Эта команда доступна в игре");
        if(action.equals("town")||action.equals("set")){if(!p.hasPermission("neverlandtownyspecialization.admin"))throw new IllegalArgumentException("Недостаточно прав");count(args,action.equals("town")?2:3,"/townyspecialization "+action+" <город>"+(action.equals("set")?" <направление>":""));var town=TownyAPI.getInstance().getTown(args[1]);if(town==null)throw new IllegalArgumentException("Город не найден");if(action.equals("town"))menu.open(p,town.getUUID(),null);else{service.offer(p,town.getUUID(),args[2],true);review(p);}return;}
        if(action.equals("confirm")){count(args,1,"/t specialization confirm");UUID town=service.confirm(p);Ui.tell(p,"Специализация города сохранена.");menu.open(p,town,null);return;}
        if(!p.hasPermission("neverlandtownyspecialization.use"))throw new IllegalArgumentException("Недостаточно прав");var town=service.town(p);if(town==null)throw new IllegalArgumentException("Вы не состоите в городе");
        switch(action){case "menu"->{count(args,args.length==0?0:1,"/t specialization");menu.open(p,town.getUUID(),null);}case "info"->{count(args,2,"/t specialization info <направление>");menu.open(p,town.getUUID(),args[1]);}case "choose"->{count(args,2,"/t specialization choose <направление>");service.offer(p,town.getUUID(),args[1],false);review(p);}case "help"->Ui.tell(p,"/t specialization — меню; info <направление> — бонусы; choose <направление> — подготовить выбор; confirm — подтвердить. Уникальное здание прошлого направления сохраняется и перестаёт работать.");default->throw new IllegalArgumentException("Справка: /t specialization help");}
    }
    private void review(Player p){var o=service.offer(p);var profile=o.settings().profiles().get(o.specialization());var town=TownyAPI.getInstance().getTown(o.town());Ui.tell(p,"Город «"+town.getName()+"» → "+profile.name()+". Выбор бесплатный. Уникальное здание прошлого направления перестанет работать. Следующая смена через "+o.settings().cooldownMillis()/3600000+" ч. "+(o.admin()?"Администратор обходит требования и текущий срок ожидания. ":"")+"Подтверждение в течение 60 секунд: /t specialization confirm");}
    @Override public List<String> onTabComplete(CommandSender sender,Command command,String alias,String[] args){var out=new ArrayList<String>();if(args.length==1){if(sender.hasPermission("neverlandtownyspecialization.use"))out.addAll(List.of("menu","info","choose","confirm","help"));if(sender.hasPermission("neverlandtownyspecialization.admin"))out.addAll(List.of("reload","town","set","confirm"));}else if(args.length==2&&Set.of("info","choose").contains(args[0])&&sender.hasPermission("neverlandtownyspecialization.use"))out.addAll(service.settings().profiles().keySet());else if(args.length==2&&Set.of("town","set").contains(args[0])&&sender.hasPermission("neverlandtownyspecialization.admin"))TownyAPI.getInstance().getTowns().forEach(t->out.add(t.getName()));else if(args.length==3&&args[0].equals("set")&&sender.hasPermission("neverlandtownyspecialization.admin"))out.addAll(service.settings().profiles().keySet());String prefix=args.length==0?"":args[args.length-1].toLowerCase(Locale.ROOT);return out.stream().filter(s->s.toLowerCase(Locale.ROOT).startsWith(prefix)).distinct().sorted().toList();}
}
