package ru.neverland.townyresearch.service;
import java.util.Map;
public final class BuildingNames { private BuildingNames(){} private static final Map<String,String> NAMES=Map.ofEntries(Map.entry("town_hall","Ратуша"),
Map.entry("forge","Кузница"),
Map.entry("barracks","Казармы"),
Map.entry("market","Рынок"),
Map.entry("miners_guild","Шахтёрская гильдия"),
Map.entry("temple","Священный Храм"),
Map.entry("great_library","Великая Библиотека"),
Map.entry("agrarian_complex","Аграрный Комплекс"),
Map.entry("infirmary","Лазарет"),
Map.entry("fire_station","Пожарная часть"),
Map.entry("tavern_inn","Таверна и постоялый двор"),
Map.entry("city_bank","Городской банк"),
Map.entry("embassy","Посольство"),
Map.entry("museum","Музей"),
Map.entry("shipyard","Верфь"),
Map.entry("university","Университет"),
Map.entry("courthouse","Суд"),
Map.entry("aqueduct","Акведук"),
Map.entry("workshop","Мастерская"),
Map.entry("watch_fortress","Сторожевая крепость"),
Map.entry("hunting_lodge","Охотничий дом"),
Map.entry("fishing_harbor","Рыбацкая гавань"),
Map.entry("post_station","Почтовая станция"),
Map.entry("observatory","Обсерватория"),
Map.entry("prison","Тюрьма"),
Map.entry("sawmill","Лесопилка"),
Map.entry("quarry","Каменоломня"),
Map.entry("foundry","Литейная"),
Map.entry("mill","Мельница"),
Map.entry("bakery","Пекарня"),
Map.entry("apiary","Пасека"),
Map.entry("warehouse","Городской склад"),
Map.entry("caravanserai","Караван-сарай"),
Map.entry("auction","Аукционный дом"),
Map.entry("merchant_guild","Торговая гильдия"),
Map.entry("cargo_terminal","Грузовой терминал"),
Map.entry("water_tower","Водонапорная башня"),
Map.entry("sewer","Канализация"),
Map.entry("baths","Городские бани"),
Map.entry("roads","Дороги"),
Map.entry("bridge_service","Мостовая служба"),
Map.entry("reservoir","Резервуар"),
Map.entry("guard","Городская стража"),
Map.entry("arsenal","Арсенал"),
Map.entry("armory","Оружейная"),
Map.entry("watchtower","Дозорная башня"),
Map.entry("fortress_gate","Крепостные ворота"),
Map.entry("counterintel","Палата контрразведки"),
Map.entry("alchemy","Алхимическая лаборатория"),
Map.entry("archive","Архив"),
Map.entry("cartography","Академия картографов"),
Map.entry("research","Исследовательский институт"),
Map.entry("botanical","Ботанический сад"),
Map.entry("theater","Театр"),
Map.entry("square","Городская площадь"),
Map.entry("arena","Арена"),
Map.entry("gallery","Художественная галерея"),
Map.entry("park","Парк"),
Map.entry("guild_house","Дом гильдий"),
Map.entry("memorial","Мемориал"),
Map.entry("shelter","Приют"),
Map.entry("cathedral","Собор"),
Map.entry("printing_house","Типография"),
Map.entry("forestry","Лесничество"),
Map.entry("customs","Таможня"),
Map.entry("trade_port","Торговый порт"),
Map.entry("mint","Монетный двор"),
Map.entry("stables","Конюшни"),
Map.entry("fortress_wall","Крепостная стена"),
Map.entry("city_moat","Городской ров"),
Map.entry("archery_range","Стрельбище"),
Map.entry("port_fort","Портовый форт"),
Map.entry("census_bureau","Бюро переписи населения"),
Map.entry("insurance_chamber","Страховая палата"),
Map.entry("pumping_station","Насосная станция"),
Map.entry("irrigation_station","Ирригационная станция"),
Map.entry("recycling_yard","Перерабатывающий двор"),
Map.entry("dam","Дамба"),
Map.entry("army","Штаб армии"),
Map.entry("residential_quarter","Жилой квартал"),
Map.entry("sun_pyramid","Пирамида Солнца"),
Map.entry("great_colosseum","Великий Колизей"),
Map.entry("alexandria_lighthouse","Александрийский Маяк"),
Map.entry("hanging_gardens","Висячие Сады"),
Map.entry("archmage_spire","Шпиль Архимагов"),
Map.entry("rhodes_colossus","Колосс Родосский"),
Map.entry("world_tree","Мировое древо"),
Map.entry("celestial_orrery","Небесный оррерий"),
Map.entry("terracotta_army","Терракотовая армия"),
Map.entry("crystal_palace","Хрустальный дворец"),
Map.entry("great_canal","Великий канал"),
Map.entry("water_wheel","Водяное колесо"),
Map.entry("generator","Генератор"),
Map.entry("power_station","Электростанция")); public static String name(String id){return NAMES.getOrDefault(id,"Городское здание");} }
