package ru.neverland.townychronicles.service;

import org.bukkit.configuration.ConfigurationSection;
import org.bukkit.configuration.file.YamlConfiguration;
import org.bukkit.plugin.java.JavaPlugin;
import ru.neverland.townychronicles.model.ChronicleCategory;
import ru.neverland.townychronicles.model.ChronicleEntry;
import ru.neverland.townychronicles.model.TownChronicleState;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;

public final class ChronicleRepository {
    private final JavaPlugin plugin;private final File file;private final Map<UUID,TownChronicleState>states=new LinkedHashMap<>();private final Map<UUID,List<ChronicleEntry>>entries=new LinkedHashMap<>();private boolean dirty;
    public ChronicleRepository(JavaPlugin plugin){this.plugin=plugin;file=new File(plugin.getDataFolder(),"chronicles.yml");}
    public synchronized void load(){states.clear();entries.clear();if(!file.exists())return;YamlConfiguration yaml=YamlConfiguration.loadConfiguration(file);ConfigurationSection root=yaml.getConfigurationSection("towns");if(root==null)return;for(String raw:root.getKeys(false))try{UUID id=UUID.fromString(raw);String base="towns."+raw;TownChronicleState state=new TownChronicleState(id);state.name(yaml.getString(base+".state.name",""));state.mayor(yaml.getString(base+".state.mayor-name",""),uuid(yaml.getString(base+".state.mayor-id")));state.nation(yaml.getString(base+".state.nation-name",""),uuid(yaml.getString(base+".state.nation-id")));state.residents(yaml.getInt(base+".state.residents"));state.blocks(yaml.getInt(base+".state.blocks"));state.balance(yaml.getDouble(base+".state.balance"));state.foundedAt(yaml.getLong(base+".state.founded-at"));state.lastSeen(yaml.getLong(base+".state.last-seen"));state.active(yaml.getBoolean(base+".state.active",true));state.achievements().addAll(yaml.getStringList(base+".state.achievements"));ConfigurationSection wonders=yaml.getConfigurationSection(base+".state.wonders");if(wonders!=null)for(String project:wonders.getKeys(false))state.wonders().put(project,wonders.getInt(project));states.put(id,state);ConfigurationSection values=yaml.getConfigurationSection(base+".entries");List<ChronicleEntry>list=new ArrayList<>();if(values!=null)for(String entryId:values.getKeys(false))try{String p=base+".entries."+entryId;list.add(new ChronicleEntry(UUID.fromString(entryId),id,yaml.getString(p+".town-name",state.name()),ChronicleCategory.valueOf(yaml.getString(p+".category","CUSTOM")),yaml.getLong(p+".timestamp"),yaml.getString(p+".title","Событие"),yaml.getStringList(p+".details"),yaml.getString(p+".actor",""),yaml.getString(p+".source","")));}catch(Exception exception){plugin.getLogger().warning("Пропущена запись "+entryId+" города "+raw);}list.sort(Comparator.comparingLong(ChronicleEntry::timestamp).reversed());entries.put(id,list);}catch(Exception exception){plugin.getLogger().warning("Пропущена повреждённая летопись "+raw+": "+exception.getMessage());}dirty=false;}
    public synchronized TownChronicleState state(UUID townId){return states.computeIfAbsent(townId,id->{dirty=true;return new TownChronicleState(id);});}public synchronized List<TownChronicleState>states(){return List.copyOf(states.values());}
    public synchronized void add(ChronicleEntry entry){List<ChronicleEntry>list=entries.computeIfAbsent(entry.townId(),id->new ArrayList<>());list.add(0,entry);int maximum=Math.max(10,plugin.getConfig().getInt("storage.maximum-entries-per-town",1000));while(list.size()>maximum)list.remove(list.size()-1);dirty=true;}
    public synchronized List<ChronicleEntry>entries(UUID townId){return List.copyOf(entries.getOrDefault(townId,List.of()));}public synchronized List<ChronicleEntry>entries(UUID townId,ChronicleCategory category){return entries(townId).stream().filter(v->category==null||v.category()==category).toList();}
    public synchronized ChronicleEntry latest(UUID townId){List<ChronicleEntry>list=entries.get(townId);return list==null||list.isEmpty()?null:list.get(0);}public synchronized boolean remove(UUID id){for(List<ChronicleEntry>list:entries.values())if(list.removeIf(v->v.id().equals(id))){dirty=true;return true;}return false;}
    public synchronized ChronicleEntry find(String id){String lower=id.toLowerCase();for(List<ChronicleEntry>list:entries.values())for(ChronicleEntry entry:list)if(entry.id().toString().equalsIgnoreCase(id)||entry.id().toString().startsWith(lower))return entry;return null;}
    public synchronized void markDirty(){dirty=true;}public synchronized void saveIfDirty(){if(dirty)save();}
    public synchronized void save(){YamlConfiguration yaml=new YamlConfiguration();for(TownChronicleState state:states.values()){String base="towns."+state.townId();yaml.set(base+".state.name",state.name());yaml.set(base+".state.mayor-name",state.mayorName());yaml.set(base+".state.mayor-id",string(state.mayorId()));yaml.set(base+".state.nation-name",state.nationName());yaml.set(base+".state.nation-id",string(state.nationId()));yaml.set(base+".state.residents",state.residents());yaml.set(base+".state.blocks",state.blocks());yaml.set(base+".state.balance",state.balance());yaml.set(base+".state.founded-at",state.foundedAt());yaml.set(base+".state.last-seen",state.lastSeen());yaml.set(base+".state.active",state.active());yaml.set(base+".state.achievements",state.achievements().stream().sorted().toList());for(Map.Entry<String,Integer>wonder:state.wonders().entrySet())yaml.set(base+".state.wonders."+wonder.getKey(),wonder.getValue());for(ChronicleEntry entry:entries.getOrDefault(state.townId(),List.of())){String p=base+".entries."+entry.id();yaml.set(p+".town-name",entry.townName());yaml.set(p+".category",entry.category().name());yaml.set(p+".timestamp",entry.timestamp());yaml.set(p+".title",entry.title());yaml.set(p+".details",entry.details());yaml.set(p+".actor",entry.actor());yaml.set(p+".source",entry.source());}}try{yaml.save(file);dirty=false;}catch(IOException exception){plugin.getLogger().severe("Не удалось сохранить chronicles.yml: "+exception.getMessage());}}
    private UUID uuid(String value){try{return value==null?null:UUID.fromString(value);}catch(IllegalArgumentException exception){return null;}}private String string(UUID value){return value==null?null:value.toString();}
}
