package ru.neverland.townytreasury.gui;
import org.bukkit.*;
import org.bukkit.entity.Player;
import org.bukkit.event.*;
import org.bukkit.event.inventory.*;
import org.bukkit.inventory.*;
import java.util.*;
import ru.neverland.townytreasury.model.*;
import ru.neverland.townytreasury.service.*;
import static ru.neverland.townytreasury.service.Ui.*;
public final class TreasuryMenu implements Listener {
    private final org.bukkit.plugin.Plugin plugin;private final TreasuryService service;
    private static final class View implements InventoryHolder{final UUID town;final Map<Integer,Runnable> actions=new HashMap<>();Inventory inventory;View(UUID town){this.town=town;}public Inventory getInventory(){return inventory;}}
    public TreasuryMenu(org.bukkit.plugin.Plugin plugin,TreasuryService service){this.plugin=plugin;this.service=service;}
    public boolean access(Player p,UUID town){var own=service.town(p);return p.hasPermission("neverlandtownytreasury.admin")||p.hasPermission("neverlandtownytreasury.use")&&own!=null&&own.getUUID().equals(town);}
    public void open(Player p,UUID town,String page){if(!access(p,town)){tell(p,"Нет доступа к этому городу.");return;}var city=service.treasury(town).orElse(null);if(city==null){tell(p,"Ожидается работа экономики Towny.");return;}var view=new View(town);view.inventory=Bukkit.createInventory(view,54,color("&6Казна и городской бюджет"));
        if(page==null){button(view,4,Material.GOLD_INGOT,"&eКазна: "+Money.format(city.balance()),List.of("Учтённый баланс настоящей казны Towny.",service.fault()?"&cУчёт приостановлен: обратитесь к администратору.":city.pending()!=null?"&cЕсть незавершённое списание: нужна сверка.":"Учёт работает.",city.enabled()?"Статьи контролируют новые платежи аддонов.":"Контроль статей пока выключен."),null);int slot=19;for(var b:Budget.values()){button(view,slot++,Material.valueOf(b.icon()),"&e"+b.title(),List.of("Доступно: "+Money.format(city.funds().get(b)),"Доля новых поступлений: "+city.shares().get(b)+"%","Нажмите: управление статьёй."),()->open(p,town,b.id()));}
            button(view,30,city.enabled()?Material.REDSTONE_TORCH:Material.LEVER,city.enabled()?"&eВыключить контроль статей":"&aВключить бюджеты",List.of("Потребуется подтверждение мэра.","Настоящий баланс Towny не изменится.","При включении вся казна распределится по долям.","По умолчанию: 40% / 20% / 25% / 15%."),()->prepare(p,town,city.enabled()?"disable":"enable",List.of()));
            button(view,32,Material.WRITABLE_BOOK,"&eНедельные отчёты",List.of("Доходы, расходы, налоги и производство.","Неделя: понедельник–воскресенье, UTC.","Хранятся текущая и 12 предыдущих недель."),()->open(p,town,"reports"));button(view,40,Material.BOOK,"&eИстория бюджета",List.of("Последние 30 решений и сверок."),()->open(p,town,"history"));
        }else if(page.equals("reports")){String current=Week.key(System.currentTimeMillis());for(int i=0;i<13;i++){String week=java.time.LocalDate.parse(current).minusWeeks(i).toString();var data=city.weeks().get(week);if(data==null&&week.compareTo(Week.key(city.started()))<0)continue;button(view,10+i,Material.PAPER,"&eНеделя с "+week,List.of(i==0?"Текущая, ещё не завершена.":"Завершённая календарная неделя.","Нажмите: открыть отчёт."),()->open(p,town,"report/"+week));}}
        else if(page.startsWith("report/")){String week=page.substring(7);try{Week.validateKey(week);}catch(Exception e){tell(p,"Дата должна быть понедельником: ГГГГ-ММ-ДД.");return;}if(week.compareTo(Week.key(city.started()))<0&&!city.weeks().containsKey(week)){tell(p,"Учёт за эту неделю ещё не вёлся.");return;}var report=city.weeks().getOrDefault(week,Week.empty());var income=new ArrayList<String>();income.add("Всего: "+Money.format(report.totalIncome()));report.income().forEach((key,n)->income.add(source(key)+": "+Money.format(n)));var expense=new ArrayList<String>();expense.add("Всего: "+Money.format(report.totalExpense()));report.expenses().forEach((key,n)->expense.add(source(key)+": "+Money.format(n)));for(var b:Budget.values())expense.add(b.title()+": "+Money.format(report.categories().get(b)));
            button(view,10,Material.EMERALD,"&aДоходы",income,null);button(view,12,Material.REDSTONE,"&cРасходы",expense,null);button(view,14,Material.GOLD_NUGGET,"&eНалоги",List.of("Поступило: "+Money.format(report.income().getOrDefault("tax",0L)),"Уплачено: "+Money.format(report.expenses().getOrDefault("tax",0L)),"Уже включены в общие денежные итоги."),null);button(view,16,Material.COMPARATOR,"&eСальдо недели",List.of("Доходы − расходы + возвраты: "+Money.format(report.totalIncome()-report.totalExpense()+report.refunds()),"Возвраты расходов: "+Money.format(report.refunds()),"Внешние корректировки: "+Money.format(report.adjustments()),"Корректировки не объявляются доходом или налогом.","Учёт начат: "+java.time.Instant.ofEpochMilli(city.started()).toString(),"Резервы караванов/заказов считаются расходом денег."),null);
            var production=new ArrayList<String>();if(!report.productionKnown())production.add("Нет подтверждённых данных Resources за неделю.");else{production.add("Завершено циклов: "+report.production().getOrDefault("cycles",0L));if(report.production().getOrDefault("overflow",0L)>0)production.add("&eДостигнут числовой предел отчёта; значения — нижняя граница.");for(String key:List.of("wood","stone","metal","food","water","materials","knowledge","influence")){long in=report.production().getOrDefault("produced_"+key,0L),out=report.production().getOrDefault("consumed_"+key,0L);production.add(resource(key)+": +"+java.math.BigDecimal.valueOf(in,3).stripTrailingZeros().toPlainString()+" / −"+java.math.BigDecimal.valueOf(out,3).stripTrailingZeros().toPlainString());}production.add("Фактические циклы; прогнозы и ручная выдача исключены.");}
            button(view,31,Material.CRAFTING_TABLE,"&eПроизводство и потребление",production,null);button(view,40,Material.PAPER,"&eЭкспорт CSV",List.of("/t treasury export "+week,"Файл сохраняется в каталоге плагина."),()->p.performCommand("town treasury export "+week));
        }else if(page.equals("history")){var list=new ArrayList<>(city.history());Collections.reverse(list);int slot=0;for(String line:list)button(view,slot++,Material.PAPER,"&eРешение бюджета",List.of(line),null);if(city.pending()!=null){var pending=city.pending();button(view,40,Material.REDSTONE_BLOCK,"&cНужна сверка списания",List.of("ID: "+pending.id(),"Статья: "+pending.category().title(),"Сумма: "+Money.format(pending.amount()),"Проверьте журнал Towny перед resolve."),null);}}
        else if(page.equals("confirm")){var offer=service.offer(p);if(offer==null||!offer.town().equals(town)){tell(p,"Подтверждение устарело.");return;}button(view,13,Material.BOOK,"&eПроверьте изменение",List.of(action(offer.action()),String.join(" → ",offer.args()),"Казна сейчас: "+Money.format(city.balance()),"Доли: "+city.shares().get(Budget.CONSTRUCTION)+" / "+city.shares().get(Budget.ARMY)+" / "+city.shares().get(Budget.INFRASTRUCTURE)+" / "+city.shares().get(Budget.SOCIAL),"Подтверждение действует 60 секунд.","При изменении казны потребуется повторный выбор."),null);button(view,31,Material.LIME_DYE,"&aПодтвердить",List.of(),()->{try{service.confirm(p);tell(p,"Бюджет обновлён.");open(p,town,null);}catch(Exception e){tell(p,"&c"+e.getMessage());}});}
        else {Budget b;try{b=Budget.parse(page);}catch(Exception e){tell(p,"Статья не найдена.");return;}button(view,13,Material.valueOf(b.icon()),"&e"+b.title(),List.of("Выделено: "+Money.format(city.funds().get(b)),"Изменить сумму: /t treasury transfer free "+b.id()+" <сумма>","Доли: /t treasury shares 40 20 25 15","Новые доли не перераспределяют уже выделенные деньги."),null);if(b!=Budget.FREE){button(view,29,Material.LIME_DYE,"&aВыделить 100",List.of("Из свободного остатка."),()->prepare(p,town,"transfer",List.of("free",b.id(),"100")));button(view,31,Material.EMERALD,"&aВыделить 1000",List.of("Из свободного остатка."),()->prepare(p,town,"transfer",List.of("free",b.id(),"1000")));button(view,33,Material.RED_DYE,"&eВернуть 100 в свободный остаток",List.of(),()->prepare(p,town,"transfer",List.of(b.id(),"free","100")));}}
        button(view,45,Material.ARROW,"&aОбзор казны",List.of(),()->open(p,town,null));button(view,49,Material.SPYGLASS,"&aОбновить",List.of(),()->open(p,town,page));if(Bukkit.getPluginManager().isPluginEnabled("NeverLandTownyPolicies"))button(view,53,Material.WRITABLE_BOOK,"&eГородские политики",List.of(),()->p.performCommand("town policies"));p.openInventory(view.inventory);
    }
    private static String action(String name){return switch(name){case "enable"->"Включение бюджетов";case "disable"->"Освобождение бюджетов";case "shares"->"Изменение долей новых поступлений";default->"Перевод между статьями";};}
    public void prepare(Player p,UUID town,String action,List<String> args){try{service.offer(p,town,action,args);open(p,town,"confirm");}catch(Exception e){tell(p,"&c"+e.getMessage());}}
    private void button(View view,int slot,Material icon,String name,List<String> lore,Runnable action){var item=new ItemStack(icon);var meta=item.getItemMeta();meta.setDisplayName(color(name));meta.setLore(lore.stream().map(s->color("&7"+s)).toList());item.setItemMeta(meta);view.inventory.setItem(slot,item);if(action!=null)view.actions.put(slot,action);}
    @EventHandler public void click(InventoryClickEvent e){if(!(e.getView().getTopInventory().getHolder() instanceof View view))return;e.setCancelled(true);if(!(e.getWhoClicked() instanceof Player p))return;if(!access(p,view.town)){p.closeInventory();return;}var action=view.actions.get(e.getRawSlot());if(action!=null)Bukkit.getScheduler().runTask(plugin,()->{if(p.isOnline()&&p.getOpenInventory().getTopInventory().getHolder()==view&&access(p,view.town))action.run();});}
    @EventHandler public void drag(InventoryDragEvent e){if(e.getView().getTopInventory().getHolder() instanceof View)e.setCancelled(true);}
}
