package ru.neverland.townypolicies;
import org.bukkit.*;
import org.bukkit.plugin.*;
import java.util.*;
import java.lang.reflect.*;
import java.nio.file.*;
import java.util.concurrent.atomic.AtomicBoolean;
import ru.neverland.integration.*;
import ru.neverland.townypolicies.api.*;
import ru.neverland.townypolicies.model.*;
import ru.neverland.townypolicies.service.PoliciesService;
import ru.neverland.townypolicies.data.PoliciesRepository;
import ru.neverland.townypolicies.config.PoliciesSettings;
import ru.neverland.townytaxes.api.NeverLandTownyTaxesApi;
import static ru.neverland.townypolicies.PoliciesSmoke.check;
public final class GateSmoke {
    @SuppressWarnings("unchecked")static <T>T proxy(Class<T> type,InvocationHandler h){return (T)Proxy.newProxyInstance(type.getClassLoader(),new Class<?>[]{type},h);}
    static Object fallback(Object p,Method m,Object[] a){return switch(m.getName()){case "hashCode"->System.identityHashCode(p);case "equals"->p==a[0];case "toString"->"fixture";default->m.getReturnType()==boolean.class?false:m.getReturnType()==int.class?0:null;};}
    static void run(PoliciesSettings settings)throws Exception{Map<String,Plugin> plugins=new HashMap<>();var services=new SimpleServicesManager();var enabled=new AtomicBoolean(true);var taxConfigured=new AtomicBoolean(true);var manager=proxy(PluginManager.class,(p,m,a)->switch(m.getName()){case "getPlugin"->plugins.get(a[0]);case "isPluginEnabled"->{var plugin=plugins.get(a[0]);yield plugin!=null&&plugin.isEnabled();}default->fallback(p,m,a);});var server=proxy(Server.class,(p,m,a)->switch(m.getName()){case "getPluginManager"->manager;case "getServicesManager"->services;case "isPrimaryThread"->true;default->fallback(p,m,a);});var field=Bukkit.class.getDeclaredField("server");field.setAccessible(true);Object old=field.get(null);field.set(null,server);var dir=Files.createTempDirectory("policy-gate");try{UUID town=UUID.randomUUID(),other=UUID.randomUUID(),actor=UUID.randomUUID();check(PoliciesAccess.production(town,"bakery")==1&&PoliciesAccess.importsAllowed(town,other,false),"absent optional module preserves prior behavior");var plugin=proxy(Plugin.class,(p,m,a)->m.getName().equals("isEnabled")?enabled.get():fallback(p,m,a));var dependency=proxy(Plugin.class,(p,m,a)->switch(m.getName()){case "isEnabled"->true;case "getDescription"->new PluginDescriptionFile("Fixture","99.0.0","fixture.Main");default->fallback(p,m,a);});for(String name:List.of("Policies","Builds","Resources","Population","Upkeep","Trade","Taxes"))plugins.put("NeverLandTowny"+name,name.equals("Policies")?plugin:dependency);services.register(NeverLandTownyTaxesApi.class,(NeverLandTownyTaxesApi)id->taxConfigured.get(),dependency,ServicePriority.Normal);
            var repo=new PoliciesRepository(dir.resolve("data.yml"));repo.load();var state=CityPolicies.empty();for(var pair:List.of(List.of("farmers","expanded"),List.of("taxes","low"),List.of("imports","nation"),List.of("mobilization","general"))){var g=settings.groups().get(pair.get(0));state=SelectionPolicy.choose(state,g,pair.get(1),100,0,state.revision(),actor,"Мэр",false,true);}repo.put(town,state);
            var api=new PoliciesService(plugin,repo,settings);Class<?> directory=Class.forName("ru.neverland.townypolicies.service.PoliciesService$Directory");var ctor=directory.getDeclaredConstructors()[0];ctor.setAccessible(true);var f=PoliciesService.class.getDeclaredField("directory");f.setAccessible(true);f.set(api,ctor.newInstance(Map.of(town,"Город",other,"Сосед"),Map.of(),Map.of()));services.register(TownyPoliciesApi.class,api,plugin,ServicePriority.Normal);
            check(Math.abs(PoliciesAccess.production(town,"bakery")-1.2155)<1e-9,"actual service composes 1.3 subsidy x1.1 protected market x.85 mobilization");check(PoliciesAccess.production(other,"bakery")==1&&PoliciesAccess.upkeep(town,"bakery")==1.5,"town isolation and real upkeep cost factor");check(PoliciesAccess.tax(town)==.75&&PoliciesAccess.effect(town,"happiness")==-3,"tax discount and full mobilization happiness aggregate");
            check(!PoliciesAccess.importsAllowed(town,other,false)&&PoliciesAccess.importsAllowed(town,other,true),"same-nation context evaluated fresh for each import");taxConfigured.set(false);check(PoliciesAccess.tax(town)==1&&PoliciesAccess.effect(town,"happiness")==-8,"no free tax-policy happiness without an active municipal levy");taxConfigured.set(true);plugins.remove("NeverLandTownyUpkeep");check(PoliciesAccess.production(town,"bakery")==1.1&&PoliciesAccess.upkeep(town,"bakery")==1,"missing cost provider suspends subsidy and military benefits/penalties together");plugins.put("NeverLandTownyUpkeep",dependency);
            var tariffs=settings.groups().get("tariffs");repo.put(town,SelectionPolicy.choose(repo.get(town),tariffs,"protective",101,0,repo.get(town).revision(),actor,"Мэр",false,true));check(PoliciesAccess.tariff(town,3,20)==10&&PoliciesAccess.tariff(town,3,7)==7&&PoliciesAccess.tariffManaged(town),"live tariff override honors configured Trade cap");check(PoliciesAccess.tariff(other,3,20)==3&&!PoliciesAccess.tariffManaged(other),"manual tariffs preserved for default city");
            enabled.set(false);check(PoliciesAccess.production(town,"bakery")==1&&!PoliciesAccess.importsAllowed(town,other,true),"disabled provider neutral effects / closed new imports");enabled.set(true);services.unregisterAll(plugin);check(!PoliciesAccess.importsAllowed(town,other,true),"missing API cannot bypass import restriction");
        }finally{field.set(null,old);try(var files=Files.walk(dir)){for(var p:files.sorted(Comparator.reverseOrder()).toList())Files.delete(p);}}System.out.println("GateSmoke OK: actual PoliciesService/Bukkit bridge, city isolation, costs, municipal levy readiness, current nation context, tariff cap and provider outages");}
}
