package ru.neverland.townypolicies;
import org.bukkit.configuration.file.YamlConfiguration;
import java.util.*;
import java.nio.file.*;
import java.io.*;
import ru.neverland.townypolicies.config.PoliciesSettings;
import ru.neverland.townypolicies.model.*;
import ru.neverland.townypolicies.data.PoliciesRepository;
import ru.neverland.integration.PolicyEffects;
public final class PoliciesSmoke {
    static void check(boolean b,String text){if(!b)throw new AssertionError(text);}
    interface Attempt{void run()throws Exception;}
    static void fails(Attempt a,String text)throws Exception{try{a.run();}catch(Exception expected){return;}throw new AssertionError(text);}
    static YamlConfiguration read(String name)throws Exception{var y=new YamlConfiguration();try(var in=PoliciesSmoke.class.getResourceAsStream("/"+name)){y.load(new InputStreamReader(Objects.requireNonNull(in),java.nio.charset.StandardCharsets.UTF_8));}return y;}
    public static void main(String[] args)throws Exception{var settings=PoliciesSettings.load(read("config.yml"),read("policies.yml"));check(settings.groups().size()==6&&settings.cooldownMillis()==86400000,"six groups and 24-hour separate cooldowns");Set<String> icons=new HashSet<>();for(var g:settings.groups().values()){check(icons.add(g.icon())&&g.name().matches(".*[А-Яа-яЁё].*"),"distinct Russian group icons/names");check(g.options().size()==3,"three modes each");for(var p:g.options().values())check(p.name().matches(".*[А-Яа-яЁё].*")&&!p.advantages().isEmpty()&&!p.disadvantages().isEmpty(),"localized modes with pros and cons");}
        var empty=CityPolicies.empty();var farmers=settings.groups().get("farmers");var industry=settings.groups().get("industry");long now=1_000_000;UUID actor=UUID.randomUUID();var chosen=SelectionPolicy.choose(empty,farmers,"expanded",now,settings.cooldownMillis(),0,actor,"Мэр",false,true);check(chosen.mode(farmers).equals("expanded")&&chosen.revision()==1,"single category choice");
        fails(()->SelectionPolicy.choose(chosen,farmers,"targeted",now+1,settings.cooldownMillis(),1,actor,"Мэр",false,true),"cooldown blocks switching");fails(()->SelectionPolicy.choose(chosen,industry,"focused",now,settings.cooldownMillis(),0,actor,"Мэр",false,true),"stale cross-category confirmation rejected");fails(()->SelectionPolicy.choose(empty,farmers,"expanded",now,0,0,actor,"Мэр",true,false),"admin cannot grant unsupported effects");
        var other=SelectionPolicy.choose(chosen,industry,"focused",now,settings.cooldownMillis(),1,actor,"Мэр",false,true);check(other.mode(farmers).equals("expanded")&&other.mode(industry).equals("focused"),"independent categories preserve previous choices");check(SelectionPolicy.choose(chosen,farmers,"none",chosen.next("farmers"),0,1,actor,"Мэр",false,true).mode(farmers).equals("none"),"cooldown boundary/reset");check(SelectionPolicy.choose(chosen,farmers,"none",now+1,0,1,actor,"Админ",true,true).mode(farmers).equals("none"),"explicit admin bypass");
        check(SelectionPolicy.manager(true,true,false)&&SelectionPolicy.manager(true,false,true)&&!SelectionPolicy.manager(false,true,true)&&!SelectionPolicy.manager(true,false,false),"mayor/delegate rights require own town; ordinary assistants not implicit");
        var history=empty;for(int i=0;i<45;i++)history=SelectionPolicy.choose(history,farmers,i%2==0?"expanded":"none",now+i,0,history.revision(),actor,"Мэр",false,true);check(history.history().size()==30&&history.revision()==45,"bounded durable history");
        for(String effect:List.of("production","upkeep","happiness")){var data=read("policies.yml");data.set("policies.farmers.options.expanded.effects."+effect,Double.NaN);fails(()->PoliciesSettings.load(read("config.yml"),data),"nonfinite effects rejected");}
        var noCost=read("policies.yml");noCost.set("policies.farmers.options.expanded.requires",List.of("NeverLandTownyResources"));fails(()->PoliciesSettings.load(read("config.yml"),noCost),"cost dependency cannot be omitted");var badDefault=read("policies.yml");badDefault.set("policies.farmers.options.none.effects.production",.2);fails(()->PoliciesSettings.load(read("config.yml"),badDefault),"default mode cannot carry hidden effects");var badTime=read("config.yml");badTime.set("selection.change-cooldown-hours",.5);fails(()->PoliciesSettings.load(badTime,read("policies.yml")),"fractional cooldown rejected");
        check(DependencyVersions.atLeast("0.1.10","0.1.9")&&DependencyVersions.atLeast("0.8.5-SNAPSHOT","0.8.5")&&!DependencyVersions.atLeast("0.8.4","0.8.5")&&!DependencyVersions.atLeast("unknown","0.1.2"),"dependency version gates prevent partial integrations");
        persistence(chosen,other);effects();GateSmoke.run(settings);System.out.println("PoliciesSmoke OK: 6 categories / 18 modes, own-city roles, independent cooldowns, stale confirmations, history, atomic persistence, production/army/trade bounds and real Bukkit integration");
    }
    private static void persistence(CityPolicies first,CityPolicies second)throws Exception{var dir=Files.createTempDirectory("policies-smoke");try{var path=dir.resolve("policies-data.yml");UUID a=UUID.randomUUID(),b=UUID.randomUUID();var repo=new PoliciesRepository(path);fails(()->repo.put(a,first),"write before load");repo.load();repo.put(a,first);repo.put(b,second);var restart=new PoliciesRepository(path);restart.load();check(restart.towns().equals(repo.towns())&&restart.get(UUID.randomUUID()).equals(CityPolicies.empty()),"restart / UUID isolation");Files.delete(path);Files.createDirectory(path);Files.writeString(path.resolve("keep"),"keep");fails(()->restart.put(a,second),"atomic write failure");check(restart.get(a).equals(first),"failed write preserves authoritative choices");Files.delete(path.resolve("keep"));Files.delete(path);Files.writeString(path,"schema: 1\ntowns: [broken");var broken=new PoliciesRepository(path);fails(broken::load,"corrupt data rejected");fails(()->broken.put(a,second),"failed load cannot erase old data");check(Files.readString(path).contains("[broken"),"corrupt database preserved");}finally{try(var files=Files.walk(dir)){for(var p:files.sorted(Comparator.reverseOrder()).toList())Files.delete(p);}}}
    private static void effects(){UUID a=new UUID(0,1),b=new UUID(0,2),c=new UUID(0,3),town=UUID.randomUUID(),other=UUID.randomUUID(),nation=UUID.randomUUID();var roster=Map.of(a,town,b,town,c,town);check(PolicyEffects.capacity(10,.25)==12&&PolicyEffects.capacity(10,.5)==15,"actual military capacity rounding");check(PolicyEffects.rosterActive(roster,a,town,2)&&!PolicyEffects.rosterActive(roster,c,town,2)&&PolicyEffects.rosterActive(roster,c,town,3),"lower cap suspends excess roster with deterministic recovery");check(roster.size()==3&&!PolicyEffects.rosterActive(roster,a,other,3),"roster preserved / foreign town excluded");check(PolicyEffects.output(1000,1,.85,100000)==850&&PolicyEffects.output(1000,3,1.3,100000)==3000,"below-base penalty and joint cap");check(PolicyEffects.imports("nation",a,b,true)&&!PolicyEffects.imports("nation",a,b,false)&&!PolicyEffects.imports("closed",a,b,true),"nation imports require real shared membership");check(PolicyEffects.travel(100,-.1,0)==90&&PolicyEffects.travel(100,-.1,-.1)==81,"endpoint modifiers each apply once");check(PolicyEffects.tax(100,1.25)==125&&PolicyEffects.tax(100,.75)==75&&PolicyEffects.tax(100,1)==100,"municipal tax multiplier only");}
}
