package ru.neverland.townytaxes.service;

import com.palmergames.bukkit.towny.object.Nation;
import com.palmergames.bukkit.towny.object.Resident;
import com.palmergames.bukkit.towny.object.Town;
import com.palmergames.bukkit.towny.object.economy.Account;
import com.palmergames.bukkit.towny.object.economy.transaction.Transaction;
import org.bukkit.Bukkit;
import org.bukkit.plugin.java.JavaPlugin;
import org.bukkit.scheduler.BukkitTask;
import ru.neverland.townytaxes.api.NeverLandTownyTaxesApi;
import ru.neverland.townytaxes.data.CivicRepository;
import ru.neverland.townytaxes.integration.TownyHook;
import ru.neverland.townytaxes.model.*;

import java.text.DecimalFormat;
import java.util.*;

public final class FiscalService implements NeverLandTownyTaxesApi {
    private final JavaPlugin plugin; private final TownyHook towny; private final CivicRepository repository; private final MessageService messages;
    private final DecimalFormat money = new DecimalFormat("#,##0.00"); private final Map<UUID,Double> balanceSnapshots=new HashMap<>(); private BukkitTask task; private boolean internal;
    public FiscalService(JavaPlugin plugin,TownyHook towny,CivicRepository repository,MessageService messages){this.plugin=plugin;this.towny=towny;this.repository=repository;this.messages=messages;}
    public void start(){if(task!=null)task.cancel();long period=Math.max(20,plugin.getConfig().getLong("scheduler.check-seconds",20)*20);task=Bukkit.getScheduler().runTaskTimer(plugin,this::tick,period,period);}
    public void shutdown(){if(task!=null)task.cancel();task=null;repository.save();}
    public TaxPolicy createPolicy(TownyHook.Party target,Domain.TaxType type,double value,TownyHook.Party destination,long interval,String actor){
        long now=System.currentTimeMillis();TaxPolicy p=new TaxPolicy(UUID.randomUUID(),target.scope(),target.id(),target.name(),type,value,destination.scope(),destination.id(),destination.name(),interval,now+interval,true,actor);repository.put(p);saveCritical();return p;}
    public Sanction createSanction(TownyHook.Party target,TownyHook.Party issuer,Domain.SanctionEffect effect,double value,long expires,String reason,String actor){long now=System.currentTimeMillis();Sanction s=new Sanction(UUID.randomUUID(),target.scope(),target.id(),target.name(),issuer.scope(),issuer.id(),issuer.name(),effect,value,now,expires,reason,actor);repository.put(s);repository.log(new LedgerEntry(now,"SANCTION_ADD",target.scope(),target.id(),target.name(),value,reason,true));saveCritical();return s;}
    public Agreement createAgreement(TownyHook.Party first,TownyHook.Party second,Domain.AgreementType type,double value,long expires,String actor,boolean active){long now=System.currentTimeMillis();Agreement a=new Agreement(UUID.randomUUID(),first.scope(),first.id(),first.name(),second.scope(),second.id(),second.name(),type,value,now,expires,active?Domain.AgreementStatus.ACTIVE:Domain.AgreementStatus.PENDING,actor);repository.put(a);saveCritical();return a;}
    public boolean setAgreement(String id,Domain.AgreementStatus status){Agreement a=repository.agreement(id);if(a==null)return false;repository.put(a.status(status));saveCritical();return true;}
    public boolean removePolicy(String id){boolean ok=repository.removePolicy(id);if(ok)saveCritical();return ok;}public boolean removeSanction(String id){boolean ok=repository.removeSanction(id);if(ok)saveCritical();return ok;}
    public void collectNow(){tick();}
    private void tick(){scanExternalIncome();long now=System.currentTimeMillis();for(TaxPolicy p:new ArrayList<>(repository.policies()))if(p.enabled()&&p.type()==Domain.TaxType.FIXED&&now>=p.nextCollection()){collectFixed(p);repository.put(p.next(now+Math.max(60_000,p.intervalMillis())));}for(Agreement a:new ArrayList<>(repository.agreements()))if(a.status()==Domain.AgreementStatus.ACTIVE&&a.expiresAt()>0&&now>=a.expiresAt())repository.put(a.status(Domain.AgreementStatus.EXPIRED));repository.saveIfDirty();}
    private void collectFixed(TaxPolicy p){for(TownyHook.Party subject:subjects(p))charge(subject,p,p.value());}
    public void onTransaction(Transaction transaction){if(internal||transaction==null||!transaction.hasReceiverAccount()||transaction.getAmount()<=0||!plugin.getConfig().getBoolean("taxes.transaction-tax-enabled",true))return;Account account=transaction.getReceivingAccount();TownyHook.Party subject=party(account);if(subject==null)return;Domain.TaxType eventType=transaction.hasSenderAccount()?Domain.TaxType.TRANSACTION:Domain.TaxType.INCOME;applyPercentage(subject,eventType,transaction.getAmount());snapshot(subject);}
    private void scanExternalIncome(){for(Resident r:towny.residents()){if(r==null||r.isNPC())continue;Account account=r.getAccount();double current;try{current=account.getHoldingBalance();}catch(RuntimeException ignored){continue;}Double previous=balanceSnapshots.putIfAbsent(r.getUUID(),current);if(previous!=null&&current>previous+0.009){TownyHook.Party party=new TownyHook.Party(Domain.Scope.PLAYER,r.getUUID(),r.getName(),account);applyPercentage(party,Domain.TaxType.INCOME,current-previous);snapshot(party);}else balanceSnapshots.put(r.getUUID(),current);}}
    private void applyPercentage(TownyHook.Party subject,Domain.TaxType type,double base){for(TaxPolicy p:repository.policies())if(p.enabled()&&p.type()==type&&matches(p,subject))charge(subject,p,base*p.value()/100D);}
    private void charge(TownyHook.Party subject,TaxPolicy p,double raw){if(subject==null||subject.account()==null||raw<=0)return;TownyHook.Party destination=towny.resolve(p.destinationScope(),p.destinationId());double discount=taxDiscount(subject,destination);double amount=cents(raw*taxMultiplier(subject)*(1-discount));if(amount<=0)return;boolean withdrawn=false,paid=false;internal=true;try{withdrawn=subject.account().withdraw(amount,reason(p));if(withdrawn){paid=deposit(destination,amount);if(!paid)subject.account().deposit(amount,"Возврат неисполненного налога NeverLand");}}catch(RuntimeException e){paid=false;}finally{internal=false;}snapshot(subject);snapshot(destination);long now=System.currentTimeMillis();repository.log(new LedgerEntry(now,"TAX",subject.scope(),subject.id(),subject.name(),amount,p.shortId()+" → "+p.destinationName(),paid));if(!withdrawn&&plugin.getConfig().getBoolean("taxes.failed-payment-debt",true))repository.debt(subject.id(),repository.debt(subject.id())+amount);if(paid&&plugin.getConfig().getBoolean("messages.announce-collections",true)){Resident r=towny.resident(subject.id());if(r!=null&&r.getPlayer()!=null)messages.send(r.getPlayer(),"tax-collected",Map.of("amount",format(amount),"policy",p.shortId()));}}
    private boolean deposit(TownyHook.Party destination,double amount){if(destination==null||destination.scope()==Domain.Scope.GLOBAL){repository.addServerBank(amount);return true;}return destination.account()!=null&&destination.account().deposit(amount,"Налоговые поступления NeverLand");}
    public boolean payDebt(TownyHook.Party subject){double amount=repository.debt(subject.id());if(amount<=0||subject.account()==null)return false;internal=true;try{if(!subject.account().withdraw(amount,"Погашение налоговой задолженности"))return false;repository.addServerBank(amount);repository.debt(subject.id(),0);repository.log(new LedgerEntry(System.currentTimeMillis(),"DEBT_PAID",subject.scope(),subject.id(),subject.name(),amount,"Погашение задолженности",true));snapshot(subject);saveCritical();return true;}finally{internal=false;}}
    private List<TownyHook.Party> subjects(TaxPolicy p){List<TownyHook.Party> out=new ArrayList<>();switch(p.scope()){case PLAYER->{TownyHook.Party v=towny.resolve(Domain.Scope.PLAYER,p.targetId());if(v!=null)out.add(v);}case TOWN->{Town t=towny.town(p.targetId());if(t!=null)for(Resident r:towny.residents(t))if(eligible(r))out.add(new TownyHook.Party(Domain.Scope.PLAYER,r.getUUID(),r.getName(),r.getAccount()));}case NATION->{Nation n=towny.nation(p.targetId());if(n!=null)for(Town t:towny.towns(n))out.add(new TownyHook.Party(Domain.Scope.TOWN,t.getUUID(),t.getName(),t.getAccount()));}case GLOBAL->{for(Resident r:towny.residents())if(eligible(r))out.add(new TownyHook.Party(Domain.Scope.PLAYER,r.getUUID(),r.getName(),r.getAccount()));}}return out;}
    private boolean eligible(Resident r){if(r==null||r.isNPC())return false;if(!plugin.getConfig().getBoolean("taxes.process-offline-residents",true)&&r.getPlayer()==null)return false;long days=plugin.getConfig().getLong("taxes.inactive-resident-days",60);return days<=0||r.getPlayer()!=null||System.currentTimeMillis()-r.getLastOnline()<=days*86_400_000L;}
    private boolean matches(TaxPolicy p,TownyHook.Party s){if(p.scope()==Domain.Scope.GLOBAL)return true;if(p.scope()==s.scope()&&Objects.equals(p.targetId(),s.id()))return true;if(s.scope()==Domain.Scope.PLAYER){Resident r=towny.resident(s.id());Town t=r==null?null:r.getTownOrNull();if(p.scope()==Domain.Scope.TOWN)return t!=null&&p.targetId().equals(t.getUUID());Nation n=t==null?null:t.getNationOrNull();return p.scope()==Domain.Scope.NATION&&n!=null&&p.targetId().equals(n.getUUID());}if(s.scope()==Domain.Scope.TOWN&&p.scope()==Domain.Scope.NATION){Town t=towny.town(s.id());Nation n=t==null?null:t.getNationOrNull();return n!=null&&p.targetId().equals(n.getUUID());}return false;}
    private TownyHook.Party party(Account account){UUID id=account.getUUID();Resident r=towny.resident(id);if(r!=null)return new TownyHook.Party(Domain.Scope.PLAYER,id,r.getName(),account);Town t=towny.town(id);if(t!=null)return new TownyHook.Party(Domain.Scope.TOWN,id,t.getName(),account);Nation n=towny.nation(id);return n==null?null:new TownyHook.Party(Domain.Scope.NATION,id,n.getName(),account);}
    public boolean commandBlocked(Resident resident,String command){if(resident==null)return false;String lower=command.toLowerCase(Locale.ROOT);for(Sanction s:applicable(resident))if(s.effect()==Domain.SanctionEffect.COMMAND_BLOCK&&!relieved(s))for(String blocked:plugin.getConfig().getStringList("sanctions.default-blocked-commands"))if(lower.equals(blocked.toLowerCase(Locale.ROOT))||lower.startsWith(blocked.toLowerCase(Locale.ROOT)+" "))return true;return false;}
    public double taxMultiplier(TownyHook.Party party){double result=1;for(Sanction s:applicable(party))if(s.effect()==Domain.SanctionEffect.TAX_MULTIPLIER&&!relieved(s))result=Math.max(result,Math.max(1,s.value()));return Math.min(result,plugin.getConfig().getDouble("sanctions.maximum-tax-multiplier",5));}
    private double taxDiscount(TownyHook.Party a,TownyHook.Party b){if(a==null||b==null)return 0;double best=0;long now=System.currentTimeMillis();for(Agreement x:repository.agreements())if(x.active(now)&&x.type()==Domain.AgreementType.TAX_EXEMPTION&&x.pair(a.scope(),a.id(),b.scope(),b.id()))best=Math.max(best,x.value()/100D);return Math.min(1,best);}
    private List<Sanction> applicable(Resident r){List<Sanction>out=new ArrayList<>();Town t=r.getTownOrNull();Nation n=t==null?null:t.getNationOrNull();for(Sanction s:repository.sanctions())if(s.active(System.currentTimeMillis())&&(s.targetScope()==Domain.Scope.GLOBAL||(s.targetScope()==Domain.Scope.PLAYER&&s.targetId().equals(r.getUUID()))||(t!=null&&s.targetScope()==Domain.Scope.TOWN&&s.targetId().equals(t.getUUID()))||(n!=null&&s.targetScope()==Domain.Scope.NATION&&s.targetId().equals(n.getUUID()))))out.add(s);return out;}
    private List<Sanction> applicable(TownyHook.Party p){if(p.scope()==Domain.Scope.PLAYER){Resident r=towny.resident(p.id());return r==null?List.of():applicable(r);}List<Sanction>out=new ArrayList<>();Town t=p.scope()==Domain.Scope.TOWN?towny.town(p.id()):null;Nation n=p.scope()==Domain.Scope.NATION?towny.nation(p.id()):t==null?null:t.getNationOrNull();for(Sanction s:repository.sanctions())if(s.active(System.currentTimeMillis())&&(s.targetScope()==Domain.Scope.GLOBAL||(s.targetScope()==p.scope()&&s.targetId().equals(p.id()))||(n!=null&&s.targetScope()==Domain.Scope.NATION&&s.targetId().equals(n.getUUID()))))out.add(s);return out;}
    private boolean relieved(Sanction s){long now=System.currentTimeMillis();for(Agreement a:repository.agreements())if(a.active(now)&&a.type()==Domain.AgreementType.SANCTION_RELIEF&&a.pair(s.issuerScope(),s.issuerId(),s.targetScope(),s.targetId()))return true;return false;}
    @Override public boolean isTradeBlocked(UUID firstTown,UUID secondTown){Town a=towny.town(firstTown),b=towny.town(secondTown);if(a==null||b==null)return false;for(Sanction s:repository.sanctions())if(s.active(System.currentTimeMillis())&&s.effect()==Domain.SanctionEffect.TRADE_BLOCK&&!relieved(s)&&(targetsTown(s,a)||targetsTown(s,b)))return true;return false;}
    @Override public double tradePreferenceMultiplier(UUID firstTown,UUID secondTown){double discount=0;long now=System.currentTimeMillis();for(Agreement a:repository.agreements())if(a.active(now)&&a.type()==Domain.AgreementType.TRADE_PREFERENCE&&a.pair(Domain.Scope.TOWN,firstTown,Domain.Scope.TOWN,secondTown))discount=Math.max(discount,a.value());return Math.max(0,1-Math.min(plugin.getConfig().getDouble("agreements.maximum-trade-discount-percent",50),discount)/100D);}
    private boolean targetsTown(Sanction s,Town t){if(s.targetScope()==Domain.Scope.TOWN)return s.targetId().equals(t.getUUID());Nation n=t.getNationOrNull();return s.targetScope()==Domain.Scope.NATION&&n!=null&&s.targetId().equals(n.getUUID());}
    @Override public double taxDebt(UUID id){return repository.debt(id);}@Override public double serverReserve(){return repository.serverBank();}
    public boolean validTaxValue(Domain.TaxType type,double value){double max=type==Domain.TaxType.FIXED?plugin.getConfig().getDouble("taxes.maximum-fixed",1_000_000):plugin.getConfig().getDouble("taxes.maximum-percent",50);return Double.isFinite(value)&&value>=0&&value<=max;}
    public long intervalMillis(long minutes){return Math.max(plugin.getConfig().getLong("taxes.minimum-interval-minutes",10),minutes)*60_000L;}
    public CivicRepository repository(){return repository;}public String format(double v){return money.format(v);}private double cents(double v){return Math.round(v*100D)/100D;}private String reason(TaxPolicy p){return plugin.getConfig().getString("taxes.reason","Налог NeverLand: %policy%").replace("%policy%",p.shortId());}private void saveCritical(){if(plugin.getConfig().getBoolean("storage.save-after-critical-operation",true))repository.save();}
    private void snapshot(TownyHook.Party party){if(party!=null&&party.scope()==Domain.Scope.PLAYER&&party.account()!=null)try{balanceSnapshots.put(party.id(),party.account().getHoldingBalance());}catch(RuntimeException ignored){}}
}
