package ru.neverland.townyjustice;
import java.util.*;
import java.math.BigDecimal;
import org.bukkit.*;
import org.bukkit.entity.Player;
import org.bukkit.event.*;
import org.bukkit.event.inventory.*;
import org.bukkit.inventory.*;
import org.bukkit.plugin.java.JavaPlugin;
import com.palmergames.bukkit.towny.TownyAPI;
import ru.neverland.core.MenuStyle;
public final class JusticeMenu implements Listener {
    private final JavaPlugin plugin;private final JusticeService service;
    private record Holder(UUID viewer,String mode,int page,UUID detail,Map<Integer,UUID> cases,Inventory back)implements InventoryHolder{public Inventory getInventory(){return null;}}
    public JusticeMenu(JavaPlugin p,JusticeService s){plugin=p;service=s;}
    static String money(long cents){return BigDecimal.valueOf(cents,2).toPlainString();}
    static String phase(JusticeCase.Phase p){return switch(p){case OPEN->"Ожидает оплаты";case PAYING->"Платёж обрабатывается";case PAID->"Штраф оплачен";case FUNDING->"Резерв награды обрабатывается";case WANTED->"В розыске";case ARRESTING->"Доставка в тюрьму";case JAILED->"Заключён";case RELEASING->"Освобождение";case RELEASED->"Освобождён";case REFUNDING->"Возврат награды городу";case CANCELLED->"Отменено";};}
    private static String resident(UUID id){var r=TownyAPI.getInstance().getResident(id);return r==null?id.toString().substring(0,8):r.getName();}
    private static String town(UUID id){var t=TownyAPI.getInstance().getTown(id);return t==null?"Город удалён":t.getName();}
    private ItemStack item(Material icon,String name,String... lore){var stack=new ItemStack(icon);var meta=stack.getItemMeta();meta.displayName(MenuStyle.nameComponent(MenuStyle.decode(name)));meta.lore(MenuStyle.loreComponents(Arrays.stream(lore).map(MenuStyle::decode).toList()));stack.setItemMeta(meta);return stack;}
    private void use(Player p){if(!p.hasPermission("neverlandtownyjustice.use"))throw new IllegalArgumentException("Недостаточно прав");}
    private List<JusticeCase> rows(Player p,String mode){use(p);UUID town=mode.equals("cases")?service.ownTown(p).getUUID():null;if(town!=null&&!service.manager(p,town))throw new IllegalArgumentException("Дела города доступны мэру и суду");long now=System.currentTimeMillis();return service.repository().state().cases().values().stream().filter(c->switch(mode){case "fines"->c.kind()==JusticeCase.Kind.FINE&&c.subject().equals(p.getUniqueId())&&!c.terminal();case "wanted"->c.kind()==JusticeCase.Kind.WARRANT&&c.phase()==JusticeCase.Phase.WANTED&&service.funded(c)&&now<c.due();case "cases"->c.town().equals(town);default->false;}).sorted(Comparator.comparingLong(JusticeCase::created).reversed().thenComparing(JusticeCase::id)).toList();}
    private void frame(Inventory inv){for(int slot=0;slot<54;slot++)if(slot<9||slot>=45)inv.setItem(slot,item(Material.GRAY_STAINED_GLASS_PANE," "));}
    public void open(Player p,String mode,int requested,Inventory back){use(p);var entries=mode.equals("menu")?List.<JusticeCase>of():rows(p,mode);int page=Math.max(0,Math.min(requested,Math.max(0,(entries.size()-1)/36)));var slots=new HashMap<Integer,UUID>();for(int i=page*36;i<Math.min(entries.size(),page*36+36);i++)slots.put(9+i-page*36,entries.get(i).id());var h=new Holder(p.getUniqueId(),mode,page,null,Map.copyOf(slots),back);var inv=MenuStyle.inventory(plugin,h,54,switch(mode){case "fines"->"Суд • Мои штрафы";case "wanted"->"Суд • Розыск";case "cases"->"Суд • Дела города";default->"Городской суд";});frame(inv);
        if(mode.equals("menu")){inv.setItem(20,item(Material.PAPER,"&eМои штрафы","&fПричины, суммы и состояние оплаты.","","&aНажмите, чтобы открыть"));inv.setItem(22,item(Material.CROSSBOW,"&6Розыск и награды","&fДействующие объявления городов.","&7Поимка возможна рядом с целью","&7и только в городе-инициаторе.","","&aНажмите, чтобы открыть"));try{var town=service.ownTown(p);if(service.manager(p,town.getUUID()))inv.setItem(24,item(Material.WRITABLE_BOOK,"&bДела города","&fШтрафы, заключённые и выплаты.","&7Управление: /justice help","","&aНажмите, чтобы открыть"));}catch(IllegalArgumentException ignored){}
            inv.setItem(31,item(Material.IRON_BARS,"&dГородские тюрьмы","&fЗаключение, залог и побег — по правилам Towny.","&7Мэр создаёт тюрьму на городском участке:","&b/justice prison create <имя>","&7Готовая тюрьма: /justice prison bind <имя>"));
        }else{slots.forEach((slot,id)->{var c=service.get(id);inv.setItem(slot,item(c.kind()==JusticeCase.Kind.FINE?Material.PAPER:Material.CROSSBOW,"&e"+resident(c.subject()),"&fГород: &b"+town(c.town()),"&f"+(c.kind()==JusticeCase.Kind.FINE?"Штраф: ":"Награда: ")+"&6"+money(c.amount()),"&f"+phase(c.phase()),"","&7"+c.reason(),"","&aОткрыть дело"));});if(entries.isEmpty())inv.setItem(22,item(Material.BOOK,"&aЗаписей нет"));if(page>0)inv.setItem(48,item(Material.ARROW,"&bПредыдущая страница"));if((page+1)*36<entries.size())inv.setItem(50,item(Material.ARROW,"&bСледующая страница"));}
        inv.setItem(45,item(Material.ARROW,back==null?"&fЗакрыть":"&fНазад"));inv.setItem(49,item(Material.CLOCK,"&bОбновить",service.healthy()?"&aСуд работает":"&cЗапись приостановлена",mode.equals("menu")?"":"&7Страница "+(page+1)));p.openInventory(inv);
    }
    public void detail(Player p,UUID id,Inventory back){use(p);var c=service.get(id);if(!service.readable(p,c))throw new IllegalArgumentException("Это дело недоступно");var h=new Holder(p.getUniqueId(),"detail",0,id,Map.of(),back);var inv=MenuStyle.inventory(plugin,h,54,"Суд • "+id.toString().substring(0,8));frame(inv);
        inv.setItem(13,item(Material.WRITABLE_BOOK,"&e"+(c.kind()==JusticeCase.Kind.FINE?"Штраф":"Розыск"),"&fИгрок: &b"+resident(c.subject()),"&fГород: &b"+town(c.town()),"&f"+(c.kind()==JusticeCase.Kind.FINE?"К оплате: ":"Награда: ")+"&6"+money(c.amount()),c.kind()==JusticeCase.Kind.WARRANT?"&fСрок: &e"+c.hours()+" ч":"&7Просрочка не списывает деньги автоматически.","","&f"+c.reason(),"","&b"+phase(c.phase()),"&7ID: "+c.id()));
        if(c.kind()==JusticeCase.Kind.FINE&&c.subject().equals(p.getUniqueId())&&c.phase()==JusticeCase.Phase.OPEN)inv.setItem(30,item(Material.GOLD_INGOT,"&aОплатить "+money(c.amount()),"&fСредства поступят в бюджет города.","","&eНажатие подтверждает оплату."));
        if(c.kind()==JusticeCase.Kind.WARRANT&&c.phase()==JusticeCase.Phase.WANTED&&p.hasPermission("neverlandtownyjustice.capture"))inv.setItem(30,item(Material.LEAD,"&6Задержать игрока","&fПодойдите к цели в городе-инициаторе.","&7Оба игрока должны быть в игре.","&7Награда — после доставки в камеру.","","&eНажатие начинает задержание."));
        inv.setItem(32,item(Material.CLOCK,"&bСостояние выплат",c.payment()==null?"&7Платёж не начат":"&fОсновной платёж: "+paymentStatus(service.repository().get(c.payment())),c.payout()==null?"&7Выплата резерва не начата":"&fРезерв: "+paymentStatus(service.repository().get(c.payout())),"","&7При спорном результате обратитесь","&7к администратору с ID дела."));inv.setItem(45,item(Material.ARROW,back==null?"&fЗакрыть":"&fНазад"));inv.setItem(49,item(Material.CLOCK,"&bОбновить"));p.openInventory(inv);
    }
    private String paymentStatus(JusticePayment p){return switch(p.step()){case READY,DEBITED->"Обрабатывается";case DEBIT_PENDING,CREDIT_PENDING->"Требуется сверка";case COMPLETE->"Завершён";case CANCELLED->"Не списано";};}
    @EventHandler public void click(InventoryClickEvent e){if(!(e.getView().getTopInventory().getHolder() instanceof Holder h))return;e.setCancelled(true);if(!(e.getWhoClicked() instanceof Player p)||!p.getUniqueId().equals(h.viewer()))return;int slot=e.getRawSlot();try{use(p);if(slot==45){MenuStyle.returnTo(p,h.back());return;}if(h.detail()!=null){if(slot==30){var c=service.get(h.detail());if(c.kind()==JusticeCase.Kind.FINE)service.pay(p,c.id());else service.capture(p,c.id());}if(slot==30||slot==49)detail(p,h.detail(),h.back());return;}
        if(h.mode().equals("menu")&&Set.of(20,22,24).contains(slot)){open(p,slot==20?"fines":slot==22?"wanted":"cases",0,e.getView().getTopInventory());return;}if(!h.mode().equals("menu"))rows(p,h.mode());if(h.cases().containsKey(slot))detail(p,h.cases().get(slot),e.getView().getTopInventory());else if(slot==48||slot==49||slot==50)open(p,h.mode(),h.page()+(slot==48?-1:slot==50?1:0),h.back());
    }catch(Exception ex){p.closeInventory();JusticeCommand.say(p,"&c"+(ex instanceof IllegalArgumentException?ex.getMessage():"Операция ожидает проверки; обратитесь к администратору"));if(!(ex instanceof IllegalArgumentException))plugin.getLogger().log(java.util.logging.Level.WARNING,"Меню суда",ex);}}
    @EventHandler public void drag(InventoryDragEvent e){if(e.getView().getTopInventory().getHolder() instanceof Holder)e.setCancelled(true);}
}
