package ru.neverland.townyjustice;
import java.math.BigDecimal;
import org.bukkit.configuration.ConfigurationSection;
public record JusticeSettings(long maximumFine,long maximumBounty,long fineDue,int jailHours,long warrantDuration,double captureDistance,long captureTimeout,long retry,int openLimit,int records,int prisons,long cooldown){
    public JusticeSettings{if(maximumFine<1||maximumFine>100000000000L||maximumBounty<1||maximumBounty>100000000000L||fineDue<86400000||fineDue>31536000000L||jailHours<1||jailHours>168||warrantDuration<86400000||warrantDuration>31536000000L||!Double.isFinite(captureDistance)||captureDistance<1||captureDistance>8||captureTimeout<10000||captureTimeout>600000||retry<1000||retry>3600000||openLimit<1||openLimit>1000||records<100||records>100000||prisons<1||prisons>100||cooldown<3600000||cooldown>2592000000L)throw new IllegalArgumentException("Неверные настройки суда");}
    public static long cents(String value){try{long n=new BigDecimal(value.replace(',','.')).movePointRight(2).longValueExact();if(n<0||n>100000000000L)throw new ArithmeticException();return n;}catch(RuntimeException e){throw new IllegalArgumentException("Сумма: от 0 до 1 миллиарда, не больше двух знаков после запятой");}}
    static long integer(ConfigurationSection c,String key){Object v=c.get(key);if(!(v instanceof Integer||v instanceof Long))throw new IllegalArgumentException("Нужно целое: "+key);return ((Number)v).longValue();}
    public static JusticeSettings load(ConfigurationSection c){Object distance=c.get("capture-distance");if(!(distance instanceof Number n))throw new IllegalArgumentException("Нужно число capture-distance");return new JusticeSettings(cents(String.valueOf(c.get("maximum-fine"))),cents(String.valueOf(c.get("maximum-bounty"))),Math.multiplyExact(integer(c,"fine-due-days"),86400000),Math.toIntExact(integer(c,"maximum-jail-hours")),Math.multiplyExact(integer(c,"warrant-days"),86400000),n.doubleValue(),Math.multiplyExact(integer(c,"capture-timeout-seconds"),1000),Math.multiplyExact(integer(c,"payment-retry-seconds"),1000),Math.toIntExact(integer(c,"maximum-open-cases-per-town")),Math.toIntExact(integer(c,"maximum-records")),Math.toIntExact(integer(c,"maximum-prisons-per-town")),Math.multiplyExact(integer(c,"recapture-cooldown-hours"),3600000));}
}
