package ru.neverland.townyjustice;
import java.util.*;
import org.bukkit.*;
import org.bukkit.entity.Player;
import org.bukkit.plugin.java.JavaPlugin;
import com.palmergames.bukkit.towny.*;
import com.palmergames.bukkit.towny.object.Town;
import ru.neverland.core.*;
import ru.neverland.townyjustice.api.*;
import static ru.neverland.townyjustice.JusticeCase.Phase.*;
import static ru.neverland.townyjustice.JusticePayment.Step.READY;
import static ru.neverland.townyjustice.JusticePayment.Step.DEBITED;
import static ru.neverland.townyjustice.JusticePayment.Step.COMPLETE;
public final class JusticeService implements TownyJusticeApi {
    private final JavaPlugin plugin;private final JusticeRepository repository;private final JusticeBank bank=new JusticeBank();private final JusticeJails jails=new JusticeJails();private JusticeSettings settings;private long warned;
    public JusticeService(JavaPlugin p,JusticeRepository r,JusticeSettings s){plugin=p;repository=r;settings=s;}
    public JusticeRepository repository(){return repository;}public JusticeSettings settings(){return settings;}
    public void reload(JusticeSettings s){ApiServices.primaryThread();settings=s;}
    private void writable(){ApiServices.primaryThread();if(!repository.writable())throw new IllegalStateException("Суд приостановлен после ошибки сохранения; требуется исправление и перезапуск");}
    public Town ownTown(Player p){var resident=TownyAPI.getInstance().getResident(p.getUniqueId());var town=resident==null?null:resident.getTownOrNull();if(town==null)throw new IllegalArgumentException("Вы не состоите в городе");return town;}
    public boolean manager(Player p,UUID town){if(p.hasPermission("neverlandtownyjustice.admin"))return true;var resident=TownyAPI.getInstance().getResident(p.getUniqueId());var city=TownyAPI.getInstance().getTown(town);return p.hasPermission("neverlandtownyjustice.manage")&&city!=null&&resident!=null&&resident.getTownOrNull()==city&&(city.getMayor()==resident||CouncilAccess.allows(p,town,"justice"));}
    private void manage(Player p,UUID town){writable();if(!manager(p,town))throw new IllegalArgumentException("Нужны полномочия мэра или суда своего города");}
    public boolean readable(Player p,JusticeCase c){return c.kind()==JusticeCase.Kind.WARRANT||c.subject().equals(p.getUniqueId())||manager(p,c.town());}
    public JusticeCase get(UUID id){var c=repository.state().cases().get(id);if(c==null)throw new IllegalArgumentException("Дело не найдено");return c;}
    private void room(UUID town){if(repository.state().cases().size()+repository.state().payments().size()+4>settings.records())throw new IllegalStateException("Реестр заполнен; новые дела приостановлены");if(repository.state().cases().values().stream().filter(c->c.town().equals(town)&&!c.terminal()).count()>=settings.openLimit())throw new IllegalArgumentException("Слишком много открытых дел города");}
    public boolean funded(JusticeCase c){return c.amount()==0||c.payment()!=null&&repository.get(c.payment()).step()==COMPLETE;}
    private JusticePayment payment(JusticeCase c,JusticePayment.Kind kind,UUID resident,long now){return new JusticePayment(UUID.randomUUID(),c.id(),c.town(),resident,kind,c.amount(),READY,now,0);}
    public UUID issue(Player actor,JusticeCase.Kind kind,UUID target,long amount,int hours,String reason)throws Exception{
        var town=ownTown(actor);manage(actor,town.getUUID());room(town.getUUID());if(TownyAPI.getInstance().getResident(target)==null)throw new IllegalArgumentException("Игрок не найден в Towny");long now=System.currentTimeMillis();
        if(kind==JusticeCase.Kind.FINE?(amount<1||amount>settings.maximumFine()||hours!=0):(amount<0||amount>settings.maximumBounty()||hours<1||hours>settings.jailHours()))throw new IllegalArgumentException("Сумма или срок превышает настройки суда");
        if(kind==JusticeCase.Kind.WARRANT){if(actor.getUniqueId().equals(target))throw new IllegalArgumentException("Нельзя объявить себя в розыск");if(repository.state().cases().values().stream().anyMatch(c->c.kind()==kind&&c.town().equals(town.getUUID())&&c.subject().equals(target)&&(!c.terminal()||c.capturedAt()>0&&now-c.capturedAt()<settings.cooldown())))throw new IllegalArgumentException("Розыск уже существует или ещё действует срок защиты от повторной награды");}
        var c=new JusticeCase(UUID.randomUUID(),town.getUUID(),target,actor.getUniqueId(),kind,amount,hours,reason,now,now+(kind==JusticeCase.Kind.FINE?settings.fineDue():settings.warrantDuration()),kind==JusticeCase.Kind.FINE?OPEN:amount==0?WANTED:FUNDING,null,null,null,null,0,0);JusticePayment tx=null;
        if(kind==JusticeCase.Kind.WARRANT&&amount>0){if(!ru.neverland.integration.TreasuryAccess.canSpend(town,"army",amount/100.0))throw new IllegalArgumentException("В военном бюджете недостаточно средств для награды");tx=payment(c,JusticePayment.Kind.BOUNTY_FUND,target,now);c=c.payment(tx.id(),FUNDING);}
        repository.put(c,tx);if(tx!=null)process(tx.id());notifyTarget(target,kind==JusticeCase.Kind.FINE?"Назначен штраф. /justice fines":"Объявлен розыск. /justice wanted");return c.id();
    }
    public void pay(Player payer,UUID id)throws Exception{writable();var c=get(id);if(!payer.hasPermission("neverlandtownyjustice.use")||c.kind()!=JusticeCase.Kind.FINE||!c.subject().equals(payer.getUniqueId()))throw new IllegalArgumentException("Можно оплатить только свой штраф");if(c.phase()==PAYING)return;if(repository.state().cases().size()+repository.state().payments().size()+1>settings.records())throw new IllegalStateException("Реестр платежей заполнен");if(c.phase()!=OPEN)throw new IllegalArgumentException("Штраф уже закрыт");if(TownyAPI.getInstance().getTown(c.town())==null)throw new IllegalArgumentException("Город больше не существует");var tx=payment(c,JusticePayment.Kind.FINE,c.subject(),System.currentTimeMillis());repository.put(c.payment(tx.id(),PAYING),tx);process(tx.id());}
    public void cancel(Player actor,UUID id)throws Exception{var c=get(id);manage(actor,c.town());if(c.kind()==JusticeCase.Kind.FINE){if(c.phase()!=OPEN)throw new IllegalArgumentException("Нельзя отменить закрытый или оплачиваемый штраф");repository.put(c.phase(CANCELLED),null);return;}if(c.phase()!=WANTED)throw new IllegalArgumentException("Отменить можно действующий розыск; заключённого освобождает release");refund(c);}
    private void refund(JusticeCase c)throws Exception{if(c.payout()!=null)throw new IllegalStateException("Резерв уже направлен на выплату");if(!funded(c))throw new IllegalStateException("Резерв ещё не подтверждён");JusticePayment tx=c.amount()==0?null:payment(c,JusticePayment.Kind.BOUNTY_REFUND,c.subject(),System.currentTimeMillis());repository.put(c.settlement(tx==null?null:tx.id(),tx==null?CANCELLED:REFUNDING),tx);}
    private static UUID territory(Player p){var town=TownyAPI.getInstance().getTown(p.getLocation());return town==null?null:town.getUUID();}
    private boolean playerReady(Player p){return p!=null&&p.isOnline()&&!p.isDead()&&!p.isInsideVehicle()&&(p.getGameMode()==GameMode.SURVIVAL||p.getGameMode()==GameMode.ADVENTURE);}
    private void captureAllowed(Player actor,Player target,JusticeCase c){var resident=target==null?null:TownyAPI.getInstance().getResident(target.getUniqueId());var hunter=TownyAPI.getInstance().getResident(actor.getUniqueId());boolean jailed=resident==null||resident.isJailed()||jails.queued(c);double distance=target!=null&&target.getWorld().equals(actor.getWorld())?target.getLocation().distance(actor.getLocation()):Double.POSITIVE_INFINITY;
        if(!actor.hasPermission("neverlandtownyjustice.capture")||hunter==null||hunter.isJailed()||!CaptureRules.allowed(actor.getUniqueId(),c.subject(),c.town(),territory(actor),target==null?null:territory(target),playerReady(actor),playerReady(target),jailed,funded(c),c.kind()==JusticeCase.Kind.WARRANT&&c.phase()==WANTED&&System.currentTimeMillis()<c.due(),distance,settings.captureDistance()))throw new IllegalArgumentException("Для поимки подойдите к разыскиваемому в пределах города-инициатора; нужен действующий оплаченный розыск");
        if(repository.state().cases().values().stream().anyMatch(other->!other.id().equals(c.id())&&other.subject().equals(c.subject())&&Set.of(ARRESTING,JAILED,RELEASING).contains(other.phase())))throw new IllegalArgumentException("Поимка этого игрока уже обрабатывается");
    }
    public void capture(Player hunter,UUID id)throws Exception{writable();var c=get(id);var target=Bukkit.getPlayer(c.subject());captureAllowed(hunter,target,c);var prison=repository.state().prisons().values().stream().filter(p->p.town().equals(c.town())&&jails.usable(p)!=null).sorted(Comparator.comparing(JusticePrison::name)).findFirst().orElseThrow(()->new IllegalArgumentException("У города нет доступной тюрьмы"));
        var event=new JusticeCaptureEvent(c.id(),c.town(),c.subject(),hunter.getUniqueId());Bukkit.getPluginManager().callEvent(event);if(event.isCancelled())throw new IllegalArgumentException("Поимка отменена правилами сервера");if(!get(id).equals(c))throw new IllegalArgumentException("Дело изменилось; повторите просмотр");captureAllowed(hunter,target,c);
        var intent=c.arrest(hunter.getUniqueId(),prison.id(),System.currentTimeMillis());repository.put(intent,null);jails.arrest(hunter,target,intent,prison);
    }
    public void release(Player actor,UUID id)throws Exception{var c=get(id);manage(actor,c.town());if(!Set.of(ARRESTING,JAILED).contains(c.phase()))throw new IllegalArgumentException("По этому делу нет заключённого");repository.put(c.phase(RELEASING),null);}
    public UUID createPrison(Player actor,String name,boolean bind)throws Exception{var town=ownTown(actor);manage(actor,town.getUUID());return createPrison(town.getUUID(),actor.getLocation(),name,bind);}
    /** Internal town-scoped operation; command layer authenticates the mayor or appointed court. */
    UUID createPrison(UUID town,Location point,String name,boolean bind)throws Exception{writable();if(repository.state().prisons().values().stream().filter(p->p.town().equals(town)).count()>=settings.prisons())throw new IllegalArgumentException("Достигнут предел тюрем");if(repository.state().prisons().values().stream().anyMatch(p->p.town().equals(town)&&p.name().equalsIgnoreCase(name)))throw new IllegalArgumentException("Название тюрьмы уже занято");var block=TownyAPI.getInstance().getTownBlock(point);UUID id=bind&&block!=null&&block.getJail()!=null?block.getJail().getUUID():UUID.randomUUID();if(bind&&(block==null||!block.isJail()||block.getJail()==null))throw new IllegalArgumentException("Встаньте на существующий тюремный участок Towny");
        if(repository.state().prisons().containsKey(id))throw new IllegalArgumentException("Тюрьма уже подключена");var p=new JusticePrison(id,town,point.getWorld().getUID(),point.getBlockX(),point.getBlockY(),point.getBlockZ(),name,false);jails.validateNew(p);repository.prison(p);jails.ensure(p);repository.prison(p.finish());return p.id();}
    public void unbind(Player actor,String name)throws Exception{var town=ownTown(actor);manage(actor,town.getUUID());var p=repository.state().prisons().values().stream().filter(v->v.town().equals(town.getUUID())&&v.name().equalsIgnoreCase(name)).findFirst().orElseThrow(()->new IllegalArgumentException("Тюрьма не найдена"));if(repository.state().cases().values().stream().anyMatch(c->p.id().equals(c.prison())&&Set.of(ARRESTING,JAILED,RELEASING).contains(c.phase())))throw new IllegalArgumentException("Сначала освободите заключённых по делам суда");var values=new HashMap<>(repository.state().prisons());values.remove(p.id());repository.commit(new JusticeRepository.State(repository.state().cases(),repository.state().payments(),values));}
    public void resolve(UUID id,String decision)throws Exception{writable();var tx=repository.get(id);if(tx==null)throw new IllegalArgumentException("Платёж не найден");repository.put(JusticePayments.resolve(tx,decision,System.currentTimeMillis()));process(id);}
    private void process(UUID id){for(int i=0;i<3;i++)try{JusticePayments.advance(id,System.currentTimeMillis(),settings.retry(),repository,bank);}catch(Exception ex){warn(ex);break;}try{project(get(repository.get(id).caseId()),System.currentTimeMillis());}catch(Exception ex){warn(ex);}}
    void pulse(){if(!repository.writable())return;long now=System.currentTimeMillis();
        for(var p:List.copyOf(repository.state().prisons().values()))if(!p.ready())try{jails.ensure(p);repository.prison(p.finish());}catch(Exception ex){warn(ex);}
        for(var tx:List.copyOf(repository.state().payments().values()))if(tx.step()==READY||tx.step()==DEBITED)try{JusticePayments.advance(tx.id(),now,settings.retry(),repository,bank);}catch(Exception ex){warn(ex);}
        for(var c:List.copyOf(repository.state().cases().values()))if(!c.terminal())try{project(c,now);}catch(Exception ex){warn(ex);}
    }
    private void project(JusticeCase c,long now)throws Exception{
        if(c.phase()==PAYING||c.phase()==FUNDING){var tx=repository.get(c.payment());if(tx.step()==COMPLETE)repository.put(c.phase(c.phase()==PAYING?PAID:WANTED),null);else if(tx.step()==JusticePayment.Step.CANCELLED)repository.put(c.kind()==JusticeCase.Kind.FINE?c.payment(null,OPEN):c.phase(CANCELLED),null);return;}
        if(c.phase()==REFUNDING){if(repository.get(c.payout()).step()==COMPLETE)repository.put(c.phase(CANCELLED),null);return;}
        if(c.phase()==WANTED&&(now>=c.due()||TownyAPI.getInstance().getTown(c.town())==null)){refund(c);return;}
        if(c.phase()==ARRESTING){var prison=repository.state().prisons().get(c.prison());if(jails.confirmed(c,prison)){JusticePayment tx=c.amount()==0?null:payment(c,JusticePayment.Kind.BOUNTY_PAY,c.hunter(),now);repository.put(c.captured(tx==null?null:tx.id(),now),tx);notifyTarget(c.hunter(),"Поимка подтверждена; награда направлена на выплату. /justice case "+c.id());}else if(now-c.captureStarted()>settings.captureTimeout()&&!jails.ownsCustody(c)&&!jails.queued(c))repository.put(c.retryCapture(),null);return;}
        if(c.phase()==JAILED&&!jails.ownsCustody(c)&&!jails.queued(c)){repository.put(c.phase(RELEASED),null);return;}
        if(c.phase()==RELEASING){if(jails.queued(c))return;jails.release(c);if(!jails.ownsCustody(c)){if(c.capturedAt()>0)repository.put(c.phase(RELEASED),null);else refund(c);}}
    }
    private void warn(Exception ex){long now=System.currentTimeMillis();if(now-warned>60000){warned=now;plugin.getLogger().log(java.util.logging.Level.WARNING,"Операция суда ожидает сверки или восстановления: "+ex.getMessage(),ex);}}
    private void notifyTarget(UUID id,String message){var p=Bukkit.getPlayer(id);if(p!=null)p.sendMessage(MenuStyle.decode("&e[Городской суд] &f"+message));}
    @Override public boolean healthy(){ApiServices.primaryThread();return repository.writable();}
    public Map<String,Object> snapshot(JusticeCase c){var values=new LinkedHashMap<String,Object>();values.put("id",c.id());values.put("town",c.town());values.put("subject",c.subject());values.put("issuer",c.issuer());values.put("kind",c.kind().name());values.put("amount",c.amount());values.put("hours",c.hours());values.put("reason",c.reason());values.put("created",c.created());values.put("due",c.due());values.put("phase",c.phase().name());values.put("payment",JusticeRepository.value(c.payment()));values.put("payout",JusticeRepository.value(c.payout()));values.put("hunter",JusticeRepository.value(c.hunter()));values.put("prison",JusticeRepository.value(c.prison()));values.put("capturedAt",c.capturedAt());return Map.copyOf(values);}
    @Override public Optional<Map<String,Object>> caseFile(UUID id){ApiServices.primaryThread();return Optional.ofNullable(repository.state().cases().get(Objects.requireNonNull(id))).map(this::snapshot);}
    @Override public Collection<Map<String,Object>> cases(UUID town){ApiServices.primaryThread();Objects.requireNonNull(town);return repository.state().cases().values().stream().filter(c->c.town().equals(town)).map(this::snapshot).toList();}
    @Override public Collection<Map<String,Object>> wanted(UUID subject){ApiServices.primaryThread();long now=System.currentTimeMillis();return repository.state().cases().values().stream().filter(c->c.kind()==JusticeCase.Kind.WARRANT&&c.phase()==WANTED&&funded(c)&&now<c.due()&&(subject==null||c.subject().equals(subject))).map(this::snapshot).toList();}
    @Override public Collection<Map<String,Object>> fines(UUID subject){ApiServices.primaryThread();Objects.requireNonNull(subject);return repository.state().cases().values().stream().filter(c->c.kind()==JusticeCase.Kind.FINE&&c.subject().equals(subject)&&Set.of(OPEN,PAYING).contains(c.phase())).map(this::snapshot).toList();}
    @Override public Collection<Map<String,Object>> prisons(UUID town){ApiServices.primaryThread();Objects.requireNonNull(town);return repository.state().prisons().values().stream().filter(p->p.town().equals(town)).map(p->Map.<String,Object>of("id",p.id(),"town",p.town(),"world",p.world(),"x",p.x(),"y",p.y(),"z",p.z(),"name",p.name(),"available",jails.usable(p)!=null)).toList();}
}
