package ru.neverland.townymarket;
import java.util.*;
import java.nio.file.*;
import java.io.IOException;
import static ru.neverland.townymarket.MarketData.*;
public final class MarketSmoke {
    static final UUID SELLER=UUID.randomUUID(),BUYER=UUID.randomUUID(),PLAYER=UUID.randomUUID(),LOT=UUID.randomUUID();static final long NOW=1_800_000_000_000L;
    static Order order(boolean city){return new Order(UUID.randomUUID(),LOT,SELLER,city?BUYER:PLAYER,PLAYER,city,500,400,NOW,Phase.PREPARED,NOW,"",false);}
    static final class Store implements MarketPayments.Store {
        Order value;Phase fail;boolean finishFail;Store(Order value){this.value=value;}
        public Order order(UUID id){return value;}public void put(Order o)throws Exception{if(o.phase()==fail||finishFail&&o.finalized())throw new IOException("full journal disk");value=o;}
    }
    static final class Gateway implements MarketPayments.Gateway {
        String receipt="MISSING",gate;long buyer=1_000_000,seller;int available=1000,destination,debits,credits,reserves;boolean refuse,creditRefuse,debitCrash,creditCrash,full,ackFail;
        public String ready(Order o){return gate;}public String reserve(Order o){if(!receipt.equals("MISSING"))return receipt;available-=o.amount();reserves++;return receipt="HELD";}
        public boolean debit(Order o){if(refuse)return false;buyer-=o.total();debits++;if(debitCrash)throw new IllegalStateException("unknown debit");return true;}
        public String deliver(Order o){if(!receipt.equals("HELD"))return receipt;if(full)return "FULL";destination+=o.amount();return receipt=o.city()?"DELIVERED":"PICKUP";}
        public boolean credit(Order o){if(creditRefuse)return false;seller+=o.total();credits++;if(creditCrash)throw new IllegalStateException("unknown credit");return true;}
        public String refund(Order o){if(receipt.equals("HELD")){available+=o.amount();receipt="RETURNED";}return receipt;}
        public String receipt(Order o){return receipt;}public void acknowledge(Order o)throws Exception{if(ackFail)throw new IOException("ack disk");receipt="MISSING";}
    }
    static void tick(Store s,Gateway g,long now)throws Exception{MarketPayments.advance(s.value.id(),now,10000,s,g);}static void finish(Store s,Gateway g,long now)throws Exception{for(int i=0;i<8;i++)tick(s,g,now);}
    public static void main(String[] args)throws Exception {
        prices();evidence();var s=new Store(order(true));var g=new Gateway();finish(s,g,NOW);check(s.value.finalized()&&g.destination==500&&g.buyer==800000&&g.seller==200000,"real city purchase conservation");finish(s,g,NOW+DAY);check(g.debits==1&&g.credits==1,"completed order cannot charge again");
        s=new Store(order(false));g=new Gateway();finish(s,g,NOW);check(s.value.phase()==Phase.COMPLETE&&!s.value.finalized()&&g.receipt.equals("PICKUP"),"personal delivery retained until explicit claim");g.receipt="CLAIMED";finish(s,g,NOW);check(s.value.finalized()&&g.credits==1,"personal claim acknowledgement never repeats money");
        s=new Store(order(true));g=new Gateway();g.gate="Импорт запрещён";finish(s,g,NOW);check(g.reserves==0&&g.debits==0&&s.value.phase()==Phase.CANCELLED,"policy/permission/stock readiness gates before money");
        s=new Store(order(true));g=new Gateway();finish(s,g,NOW+60000);check(g.debits==0&&s.value.phase()==Phase.CANCELLED,"old unpaid intent expires instead of charging days later");
        s=new Store(order(true));g=new Gateway();g.refuse=true;finish(s,g,NOW);check(g.available==1000&&g.destination==0&&g.debits==0,"refused debit returns held stock");
        s=new Store(order(true));g=new Gateway();s.fail=Phase.DEBIT_PENDING;Store ds=s;Gateway dg=g;failure(()->tick(ds,dg,NOW));check(g.debits==0&&s.value.phase()==Phase.PREPARED,"intent save must succeed before bank");s.fail=null;finish(s,g,NOW);check(g.reserves==1&&g.debits==1,"replayed held order is idempotent");
        s=new Store(order(true));g=new Gateway();g.debitCrash=true;Store us=s;Gateway ug=g;failure(()->tick(us,ug,NOW));finish(s,g,NOW+DAY);check(g.debits==1&&g.destination==0&&s.value.phase()==Phase.DEBIT_PENDING,"unknown debit pauses after restart");s.value=MarketPayments.resolve(s.value,"debit-paid",NOW);finish(s,g,NOW);check(g.debits==1&&g.destination==500&&g.credits==1,"verified paid debit resumes delivery");
        s=new Store(order(true));g=new Gateway();s.fail=Phase.PAID;Store ps=s;Gateway pg=g;failure(()->tick(ps,pg,NOW));s.fail=null;finish(s,g,NOW+DAY);check(g.debits==1&&s.value.phase()==Phase.DEBIT_PENDING,"post-debit write failure cannot cause duplicate charge");
        s=new Store(order(true));g=new Gateway();tick(s,g,NOW);g.full=true;tick(s,g,NOW);check(g.destination==0&&g.credits==0&&s.value.phase()==Phase.PAID,"full warehouse retains paid goods");g.full=false;finish(s,g,NOW+10000);check(g.destination==500&&g.debits==1,"delivery retry uses same purchase");
        s=new Store(order(true));g=new Gateway();tick(s,g,NOW);tick(s,g,NOW);g.creditCrash=true;Store cs=s;Gateway cg=g;failure(()->tick(cs,cg,NOW));finish(s,g,NOW+DAY);check(g.credits==1&&s.value.phase()==Phase.CREDIT_PENDING,"unknown credit cannot mint money");s.value=MarketPayments.resolve(s.value,"credit-paid",NOW);finish(s,g,NOW);check(s.value.finalized()&&g.credits==1,"verified credit completes once");
        s=new Store(order(true));g=new Gateway();tick(s,g,NOW);tick(s,g,NOW);s.fail=Phase.COMPLETE;Store fs=s;Gateway fg=g;failure(()->tick(fs,fg,NOW));s.fail=null;finish(s,g,NOW+DAY);check(g.credits==1&&s.value.phase()==Phase.CREDIT_PENDING,"post-credit disk failure stops");
        s=new Store(order(true));g=new Gateway();tick(s,g,NOW);tick(s,g,NOW);g.creditRefuse=true;tick(s,g,NOW);check(s.value.phase()==Phase.DELIVERED&&g.credits==0,"bank refusal can retry credit");g.creditRefuse=false;finish(s,g,NOW+10000);check(g.credits==1&&g.destination==500,"credit retry does not repeat delivery");
        s=new Store(order(true));g=new Gateway();for(int i=0;i<3;i++)tick(s,g,NOW);s.finishFail=true;Store as=s;Gateway ag=g;failure(()->tick(as,ag,NOW));s.finishFail=false;finish(s,g,NOW);check(g.credits==1&&s.value.finalized(),"crash after warehouse acknowledgement is safe");
        s=new Store(order(true));g=new Gateway();s.fail=Phase.DEBIT_PENDING;Store xs=s;Gateway xg=g;failure(()->tick(xs,xg,NOW));s.fail=null;g.gate="Продавец закрыл предложение";finish(s,g,NOW);check(g.available==1000&&g.debits==0,"closed listing returns previously reserved unpaid goods");
        var pending=order(true).phase(Phase.DEBIT_PENDING,NOW,"");check(MarketPayments.resolve(pending,"debit-unpaid",NOW).phase()==Phase.RETURNING,"unpaid reconciliation returns stock");failure(()->MarketPayments.resolve(pending,"credit-paid",NOW));
        failure(()->new Order(UUID.randomUUID(),LOT,SELLER,SELLER,PLAYER,true,500,400,NOW,Phase.PREPARED,NOW,"",false));
        for(String bad:List.of("0","-1","NaN","Infinity","1.001","1000000001"))failure(()->cents(bad));check(cents("4,00")==400,"exact cents");persistence();
        System.out.println("MarketSmoke OK: dynamic price bounds, demand age and buyer caps, account identity, local/city payments, consent lifetime, all bank/disk crash windows, retries and strict journal persistence");
    }
    static void prices(){long normal=MarketPrices.unit(400,512,512,512,5000,20000);check(normal==400,"balanced supply and demand equals reference");check(MarketPrices.unit(400,4096,0,512,5000,20000)==200,"price floor");check(MarketPrices.unit(400,0,10000,512,5000,20000)==800,"price ceiling");check(MarketPrices.unit(400,128,256,512,5000,20000)>MarketPrices.unit(400,1024,256,512,5000,20000),"real stock lowers price");
        UUID id=UUID.randomUUID();var rows=List.of(new Demand(id,"global","iron",BUYER,NOW,500),new Demand(id,"global","iron",BUYER,NOW,500),new Demand(UUID.randomUUID(),"global","iron",BUYER,NOW,500),new Demand(UUID.randomUUID(),"global","iron",SELLER,NOW,100),new Demand(UUID.randomUUID(),"local_x","iron",PLAYER,NOW,1000),new Demand(UUID.randomUUID(),"global","iron",PLAYER,NOW-DAY,200),new Demand(UUID.randomUUID(),"global","iron",PLAYER,NOW+1,200));
        check(MarketPrices.demand(rows,"global","iron",NOW,256)==356,"24-hour demand, scope, unique receipt and per-buyer cap");}
    static void evidence(){Object city=new Object(),server=new Object();var p=new PaymentEvidence(city,false,"[test]",200000);p.observe(server,false,2000,"[test]");p.observe(city,true,2000,"[test]");p.observe(city,false,2000,"other");p.observe(city,false,Double.NaN,"[test]");check(!p.observed(),"server account, direction, unrelated amount and token ignored");p.observe(city,false,2000,"[NLT|uuid|trade] [test]");check(p.result(false),"observed actual debit overrides false result after callback");var missing=new PaymentEvidence(city,true,"token",100);try{missing.result(true);throw new AssertionError("unknown success must stop");}catch(IllegalStateException expected){}check(!missing.result(false),"definite refusal");}
    static void persistence()throws Exception {Path dir=Files.createTempDirectory("market-ledger-");try{Path file=dir.resolve("market.yml");var repo=new MarketRepository(file);repo.load();var l=new Listing(LOT,SELLER,"AA==","Железный слиток","iron",Scope.GLOBAL,true,400,1000,NOW,ListingState.ACTIVE,"Выставлен");repo.put(l);var o=order(true);repo.put(o,NOW);repo.put(o.phase(Phase.COMPLETE,NOW,""),NOW);repo.put(o.phase(Phase.COMPLETE,NOW,"").finish(),NOW);check(repo.demand().size()==1,"completion and demand counted atomically once");var loaded=new MarketRepository(file);loaded.load();check(loaded.listing(LOT).equals(l)&&loaded.order(o.id()).finalized()&&loaded.demand().size()==1,"actual YAML reload preserves all journal state");
        Files.writeString(file,"schema: 1\nlistings: {}\norders: broken\ndemand: {}\n");failure(loaded::load);failure(()->loaded.put(l));check(Files.readString(file).contains("broken"),"corrupt journal is not replaced with empty data");
        Path blocked=dir.resolve("blocked");Files.createDirectory(blocked);Files.writeString(blocked.resolve("keep"),"original");failure(()->MarketRepository.atomic(new org.bukkit.configuration.file.YamlConfiguration(),blocked));check(Files.readString(blocked.resolve("keep")).equals("original"),"atomic replacement failure preserves prior file");
    }finally{try(var paths=Files.walk(dir)){for(var p:paths.sorted(Comparator.reverseOrder()).toList())Files.delete(p);}}}
    interface Action{void run()throws Exception;}static void failure(Action a)throws Exception{boolean failed=false;try{a.run();}catch(Exception ex){failed=true;}check(failed,"expected rejection");}static void check(boolean value,String text){if(!value)throw new AssertionError(text);}
}
