name: NeverLandTownyPopulation
version: '0.1.7'
main: ru.neverland.townypopulation.NeverLandTownyPopulation
api-version: '26.2'
authors: [Alexander Sokolov]
description: Население города, жильё, занятость, довольство и снабжение.
depend: [Towny, NeverLandTownyBuilds]
softdepend: [PlaceholderAPI, NeverLandTownyDistricts]
commands:
  townypopulation:
    description: Население города
    usage: /townypopulation [info|buildings|reload|set]
    aliases: [population, nltpopulation]
permissions:
  neverlandtownypopulation.use:
    default: true
  neverlandtownypopulation.admin:
    default: op
