#!/usr/bin/env python3
"""Generate bundled vanilla labels from Mojang's verified 26.2 ru_ru language asset."""
import argparse
import hashlib
import json
from pathlib import Path

SOURCE_SHA1 = "6efaa4396b51eae6de896704c442cd8002b1a66c"
SOURCE_URL = "https://resources.download.minecraft.net/6e/" + SOURCE_SHA1
ROOT = Path(__file__).resolve().parents[1]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("language", type=Path, help="Downloaded Minecraft 26.2 ru_ru.json")
    args = parser.parse_args()
    data = args.language.read_bytes()
    if hashlib.sha1(data).hexdigest() != SOURCE_SHA1:
        raise SystemExit("Language asset hash differs from the recorded Minecraft 26.2 source")
    lang = json.loads(data)
    names = {}
    for prefix in ("entity.minecraft.", "block.minecraft.", "item.minecraft."):
        for key, value in lang.items():
            if key.startswith(prefix) and "." not in key[len(prefix):]:
                names[key[len(prefix):].upper()] = value
    for key, value in list(names.items()):
        if key.endswith("_BANNER") and not key.endswith("_WALL_BANNER"):
            names[key[:-7] + "_WALL_BANNER"] = value
    names["ANY"] = "Любая подходящая цель"
    output = ROOT / "shared/localization/src/main/resources/neverland-localization/materials-ru.properties"
    output.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# Minecraft Java 26.2 Russian material and entity names", "# " + SOURCE_URL,
             "# SHA-1: " + SOURCE_SHA1, "# Generated by scripts/generate_material_labels.py"]
    for key, value in sorted(names.items()):
        escaped = value.replace("\\", "\\\\").replace("\n", "\\n").replace("\r", "\\r")
        lines.append(key + "=" + escaped)
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Generated {len(names)} labels: {output.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
