package ru.neverland.townytreasury.service;
import java.nio.file.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import ru.neverland.townytreasury.model.*;
public final class ReportExporter {
    private ReportExporter(){}
    private static String cell(String value){if(value.matches("^[=+@-].*"))value="'"+value;return "\""+value.replace("\"","\"\"")+"\"";}
    public static Path write(Path folder,UUID town,String name,String week,CityLedger city)throws Exception{Week.validateKey(week);var report=city.weeks().get(week);if(report==null)throw new IllegalArgumentException("Нет записей за эту неделю");var lines=new ArrayList<String>();lines.add("Раздел;Показатель;Значение");lines.add("Город;Название;"+cell(name));lines.add("Период;Начало недели UTC;"+week);lines.add("Период;Начало учёта;"+java.time.Instant.ofEpochMilli(city.started()));report.income().forEach((key,n)->lines.add("Доходы;"+cell(Ui.source(key))+";"+Money.format(n)));report.expenses().forEach((key,n)->lines.add("Расходы;"+cell(Ui.source(key))+";"+Money.format(n)));for(var b:Budget.values())lines.add("Расходы по статьям;"+cell(b.title())+";"+Money.format(report.categories().get(b)));lines.add("Возвраты;Возврат расходов;"+Money.format(report.refunds()));lines.add("Сверка;Внешние корректировки;"+Money.format(report.adjustments()));lines.add("Производство;Подтверждено;"+(report.productionKnown()?"Да":"Нет данных"));report.production().entrySet().stream().sorted(Map.Entry.comparingByKey()).forEach(e->{String key=e.getKey();String title=key.equals("overflow")?"Достигнут числовой предел":key.equals("cycles")?"Завершённых циклов":(key.startsWith("produced_")?"Произведено: ":"Потреблено: ")+Ui.resource(key.substring(key.indexOf('_')+1));lines.add("Производство;"+cell(title)+";"+((key.equals("cycles")||key.equals("overflow"))?e.getValue().toString():java.math.BigDecimal.valueOf(e.getValue(),3).toPlainString()));});Path dir=folder.resolve(town.toString());Files.createDirectories(dir);Path target=dir.resolve(week+".csv"),tmp=Files.createTempFile(dir,"report-",".tmp");try{Files.writeString(tmp,"\uFEFF"+String.join("\n",lines)+"\n",StandardCharsets.UTF_8);Files.move(tmp,target,StandardCopyOption.REPLACE_EXISTING);}finally{Files.deleteIfExists(tmp);}return target;}
}
