name: NeverLandCrimeRuntimeProbe
version: 0.29.0
main: ru.neverland.runtime.CrimeRuntimeProbe
api-version: '26.2'
depend:
- Towny
- NeverLandTownyArchaeology
- NeverLandTownyBuilds
- NeverLandTownyCamps
- NeverLandTownyChronicles
- NeverLandTownyCitizens
- NeverLandTownyCompanies
- NeverLandTownyContracts
- NeverLandTownyCouncil
- NeverLandTownyDiplomacy
- NeverLandTownyDistricts
- NeverLandTownyElections
- NeverLandTownyEspionage
- NeverLandTownyEvents
- NeverLandTownyExpeditions
- NeverLandTownyGovernance
- NeverLandTownyIdeologies
- NeverLandTownyJobs
- NeverLandTownyLogistics
- NeverLandTownyMarket
- NeverLandTownyPolicies
- NeverLandTownyPopulation
- NeverLandTownyPower
- NeverLandTownyReputation
- NeverLandTownyResearch
- NeverLandTownyResources
- NeverLandTownySpecialization
- NeverLandTownyStick
- NeverLandTownyTaxes
- NeverLandTownyTrade
- NeverLandTownyTreasuryPlus
- NeverLandTownyUpkeep
- NeverLandTownyCrime
