package ru.neverland.townyarmy;
import java.util.*;import static ru.neverland.townyarmy.ArmyModel.*;
/** Deterministic strength and staffing calculations; live eligibility is supplied by the server adapter. */
public final class ArmyRules {
    private ArmyRules(){}
    public record Result(Set<UUID> active,Map<Unit,Integer> capacity,Map<Unit,Integer> count,int totalCapacity,double score,double readiness,double defense){public Result{active=Set.copyOf(active);capacity=Map.copyOf(capacity);count=Map.copyOf(count);}}
    public static int capacity(Unit unit,Map<String,Integer> levels,ArmySettings settings){var spec=settings.units().get(unit);if(spec.requirements().entrySet().stream().anyMatch(e->levels.getOrDefault(e.getKey(),0)<e.getValue()))return 0;return levels.getOrDefault(spec.capacityProject(),0)*spec.perLevel();}
    public static Result calculate(Collection<Soldier> roster,Set<UUID> eligible,Set<UUID> onDuty,Map<String,Integer> levels,boolean supplied,ArmySettings settings){int total=Math.max(0,levels.getOrDefault("army",0))*settings.hqCapacity();var capacity=new EnumMap<Unit,Integer>(Unit.class);var count=new EnumMap<Unit,Integer>(Unit.class);for(Unit unit:Unit.values()){capacity.put(unit,capacity(unit,levels,settings));count.put(unit,0);}var active=new LinkedHashSet<UUID>();double score=0,readiness=0;
        for(var s:roster.stream().sorted(Comparator.comparingLong(Soldier::joined).thenComparing(Soldier::resident)).toList()){if(!s.oath()||!s.serving()||!eligible.contains(s.resident())||s.status()!=Status.ACTIVE&&!onDuty.contains(s.resident())||active.size()>=total||count.get(s.unit())>=capacity.get(s.unit()))continue;active.add(s.resident());count.compute(s.unit(),(k,n)->n+1);double ready=s.equipment()/100.0*(supplied?1:.25);readiness+=ready*100;score+=settings.units().get(s.unit()).weight()*(.25+.75*s.training()/100.0)*ready;}
        return new Result(active,capacity,count,total,score,active.isEmpty()?0:readiness/active.size(),Math.min(settings.maximumDefense(),score/settings.scoreMaximum()*settings.maximumDefense()));
    }
    public static boolean canPromote(Soldier actor,Soldier target,Rank next,boolean executive,ArmySettings settings){if(!target.oath()||!target.serving()||next==Rank.GENERAL||next.ordinal()!=target.rank().ordinal()+1)return false;if(!executive&&(actor==null||!actor.serving()||!actor.oath()||!actor.town().equals(target.town())||actor.resident().equals(target.resident())||!actor.rank().atLeast(Rank.CAPTAIN)||actor.rank().ordinal()<=next.ordinal()))return false;var requirement=settings.ranks().get(next);return target.training()>=requirement.training()&&target.dutyMillis()/60000>=requirement.dutyMinutes();}
    public static Map<String,Long> upkeep(Collection<Soldier> roster,Set<UUID> active,ArmySettings settings){var sum=new HashMap<String,Long>();for(var s:roster)if(active.contains(s.resident()))settings.units().get(s.unit()).upkeep().forEach((k,n)->sum.merge(k,n,Math::addExact));return stock(sum);}
    public static boolean trainingComplete(long elapsed,double movement,boolean atBase,boolean eligible,ArmySettings s){return elapsed>=s.trainingDuration()&&Double.isFinite(movement)&&movement>=s.trainingMovement()&&atBase&&eligible;}
}
