package ru.neverland.townyarmy;
import java.util.*;import com.palmergames.bukkit.towny.TownyAPI;import ru.neverland.core.ApiServices;
/** Public contracts only. Missing optional citizenship keeps Towny membership rules; unavailable providers pause actions. */
public final class ArmyBridge implements ArmySupplies.Resources, ArmyMigration.Legacy {
    public Map<String,Integer> levels(UUID town,ArmySettings settings)throws Exception{var required=new HashSet<String>();required.add("army");settings.units().values().forEach(u->{required.add(u.capacityProject());required.addAll(u.requirements().keySet());});var out=new HashMap<String,Integer>();for(String project:required)out.put(project,((Number)ApiServices.call("NeverLandTownyBuilds","ru.neverland.townybuilds.api.TownyBuildsApi","operationalLevel",new Class<?>[]{UUID.class,String.class},town,project)).intValue());return Map.copyOf(out);}
    public OptionalInt age(UUID resident)throws Exception{return (OptionalInt)ApiServices.call("NeverLandTownyBuilds","ru.neverland.townybuilds.api.TownArmyApi","characterAge",new Class<?>[]{UUID.class},resident);}
    public boolean eligible(UUID town,UUID resident)throws Exception{var r=TownyAPI.getInstance().getResident(resident);if(r==null||r.getTownOrNull()==null||!town.equals(r.getTownOrNull().getUUID())||r.isJailed()||age(resident).orElse(-1)<18)return false;var api=ApiServices.connect("NeverLandTownyCitizens","ru.neverland.townycitizens.api.TownyCitizensApi",1,"healthy","allows");if(api.state()==ApiServices.State.NOT_INSTALLED)return true;if(!api.ready()||!Boolean.TRUE.equals(api.invoke("healthy",new Class<?>[]{})))throw new IllegalStateException("Гражданство временно недоступно");return Boolean.TRUE.equals(api.invoke("allows",new Class<?>[]{UUID.class,UUID.class,String.class},town,resident,"HOLD_OFFICE"));}
    @SuppressWarnings("unchecked") public Map<UUID,UUID> legacy()throws Exception{return Map.copyOf((Map<UUID,UUID>)ApiServices.call("NeverLandTownyBuilds","ru.neverland.townybuilds.api.TownArmyApi","legacyRoster",new Class<?>[]{}));}
    public void handoff(Map<UUID,UUID> expected)throws Exception{if(!Boolean.TRUE.equals(ApiServices.call("NeverLandTownyBuilds","ru.neverland.townybuilds.api.TownArmyApi","completeMigration",new Class<?>[]{Map.class},expected)))throw new IllegalStateException("Старый состав изменился до завершения переноса");}
    public void resourceReady(UUID town)throws Exception{var snapshot=((Optional<?>)ApiServices.call("NeverLandTownyResources","ru.neverland.townyresources.api.TownyResourcesApi","resources",new Class<?>[]{UUID.class},town)).orElseThrow(()->new IllegalStateException("Ресурсы города ещё не готовы"));if(!Boolean.FALSE.equals(snapshot.getClass().getMethod("paused").invoke(snapshot)))throw new IllegalStateException("Снабжение Resources приостановлено");}
    @Override public String status(UUID id)throws Exception{return (String)ApiServices.call("NeverLandTownyResources","ru.neverland.townyresources.api.TownyResourcesApi","reservationStatus",new Class<?>[]{UUID.class},id);}
    @Override public boolean reserve(UUID id,UUID town,Map<String,Long> amounts)throws Exception{return Boolean.TRUE.equals(ApiServices.call("NeverLandTownyResources","ru.neverland.townyresources.api.TownyResourcesApi","reserveResources",new Class<?>[]{UUID.class,UUID.class,Map.class},id,town,amounts));}
    @Override public void consume(UUID id)throws Exception{ApiServices.call("NeverLandTownyResources","ru.neverland.townyresources.api.TownyResourcesApi","settleResources",new Class<?>[]{UUID.class,boolean.class},id,true);}
    @Override public void forget(UUID id)throws Exception{ApiServices.call("NeverLandTownyResources","ru.neverland.townyresources.api.TownyResourcesApi","forgetReservation",new Class<?>[]{UUID.class},id);}
}
