package ru.neverland.townyarmy;
import java.util.*;import java.math.BigDecimal;import org.bukkit.Material;import org.bukkit.configuration.ConfigurationSection;
import static ru.neverland.townyarmy.ArmyModel.*;
public record ArmySettings(int hqCapacity,int reserveMultiplier,int records,int auditLimit,long maxTransfer,long supplyInterval,int shortageLoss,double maximumDefense,double scoreMaximum,double baseRadius,long dutyIdle,long trainingDuration,long trainingCooldown,int trainingGain,double trainingMovement,Map<String,Long> trainingCost,Map<Unit,UnitSpec> units,Map<Rank,RankSpec> ranks){
    public record UnitSpec(String title,Material icon,String capacityProject,int perLevel,Map<String,Integer> requirements,double weight,Map<String,Long> kit,Map<String,Long> upkeep){public UnitSpec{requirements=Map.copyOf(requirements);kit=stock(kit);upkeep=stock(upkeep);if(title==null||title.isBlank()||title.length()>48||icon==null||!capacityProject.matches("[a-z_]{2,64}")||perLevel<1||perLevel>1000||requirements.isEmpty()||requirements.entrySet().stream().anyMatch(e->!e.getKey().matches("[a-z_]{2,64}")||e.getValue()<1||e.getValue()>5)||!Double.isFinite(weight)||weight<.1||weight>10||kit.isEmpty()||upkeep.isEmpty())throw new IllegalArgumentException("Неверные настройки подразделения");}}
    public record RankSpec(String title,int training,long dutyMinutes){public RankSpec{if(title==null||title.isBlank()||title.length()>48||training<0||training>100||dutyMinutes<0||dutyMinutes>100000)throw new IllegalArgumentException("Неверные настройки звания");}}
    public ArmySettings{trainingCost=stock(trainingCost);units=Map.copyOf(units);ranks=Map.copyOf(ranks);if(hqCapacity<1||hqCapacity>1000||reserveMultiplier<1||reserveMultiplier>10||records<100||records>100000||auditLimit<100||auditLimit>10000||maxTransfer<1||maxTransfer>STOCK_LIMIT||supplyInterval<60000||supplyInterval>86400000||shortageLoss<1||shortageLoss>100||!Double.isFinite(maximumDefense)||maximumDefense<0||maximumDefense>.5||!Double.isFinite(scoreMaximum)||scoreMaximum<1||scoreMaximum>100000||!Double.isFinite(baseRadius)||baseRadius<4||baseRadius>128||dutyIdle<30000||dutyIdle>3600000||trainingDuration<10000||trainingDuration>3600000||trainingCooldown<60000||trainingCooldown>86400000||trainingGain<1||trainingGain>25||!Double.isFinite(trainingMovement)||trainingMovement<1||trainingMovement>1000||trainingCost.isEmpty()||units.size()!=Unit.values().length||ranks.size()!=Rank.values().length)throw new IllegalArgumentException("Неверные настройки армии");}
    public static long amount(String text){try{long value=new BigDecimal(text.replace(',','.')).movePointRight(3).longValueExact();if(value<0||value>STOCK_LIMIT)throw new ArithmeticException();return value;}catch(RuntimeException e){throw new IllegalArgumentException("Количество: положительное число, до трёх знаков после запятой");}}
    static long number(ConfigurationSection c,String key){Object value=c.get(key);if(!(value instanceof Integer||value instanceof Long))throw new IllegalArgumentException("Нужно целое: "+key);return ((Number)value).longValue();}
    static double decimal(ConfigurationSection c,String key){Object value=c.get(key);if(!(value instanceof Number n)||!Double.isFinite(n.doubleValue()))throw new IllegalArgumentException("Нужно число: "+key);return n.doubleValue();}
    static ConfigurationSection section(ConfigurationSection c,String key){var value=c.getConfigurationSection(key);if(value==null)throw new IllegalArgumentException("Нет раздела "+key);return value;}
    static Map<String,Long> cost(ConfigurationSection c){var out=new HashMap<String,Long>();for(String key:c.getKeys(false))out.put(key,amount(String.valueOf(c.get(key))));return stock(out);}
    public static ArmySettings load(ConfigurationSection c){var units=new EnumMap<Unit,UnitSpec>(Unit.class);for(Unit unit:Unit.values()){var u=section(c,"units."+unit.id());var required=section(u,"requirements");var levels=new HashMap<String,Integer>();for(String id:required.getKeys(false))levels.put(id,Math.toIntExact(number(required,id)));units.put(unit,new UnitSpec(u.getString("title"),Material.matchMaterial(u.getString("icon","")),u.getString("capacity-project",""),Math.toIntExact(number(u,"per-level")),levels,decimal(u,"weight"),cost(section(u,"kit")),cost(section(u,"upkeep"))));}
        var ranks=new EnumMap<Rank,RankSpec>(Rank.class);for(Rank rank:Rank.values()){var v=section(c,"ranks."+rank.id());ranks.put(rank,new RankSpec(v.getString("title"),Math.toIntExact(number(v,"training")),number(v,"duty-minutes")));}
        return new ArmySettings(Math.toIntExact(number(c,"headquarters-capacity-per-level")),Math.toIntExact(number(c,"reserve-capacity-multiplier")),Math.toIntExact(number(c,"maximum-records")),Math.toIntExact(number(c,"maximum-audit")),amount(String.valueOf(c.get("maximum-supply-transfer"))),Math.multiplyExact(number(c,"supply-interval-seconds"),1000),Math.toIntExact(number(c,"shortage-equipment-loss")),decimal(c,"maximum-defense-bonus"),decimal(c,"score-for-maximum-defense"),decimal(c,"base-radius"),Math.multiplyExact(number(c,"duty-idle-seconds"),1000),Math.multiplyExact(number(c,"training.seconds"),1000),Math.multiplyExact(number(c,"training.cooldown-seconds"),1000),Math.toIntExact(number(c,"training.gain")),decimal(c,"training.minimum-movement"),cost(section(c,"training.cost")),units,ranks);
    }
}
