package ru.neverland.townyarmy;
import java.util.*;import java.nio.file.*;import java.io.IOException;
import org.bukkit.configuration.ConfigurationSection;import org.bukkit.configuration.file.YamlConfiguration;
import ru.neverland.core.AtomicFiles;import static ru.neverland.townyarmy.ArmyModel.*;
/** Durable state publication. A supply credit and its applied receipt share one file replacement. */
public final class ArmyRepository implements ArmySupplies.Store {
    private final Path file;private State state=State.empty();private boolean loaded;private int auditLimit;
    public ArmyRepository(Path file,int limit){this.file=file;auditLimit=limit;}public State state(){return state;}public boolean writable(){return loaded&&AtomicFiles.writable(file);}public void auditLimit(int value){auditLimit=value;}
    public static final class Draft {
        public boolean imported,handoff;public final Map<UUID,UUID> legacy;public final Map<UUID,Soldier> soldiers;public final Map<UUID,City> cities;public final Map<UUID,Transfer> transfers;public final List<Audit> audit;
        Draft(State s){imported=s.imported();handoff=s.handoff();legacy=new HashMap<>(s.legacy());soldiers=new HashMap<>(s.soldiers());cities=new HashMap<>(s.cities());transfers=new HashMap<>(s.transfers());audit=new ArrayList<>(s.audit());}
        public void soldier(Soldier s){soldiers.put(s.resident(),s);cities.putIfAbsent(s.town(),City.empty(s.town()));}public City city(UUID town){return cities.computeIfAbsent(town,City::empty);}public State freeze(){return new State(imported,handoff,legacy,soldiers,cities,transfers,audit);}
    }
    public Draft draft(){return new Draft(state);}
    public void commit(Draft d,UUID town,UUID actor,UUID subject,String action,String reason,long now)throws IOException{d.audit.add(new Audit(UUID.randomUUID(),town,actor,subject,action,reason,now));while(d.audit.size()>auditLimit)d.audit.remove(0);commit(d.freeze());}
    @Override public Transfer transfer(UUID id){return state.transfers().get(id);}
    @Override public void phase(Transfer t)throws IOException{var d=draft();d.transfers.put(t.id(),t);commit(d.freeze());}
    @Override public void apply(UUID id)throws IOException{var t=transfer(id);if(t==null||t.phase()!=Phase.PLANNED)throw new IllegalStateException("Поставка уже учтена или не существует");var d=draft();d.cities.put(t.town(),d.city(t.town()).stock(add(d.city(t.town()).stock(),t.amounts())));d.transfers.put(id,t.phase(Phase.APPLIED));commit(d,t.town(),t.actor(),t.actor(),"SUPPLY_APPLIED","Принята поставка "+id,System.currentTimeMillis());}
    public void load()throws IOException{loaded=false;State next=State.empty();if(Files.exists(file))try{var y=new YamlConfiguration();y.load(file.toFile());if(n(y,"schema")!=1)throw new IOException("Неверная схема армии");var legacy=new HashMap<UUID,UUID>();var soldiers=new HashMap<UUID,Soldier>();var cities=new HashMap<UUID,City>();var transfers=new HashMap<UUID,Transfer>();var audit=new ArrayList<Audit>();var root=section(y,"legacy");for(String id:root.getKeys(false))legacy.put(UUID.fromString(id),UUID.fromString(text(root,id)));
        root=section(y,"cities");for(String id:root.getKeys(false)){var c=section(root,id);Base base=null;if(c.contains("base")){var p=section(c,"base");base=new Base(uuid(p,"world"),decimal(p,"x"),decimal(p,"y"),decimal(p,"z"));}UUID town=UUID.fromString(id);cities.put(town,new City(town,base,stock(section(c,"stock")),bool(c,"alert"),n(c,"next-supply"),n(c,"supplied-until")));}
        root=section(y,"soldiers");for(String id:root.getKeys(false)){var c=section(root,id);UUID resident=UUID.fromString(id);soldiers.put(resident,new Soldier(resident,uuid(c,"town"),Unit.valueOf(text(c,"unit")),Rank.valueOf(text(c,"rank")),Status.valueOf(text(c,"status")),bool(c,"oath"),Math.toIntExact(n(c,"training")),Math.toIntExact(n(c,"equipment")),n(c,"duty-millis"),n(c,"joined"),n(c,"last-training"),n(c,"last-promotion"),Math.toIntExact(n(c,"warnings")),n(c,"suspended-until")));}
        root=section(y,"transfers");for(String id:root.getKeys(false)){var c=section(root,id);UUID key=UUID.fromString(id);transfers.put(key,new Transfer(key,uuid(c,"town"),uuid(c,"actor"),stock(section(c,"amounts")),Phase.valueOf(text(c,"phase")),n(c,"created")));}
        root=section(y,"audit");for(String id:root.getKeys(false)){var c=section(root,id);audit.add(new Audit(UUID.fromString(id),uuid(c,"town"),uuid(c,"actor"),uuid(c,"subject"),text(c,"action"),text(c,"reason"),n(c,"time")));}
        next=new State(bool(y,"imported"),bool(y,"handoff"),legacy,soldiers,cities,transfers,audit);
    }catch(Exception e){throw new IOException("army-data.yml повреждён; данные не перезаписаны",e);}state=next;AtomicFiles.loaded(file);loaded=true;}
    public void commit(State next)throws IOException{if(!writable())throw new IOException("Запись армии приостановлена до восстановления базы");if(next.equals(state))return;AtomicFiles.write(file,()->encode(next));state=next;}
    static String encode(State s){var y=new YamlConfiguration();y.set("schema",1);y.set("imported",s.imported());y.set("handoff",s.handoff());for(String name:List.of("legacy","cities","soldiers","transfers","audit"))y.createSection(name);
        s.legacy().forEach((id,town)->y.set("legacy."+id,town.toString()));
        for(var c:s.cities().values()){var p=y.createSection("cities."+c.town());p.createSection("stock",c.stock());p.set("alert",c.alert());p.set("next-supply",c.nextSupply());p.set("supplied-until",c.suppliedUntil());if(c.base()!=null){var b=p.createSection("base");b.set("world",c.base().world().toString());b.set("x",c.base().x());b.set("y",c.base().y());b.set("z",c.base().z());}}
        for(var a:s.soldiers().values()){var p=y.createSection("soldiers."+a.resident());p.set("town",a.town().toString());p.set("unit",a.unit().name());p.set("rank",a.rank().name());p.set("status",a.status().name());p.set("oath",a.oath());p.set("training",a.training());p.set("equipment",a.equipment());p.set("duty-millis",a.dutyMillis());p.set("joined",a.joined());p.set("last-training",a.lastTraining());p.set("last-promotion",a.lastPromotion());p.set("warnings",a.warnings());p.set("suspended-until",a.suspendedUntil());}
        for(var a:s.transfers().values()){var p=y.createSection("transfers."+a.id());p.set("town",a.town().toString());p.set("actor",a.actor().toString());p.createSection("amounts",a.amounts());p.set("phase",a.phase().name());p.set("created",a.created());}
        for(var a:s.audit()){var p=y.createSection("audit."+a.id());p.set("town",a.town().toString());p.set("actor",a.actor().toString());p.set("subject",a.subject().toString());p.set("action",a.action());p.set("reason",a.reason());p.set("time",a.time());}return y.saveToString();
    }
    static ConfigurationSection section(ConfigurationSection c,String k)throws IOException{var value=c.getConfigurationSection(k);if(value==null)throw new IOException("Нет раздела "+k);return value;}static String text(ConfigurationSection c,String k)throws IOException{if(!c.isString(k))throw new IOException("Нужна строка "+k);return c.getString(k);}static UUID uuid(ConfigurationSection c,String k)throws IOException{return UUID.fromString(text(c,k));}static boolean bool(ConfigurationSection c,String k)throws IOException{if(!c.isBoolean(k))throw new IOException("Нужен флаг "+k);return c.getBoolean(k);}static long n(ConfigurationSection c,String k)throws IOException{Object value=c.get(k);if(!(value instanceof Integer||value instanceof Long))throw new IOException("Нужно целое "+k);return ((Number)value).longValue();}static double decimal(ConfigurationSection c,String k)throws IOException{Object v=c.get(k);if(!(v instanceof Number value)||!Double.isFinite(value.doubleValue()))throw new IOException("Нужно число "+k);return value.doubleValue();}static Map<String,Long> stock(ConfigurationSection c)throws IOException{var values=new HashMap<String,Long>();for(String key:c.getKeys(false))values.put(key,n(c,key));return ArmyModel.stock(values);}
}
