package ru.neverland.townybuilds.construction;
import org.bukkit.*;
import org.bukkit.block.BlockFace;
import org.bukkit.block.data.Bisected;
import org.bukkit.block.data.type.Door;
import java.util.*;
/** Seven distinct additive five-stage buildings with closed load-bearing walls and connected roofs. */
public final class SpecializationBlueprintGenerator {
    public static final Set<String> PROJECTS=Set.of("trade_exchange","citadel","seed_vault","industrial_works","academy_of_sciences","admiralty","pilgrimage_center");
    public BlueprintPlan generate(String id,int requested){if(!PROJECTS.contains(id))return null;int level=Math.max(1,Math.min(5,requested));var b=new Builder(level);switch(id){case "trade_exchange"->exchange(b);case "citadel"->citadel(b);case "seed_vault"->greenhouse(b);case "industrial_works"->works(b);case "academy_of_sciences"->academy(b);case "admiralty"->admiralty(b);case "pilgrimage_center"->pilgrims(b);default->throw new IllegalArgumentException(id);}return new BlueprintPlan(id,level,stageName(level),b.blocks);}
    public String stageName(int level){return List.of("Фундамент и подходы","Несущие стены","Крыша и рабочий корпус","Профильное оснащение","Городской центр специализации").get(Math.max(1,Math.min(5,level))-1);}
    private void hall(Builder b,int hx,int hz,Material wall,Material roof){b.floor(-hx-1,hx+1,-hz-1,hz+1,0,Material.STONE_BRICKS,1);b.floor(-1,1,-hz-3,-hz-2,0,Material.STONE_BRICKS,1);
        for(int y=1;y<=4;y++){for(int x=-hx;x<=hx;x++){if(x!=0||y>2)b.block(x,y,-hz,wall,2);b.block(x,y,hz,wall,2);}for(int z=-hz+1;z<hz;z++){b.block(-hx,y,z,wall,2);b.block(hx,y,z,wall,2);}}
        b.floor(-hx-1,hx+1,-hz-1,hz+1,5,roof,3);b.door(0,1,-hz,3);b.block(-hx+1,1,-hz+1,Material.BARREL,3);b.block(hx-1,1,-hz+1,Material.LANTERN,3);
    }
    private void exchange(Builder b){hall(b,6,5,Material.SMOOTH_SANDSTONE,Material.DARK_OAK_PLANKS);for(int x:new int[]{-4,4}){b.floor(x,x,-2,2,1,Material.BARREL,3);for(int z:new int[]{-2,0,2})b.block(x,2,z,Material.LECTERN,4);}b.floor(-2,2,2,3,1,Material.SMOOTH_QUARTZ,4);b.block(0,2,3,Material.GOLD_BLOCK,4);
        b.floor(-2,2,-2,2,6,Material.SMOOTH_SANDSTONE,5);for(int y=7;y<=8;y++)for(int x:new int[]{-2,2})for(int z:new int[]{-2,2})b.block(x,y,z,Material.QUARTZ_PILLAR,5);b.floor(-2,2,-2,2,9,Material.DARK_OAK_PLANKS,5);b.block(0,7,0,Material.GOLD_BLOCK,5);}
    private void citadel(Builder b){hall(b,7,6,Material.POLISHED_BLACKSTONE_BRICKS,Material.DEEPSLATE_BRICKS);for(int x:new int[]{-6,6})for(int z:new int[]{-5,5}){b.floor(x-1,x+1,z-1,z+1,6,Material.STONE_BRICKS,4);for(int y=7;y<=9;y++){for(int dx=-1;dx<=1;dx++)for(int dz=-1;dz<=1;dz++)if(Math.abs(dx)==1||Math.abs(dz)==1)b.block(x+dx,y,z+dz,Material.STONE_BRICKS,4);}b.floor(x-1,x+1,z-1,z+1,10,Material.STONE_BRICKS,4);b.block(x,11,z,Material.LANTERN,5);}for(int x=-8;x<=8;x+=2)for(int z:new int[]{-7,7})b.block(x,6,z,Material.POLISHED_BLACKSTONE_BRICKS,5);for(int z=-5;z<=5;z+=2)for(int x:new int[]{-8,8})b.block(x,6,z,Material.POLISHED_BLACKSTONE_BRICKS,5);b.block(-5,1,4,Material.SMITHING_TABLE,3);b.block(5,1,4,Material.FLETCHING_TABLE,3);}
    private void greenhouse(Builder b){hall(b,7,4,Material.GLASS,Material.GLASS);for(int x:new int[]{-6,6}){b.floor(x,x,-2,2,1,Material.MOSS_BLOCK,3);for(int z:new int[]{-2,0,2})b.block(x,2,z,Material.OAK_LEAVES,3);}b.floor(-3,-2,1,2,1,Material.COMPOSTER,4);b.floor(2,3,1,2,1,Material.BARREL,4);for(int x:new int[]{-5,5}){b.floor(x-1,x+1,6,8,0,Material.STONE_BRICKS,5);b.floor(x-1,x+1,6,8,1,Material.MOSS_BLOCK,5);b.block(x,2,7,Material.AZALEA_LEAVES,5);}for(int z=-3;z<=3;z+=3)b.block(0,1,z,Material.GLOWSTONE,5);}
    private void works(Builder b){hall(b,7,5,Material.DEEPSLATE_BRICKS,Material.CUT_COPPER);for(int x:new int[]{-4,4}){b.floor(x-1,x+1,0,2,1,Material.IRON_BLOCK,3);for(int z=0;z<=2;z++)b.block(x,2,z,Material.BLAST_FURNACE,3);b.block(x,3,1,Material.COPPER_BLOCK,4);}b.floor(-6,6,7,10,0,Material.STONE_BRICKS,4);for(int x:new int[]{-4,4})for(int y=1;y<=11;y++)b.block(x,y,9,Material.BRICKS,4);for(int x:new int[]{-4,4})b.block(x,12,9,Material.LIGHTNING_ROD,5);b.floor(-1,1,7,8,1,Material.CUT_COPPER,5);for(int z=7;z<=8;z++)b.block(0,2,z,Material.IRON_BLOCK,5);}
    private void academy(Builder b){hall(b,6,6,Material.QUARTZ_BRICKS,Material.SMOOTH_QUARTZ);for(int x:new int[]{-4,4})for(int z=0;z<=3;z++){b.block(x,1,z,Material.BOOKSHELF,3);b.block(x,2,z,Material.BOOKSHELF,4);}b.block(0,1,2,Material.ENCHANTING_TABLE,3);
        b.floor(-3,3,-3,3,6,Material.QUARTZ_BRICKS,4);for(int y=7;y<=9;y++){for(int x=-3;x<=3;x++)for(int z:new int[]{-3,3})b.block(x,y,z,Material.LIGHT_BLUE_STAINED_GLASS,4);for(int z=-2;z<=2;z++)for(int x:new int[]{-3,3})b.block(x,y,z,Material.LIGHT_BLUE_STAINED_GLASS,4);}b.floor(-3,3,-3,3,10,Material.LIGHT_BLUE_STAINED_GLASS,4);b.floor(-2,2,-2,2,11,Material.AMETHYST_BLOCK,5);b.floor(-1,1,-1,1,12,Material.SMOOTH_QUARTZ,5);b.block(0,13,0,Material.LIGHTNING_ROD,5);}
    private void admiralty(Builder b){hall(b,5,7,Material.PRISMARINE_BRICKS,Material.DARK_PRISMARINE);for(int x:new int[]{-3,3})for(int z=0;z<=4;z+=2)b.block(x,1,z,Material.CARTOGRAPHY_TABLE,3);b.floor(-6,6,9,13,0,Material.SPRUCE_PLANKS,4);for(int x:new int[]{-5,5})for(int z:new int[]{10,12}){b.block(x,1,z,Material.SPRUCE_FENCE,4);b.block(x,2,z,Material.LANTERN,4);}for(int y=6;y<=12;y++)b.block(0,y,5,Material.STRIPPED_SPRUCE_LOG,5);for(int x=-3;x<=3;x++)b.block(x,11,5,Material.STRIPPED_SPRUCE_LOG,5,Axis.X);for(int x=-2;x<=2;x++)for(int y=8;y<=10;y++)b.block(x,y,5,Material.WHITE_WOOL,5);b.block(0,13,5,Material.LANTERN,5);}
    private void pilgrims(Builder b){hall(b,6,5,Material.SMOOTH_SANDSTONE,Material.RED_SANDSTONE);for(int x:new int[]{-4,4}){b.floor(x-1,x+1,1,2,1,Material.OAK_PLANKS,3);b.block(x,2,2,Material.LANTERN,3);}b.floor(-2,2,3,4,1,Material.QUARTZ_BRICKS,4);b.floor(-1,1,3,4,2,Material.QUARTZ_BRICKS,4);b.block(0,3,4,Material.GOLD_BLOCK,4);
        for(int x:new int[]{-5,5}){for(int y=6;y<=9;y++)b.block(x,y,-4,Material.QUARTZ_PILLAR,5);b.floor(x-1,x+1,-5,-3,10,Material.RED_SANDSTONE,5);b.block(x,11,-4,Material.LANTERN,5);}b.floor(-2,2,-2,2,6,Material.RED_SANDSTONE,5);b.floor(-1,1,-1,1,7,Material.RED_SANDSTONE,5);b.block(0,8,0,Material.GOLD_BLOCK,5);}
    private static final class Builder{final int level;final Map<BlockOffset,BlueprintBlock> blocks=new LinkedHashMap<>();Builder(int level){this.level=level;}
        void block(int x,int y,int z,Material material,int stage){block(x,y,z,material,stage,Axis.Y);}void block(int x,int y,int z,Material material,int stage,Axis axis){if(stage<=level)blocks.putIfAbsent(new BlockOffset(x,y,z),new BlueprintBlock(material,BlockRole.RESIDENT,stage).withAxis(axis));}
        void floor(int x0,int x1,int z0,int z1,int y,Material material,int stage){for(int x=x0;x<=x1;x++)for(int z=z0;z<=z1;z++)block(x,y,z,material,stage);}
        void door(int x,int y,int z,int stage){if(stage>level)return;blocks.put(new BlockOffset(x,y,z),new BlueprintBlock(Material.SPRUCE_DOOR,BlockRole.RESIDENT,stage).asDoor(BlockFace.NORTH,Bisected.Half.BOTTOM,Door.Hinge.LEFT));blocks.put(new BlockOffset(x,y+1,z),new BlueprintBlock(Material.SPRUCE_DOOR,BlockRole.RESIDENT,stage).asDoor(BlockFace.NORTH,Bisected.Half.TOP,Door.Hinge.LEFT));}
    }
}
