package ru.neverland.townyresearch.gui;
import org.bukkit.*;
import org.bukkit.entity.Player;
import org.bukkit.event.*;
import org.bukkit.event.inventory.*;
import org.bukkit.inventory.*;
import ru.neverland.townyresearch.api.ResearchSnapshot;
import ru.neverland.townyresearch.model.*;
import ru.neverland.townyresearch.service.*;
import java.util.*;
import static ru.neverland.townyresearch.service.Ui.*;
public final class ResearchMenu implements Listener {
    private final org.bukkit.plugin.Plugin plugin;private final ResearchService service;
    private static final class View implements InventoryHolder {final UUID town;final String technology;final Map<Integer,Runnable> actions=new HashMap<>();Inventory inventory;View(UUID town,String technology){this.town=town;this.technology=technology;}public Inventory getInventory(){return inventory;}}
    public ResearchMenu(org.bukkit.plugin.Plugin plugin,ResearchService service){this.plugin=plugin;this.service=service;}
    private boolean access(Player p,UUID town){var t=service.town(p);return p.hasPermission("neverlandtownyresearch.admin")||(p.hasPermission("neverlandtownyresearch.use")&&t!=null&&t.getUUID().equals(town));}
    public void open(Player p,UUID town,String technology){if(!access(p,town)){tell(p,"&cНет доступа к исследованиям этого города.");return;}var snapshot=service.research(town).orElse(null);if(snapshot==null){tell(p,"Ожидается расчёт города.");return;}var v=new View(town,technology);v.inventory=Bukkit.createInventory(v,54,color("&6Исследования города"));
        if(technology==null){int[] slots={10,11,12,13,14,15,16};int i=0;for(var t:service.settings().technologies().values()){var lines=lore(snapshot,t);lines.add("Нажмите: требования и изучение.");button(v,slots[i++],icon(t.icon()),"&e"+t.name(),lines,()->open(p,town,t.id()));}}
        else{var t=service.settings().technologies().get(technology);if(t==null){tell(p,"Технология не найдена.");return;}button(v,13,icon(t.icon()),"&e"+t.name(),lore(snapshot,t),null);int learned=snapshot.state().learned().getOrDefault(t.id(),0);if(learned<t.levels().size()){var next=t.levels().get(learned);var requirements=new ArrayList<String>();next.buildings().forEach((id,n)->requirements.add((snapshot.buildings().getOrDefault(id,0)>=n?"&a✓ ":"&c✗ ")+BuildingNames.name(id)+" "+snapshot.buildings().getOrDefault(id,0)+"/"+n));next.requires().forEach((id,n)->requirements.add((snapshot.state().learned().getOrDefault(id,0)>=n?"&a✓ ":"&c✗ ")+service.settings().technologies().get(id).name()+" "+snapshot.state().learned().getOrDefault(id,0)+"/"+n));button(v,22,Material.BOOK,"&eТребования следующего уровня",requirements,null);
            button(v,31,Material.EXPERIENCE_BOTTLE,"&aНачать изучение",List.of("Цена: "+amount(next.knowledge())+" знаний","Время: "+time(next.seconds()),"При нехватке знаний проект ждёт пополнения.","Здания должны работать до конца изучения.","Доступно мэру и управляющим."),()->change(p,v,()->{if(service.level(town,t.id())!=learned||!t.equals(service.settings().technologies().get(t.id())))throw new IllegalStateException("Требования изменились. Обновите меню.");service.begin(town,t.id());}));}
            button(v,45,Material.ARROW,"&aВсе технологии",List.of(),()->open(p,town,null));}
        var active=snapshot.state().active();var lines=new ArrayList<String>();lines.add(snapshot.status());lines.add("В городском запасе: "+amount(snapshot.knowledge()));lines.add("Неприкосновенный резерв: "+amount(snapshot.reserve()));if(active!=null){var tech=service.settings().technologies().get(active.technology());lines.add("Проект: "+(tech==null?"Исследование":tech.name())+" "+active.level());lines.add("Осталось: "+time(active.remaining()));lines.add("Цена проекта: "+amount(active.cost())+" знаний");lines.add("Прогресс: "+(100L*(active.duration()-active.remaining())/active.duration())+"%");button(v,41,Material.RED_DYE,"&cОтменить исследование",List.of("Возврат неиспользованных знаний.","Завершающееся исследование отменить нельзя."),()->change(p,v,()->{var current=service.research(town).orElseThrow().state().active();if(current==null||!current.invoice().equals(active.invoice()))throw new IllegalStateException("Исследование изменилось. Обновите меню.");service.cancel(town);}));}
        button(v,40,Material.CLOCK,"&eНаучная работа",lines,null);button(v,49,Material.SPYGLASS,"&aОбновить",List.of(),()->open(p,town,technology));button(v,48,Material.CHEST,"&eЗапасы знаний",List.of("Открыть стратегические ресурсы."),()->p.performCommand("townyresources"));p.openInventory(v.inventory);
    }
    private List<String> lore(ResearchSnapshot s,Technology t){var result=new ArrayList<String>();int learned=s.state().learned().getOrDefault(t.id(),0);result.add(t.description());result.add("Изучено: "+learned+" / "+t.levels().size());result.add("Текущий бонус: "+bonus(t.id(),service.bonus(s.townId(),t.id())));if(!t.enabled())result.add("&cОтключено в настройках");for(int i=0;i<t.levels().size();i++){var level=t.levels().get(i);result.add("Уровень "+(i+1)+": "+amount(level.knowledge())+" знаний; "+time(level.seconds()));result.add("Бонус: "+bonus(t.id(),level.bonus()));}return result;}
    private static String bonus(String technology,double value){return technology.equals("navigation")?percent(value).replace("%"," п.п."):percent(value);}
    private static String time(int seconds){return seconds/60+" мин. "+seconds%60+" сек.";}
    private interface Action{void run()throws Exception;}
    private void change(Player player,View view,Action action){var town=service.town(player);if(town==null||!town.getUUID().equals(view.town)||!service.manager(player,town)){tell(player,"&cНужны права управляющего этого города.");return;}try{action.run();open(player,view.town,view.technology);}catch(Exception ex){tell(player,"&c"+ex.getMessage());}}
    private void button(View v,int slot,Material material,String name,List<String> lore,Runnable action){var item=new ItemStack(material);var meta=item.getItemMeta();meta.setDisplayName(color(name));meta.setLore(lore.stream().map(s->color("&7"+s)).toList());item.setItemMeta(meta);v.inventory.setItem(slot,item);if(action!=null)v.actions.put(slot,action);}
    @EventHandler public void click(InventoryClickEvent e){if(!(e.getView().getTopInventory().getHolder() instanceof View v))return;e.setCancelled(true);if(!(e.getWhoClicked() instanceof Player p))return;if(!access(p,v.town)){p.closeInventory();return;}var action=v.actions.get(e.getRawSlot());if(action!=null)Bukkit.getScheduler().runTask(plugin,()->{if(p.isOnline()&&p.getOpenInventory().getTopInventory().getHolder()==v&&access(p,v.town))action.run();});}
    @EventHandler public void drag(InventoryDragEvent e){if(e.getView().getTopInventory().getHolder() instanceof View)e.setCancelled(true);}
}
